package com.jiuyv.yl.console.finance.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户余额操作记录表 TBL_MHT_BALANCE_LOG : TBL_MHT_BALANCE_LOG
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtBalanceLogVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** logSeqNo : 记录序号. LOG_SEQ_NO: NUMBER(10) */
	private Long logSeqNo ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** mid : 商户号. MID: VARCHAR2(15) */
	private String mid ;
	
	/** stlmDate : 清算日期. STLM_DATE: CHAR(8) */
	private String stlmDate ;
	
	/** oprType : 操作类型. OPR_TYPE: CHAR(2) */
	private String oprType ;
	
	/** balance : 操作金额. BALANCE: NUMBER(12) */
	private Long balance ;
	
	/** lastUpdUser : 操作人. LAST_UPD_USER: VARCHAR2(30) */
	private String oprUser ;
	
	/** lastUpdTime : 操作日期. LAST_UPD_TIME: CHAR(14) */
	private String oprTime ;
	
	/** remark : 备注. REMARK: VARCHAR2(400) */
	private String remark ;
	
	/** payReqSeq : 出账处理付款单序号. PAY_REQ_SEQ: NUMBER(10) */
	private Long payReqSeq ;
	
	/** status : 状态. STATUS: CHAR(2) */
	private String status ;
	
	/** lockStatus : 冻结状态. LOCK_STATUS: CHAR(2) */
	private String lockStatus ;
	
	/** oriLogSeqNo : 原冻结记录序号. ORI_LOG_SEQ_NO: NUMBER(10) */
	private Long oriLogSeqNo ;
	
	/** settleSeqNo : 结算调整款单号. SETTLE_SEQ_NO: NUMBER(10) */
	private Long settleSeqNo;
	
	/** lastUpdOrg : 最后更新机构. LAST_UPD_ORG: VARCHAR2(30) */
	private String lastUpdOrg ;
	
	/** lastUpdTime : 最后更新时间. LAST_UPD_TIME: CHAR(14) */
	private String lastUpdTime ;
	
	/** lastUpdUser : 最后更新账号. LAST_UPD_USER: VARCHAR2(30) */
	private String lastUpdUser ;
	
	/** unlockTime : 解冻时间. UNLOCK_TIME: CHAR(14) */
	private String unlockTime;
	
	// -- Extend -- 
	
	/** 更新后余额  */
	private Long finalAmt;
	
	/** 操作类型描述  */
	private String oprTypeDesc;
	
	/** 冻结标识描述  */
	private String lockStatusDesc;
	
	/** 状态 */
	private String statusDesc;
    
	/** 商户名称 */
	private String merName;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MhtBalanceLogVo() {
		// Default Construtor
	}
	
	public MhtBalanceLogVo(Long logSeqNo) {
		this.logSeqNo = logSeqNo;
	}
		
	// -- Setter And Getter
	/**
	 * Set logSeqNo : 记录序号. LOG_SEQ_NO: NUMBER(10) 
	 */
	public void setLogSeqNo(Long logSeqNo){
		this.logSeqNo = logSeqNo;	
	}
	
	/**
	 * Get logSeqNo : 记录序号. LOG_SEQ_NO: NUMBER(10) 
	 */
	public Long getLogSeqNo(){
		return this.logSeqNo;	
	}
	
	/**
	 * Set mid : 商户号. MID: VARCHAR2(15) 
	 */
	public void setMid(String mid){
		this.mid = mid;	
	}
	
	/**
	 * Get mid : 商户号. MID: VARCHAR2(15) 
	 */
	public String getMid(){
		return this.mid;	
	}
	
	/**
	 * Set oprType : 操作类型. OPR_TYPE: CHAR(2) 
	 */
	public void setOprType(String oprType){
		this.oprType = oprType;	
	}
	
	/**
	 * Get oprType : 操作类型. OPR_TYPE: CHAR(2) 
	 */
	public String getOprType(){
		return this.oprType;	
	}
	
	/**
	 * Set balance : 操作金额. BALANCE: NUMBER(12) 
	 */
	public void setBalance(Long balance){
		this.balance = balance;	
	}
	
	/**
	 * Get balance : 操作金额. BALANCE: NUMBER(12) 
	 */
	public Long getBalance(){
		return this.balance;	
	}
	
	/**
	 * Set lastUpdUser : 操作人. LAST_UPD_USER: VARCHAR2(30) 
	 */
	public void setLastUpdUser(String lastUpdUser){
		this.lastUpdUser = lastUpdUser;	
	}
	
	/**
	 * Get lastUpdUser : 操作人. LAST_UPD_USER: VARCHAR2(30) 
	 */
	public String getLastUpdUser(){
		return this.lastUpdUser;	
	}
	
	/**
	 * Set lastUpdTime : 操作日期. LAST_UPD_TIME: CHAR(14) 
	 */
	public void setLastUpdTime(String lastUpdTime){
		this.lastUpdTime = lastUpdTime;	
	}
	
	/**
	 * Get lastUpdTime : 操作日期. LAST_UPD_TIME: CHAR(14) 
	 */
	public String getLastUpdTime(){
		return this.lastUpdTime;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR2(400) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR2(400) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set payReqSeq : 出账处理付款单序号. PAY_REQ_SEQ: NUMBER(10) 
	 */
	public void setPayReqSeq(Long payReqSeq){
		this.payReqSeq = payReqSeq;	
	}
	
	/**
	 * Get payReqSeq : 出账处理付款单序号. PAY_REQ_SEQ: NUMBER(10) 
	 */
	public Long getPayReqSeq(){
		return this.payReqSeq;	
	}
	
	/**
	 * @return the lockStatus
	 */
	public String getLockStatus() {
		return lockStatus;
	}

	/**
	 * @param lockStatus the lockStatus to set
	 */
	public void setLockStatus(String lockStatus) {
		this.lockStatus = lockStatus;
	}

	/**
	 * Set status : 状态. STATUS: CHAR(2) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: CHAR(2) 
	 */
	public String getStatus(){
		return this.status;	
	}

	/**
	 * @return the oprUser
	 */
	public String getOprUser() {
		return oprUser;
	}

	/**
	 * @param oprUser the oprUser to set
	 */
	public void setOprUser(String oprUser) {
		this.oprUser = oprUser;
	}

	/**
	 * @return the oprTime
	 */
	public String getOprTime() {
		return oprTime;
	}

	/**
	 * @param oprTime the oprTime to set
	 */
	public void setOprTime(String oprTime) {
		this.oprTime = oprTime;
	}

	/**
	 * @return the lastUpdOrg
	 */
	public String getLastUpdOrg() {
		return lastUpdOrg;
	}

	/**
	 * @param lastUpdOrg the lastUpdOrg to set
	 */
	public void setLastUpdOrg(String lastUpdOrg) {
		this.lastUpdOrg = lastUpdOrg;
	}

	/**
	 * @return the version
	 */
	public Long getVersion() {
		return version;
	}

	/**
	 * @param version the version to set
	 */
	public void setVersion(Long version) {
		this.version = version;
	}

	/**
	 * @return the finalAmt
	 */
	public Long getFinalAmt() {
		return finalAmt;
	}

	/**
	 * @param finalAmt the finalAmt to set
	 */
	public void setFinalAmt(Long finalAmt) {
		this.finalAmt = finalAmt;
	}

	/**
	 * @return the oprTypeDesc
	 */
	public String getOprTypeDesc() {
		return oprTypeDesc;
	}

	/**
	 * @param oprTypeDesc the oprTypeDesc to set
	 */
	public void setOprTypeDesc(String oprTypeDesc) {
		this.oprTypeDesc = oprTypeDesc;
	}

	/**
	 * @return the lockStatusDesc
	 */
	public String getLockStatusDesc() {
		return lockStatusDesc;
	}

	/**
	 * @param lockStatusDesc the lockStatusDesc to set
	 */
	public void setLockStatusDesc(String lockStatusDesc) {
		this.lockStatusDesc = lockStatusDesc;
	}

	/**
	 * @return the statusDesc
	 */
	public String getStatusDesc() {
		return statusDesc;
	}

	/**
	 * @param statusDesc the statusDesc to set
	 */
	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	/**
	 * @return the stlmDate
	 */
	public String getStlmDate() {
		return stlmDate;
	}

	/**
	 * @param stlmDate the stlmDate to set
	 */
	public void setStlmDate(String stlmDate) {
		this.stlmDate = stlmDate;
	}

	/**
	 * @return the oriLogSeqNo
	 */
	public Long getOriLogSeqNo() {
		return oriLogSeqNo;
	}

	/**
	 * @param oriLogSeqNo the oriLogSeqNo to set
	 */
	public void setOriLogSeqNo(Long oriLogSeqNo) {
		this.oriLogSeqNo = oriLogSeqNo;
	}

	/**
	 * @return the settleSeqNo
	 */
	public Long getSettleSeqNo() {
		return settleSeqNo;
	}

	/**
	 * @param settleSeqNo the settleSeqNo to set
	 */
	public void setSettleSeqNo(Long settleSeqNo) {
		this.settleSeqNo = settleSeqNo;
	}

	/**
	 * @return the merName
	 */
	public String getMerName() {
		return merName;
	}

	/**
	 * @param merName the merName to set
	 */
	public void setMerName(String merName) {
		this.merName = merName;
	}

	/**
	 * @return the unlockTime
	 */
	public String getUnlockTime() {
		return unlockTime;
	}

	/**
	 * @param unlockTime the unlockTime to set
	 */
	public void setUnlockTime(String unlockTime) {
		this.unlockTime = unlockTime;
	}

}