package com.jiuyv.yl.console.finance.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class NetPayVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	
	/** 转账类型 */
	private String payType;
	
	/** 付款账号 */
	private String payAccntNo;
	
	/** 收款账号 */
	private String receviceAccntNo;
	
	/** 收款人姓名 */
	private String receviceAccntName;
	
	/** 收款人开户行名称 */
	private String receviceAccntBank;
	
	/** 收款人开户行网点名称 */
	private String receviceBranchBankName;
	
	/** 收款人开户行网点号 */
	private String receviceBranchBankNo;
	
	/** 交易金额 */
	private Long transAmt;
	
	/** 用途 */
	private String purpose;
	
	/** 加急标识 */
	private String flag;

	// -- Extends --
	/** 收款账户类型 */
	private String receviceAccntType;
	
	/** 收款银行大行号 */
	private String receviceBankTitle;
	
	/** 收款银行地区 */
	private String receviceBankArea;
	
	/** 交易金额格式化 */
	private String transAmtDesc;
	/**
	 * @return the payType
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * @param payType the payType to set
	 */
	public void setPayType(String payType) {
		this.payType = payType;
	}

	/**
	 * @return the payAccntNo
	 */
	public String getPayAccntNo() {
		return payAccntNo;
	}

	/**
	 * @param payAccntNo the payAccntNo to set
	 */
	public void setPayAccntNo(String payAccntNo) {
		this.payAccntNo = payAccntNo;
	}

	/**
	 * @return the receviceAccntNo
	 */
	public String getReceviceAccntNo() {
		return receviceAccntNo;
	}

	/**
	 * @param receviceAccntNo the receviceAccntNo to set
	 */
	public void setReceviceAccntNo(String receviceAccntNo) {
		this.receviceAccntNo = receviceAccntNo;
	}

	/**
	 * @return the receviceAccntName
	 */
	public String getReceviceAccntName() {
		return receviceAccntName;
	}

	/**
	 * @param receviceAccntName the receviceAccntName to set
	 */
	public void setReceviceAccntName(String receviceAccntName) {
		this.receviceAccntName = receviceAccntName;
	}

	/**
	 * @return the receviceAccntBank
	 */
	public String getReceviceAccntBank() {
		return receviceAccntBank;
	}

	/**
	 * @param receviceAccntBank the receviceAccntBank to set
	 */
	public void setReceviceAccntBank(String receviceAccntBank) {
		this.receviceAccntBank = receviceAccntBank;
	}

	/**
	 * @return the receviceBranchBankName
	 */
	public String getReceviceBranchBankName() {
		return receviceBranchBankName;
	}

	/**
	 * @param receviceBranchBankName the receviceBranchBankName to set
	 */
	public void setReceviceBranchBankName(String receviceBranchBankName) {
		this.receviceBranchBankName = receviceBranchBankName;
	}

	/**
	 * @return the receviceBranchBankNo
	 */
	public String getReceviceBranchBankNo() {
		return receviceBranchBankNo;
	}

	/**
	 * @param receviceBranchBankNo the receviceBranchBankNo to set
	 */
	public void setReceviceBranchBankNo(String receviceBranchBankNo) {
		this.receviceBranchBankNo = receviceBranchBankNo;
	}

	/**
	 * @return the transAmt
	 */
	public Long getTransAmt() {
		return transAmt;
	}

	/**
	 * @param transAmt the transAmt to set
	 */
	public void setTransAmt(Long transAmt) {
		this.transAmt = transAmt;
	}

	/**
	 * @return the purpose
	 */
	public String getPurpose() {
		return purpose;
	}

	/**
	 * @param purpose the purpose to set
	 */
	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	/**
	 * @return the flag
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * @param flag the flag to set
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * @return the receviceAccntType
	 */
	public String getReceviceAccntType() {
		return receviceAccntType;
	}

	/**
	 * @param receviceAccntType the receviceAccntType to set
	 */
	public void setReceviceAccntType(String receviceAccntType) {
		this.receviceAccntType = receviceAccntType;
	}

	/**
	 * @return the receviceBankTitle
	 */
	public String getReceviceBankTitle() {
		return receviceBankTitle;
	}

	/**
	 * @param receviceBankTitle the receviceBankTitle to set
	 */
	public void setReceviceBankTitle(String receviceBankTitle) {
		this.receviceBankTitle = receviceBankTitle;
	}

	/**
	 * @return the receviceBankArea
	 */
	public String getReceviceBankArea() {
		return receviceBankArea;
	}

	/**
	 * @param receviceBankArea the receviceBankArea to set
	 */
	public void setReceviceBankArea(String receviceBankArea) {
		this.receviceBankArea = receviceBankArea;
	}

	/**
	 * @return the transAmtDesc
	 */
	public String getTransAmtDesc() {
		return transAmtDesc;
	}

	/**
	 * @param transAmtDesc the transAmtDesc to set
	 */
	public void setTransAmtDesc(String transAmtDesc) {
		this.transAmtDesc = transAmtDesc;
	}
	
}