package com.jiuyv.yl.console.finance.entity ;

import java.util.List;

// Generated by AutoCode4J
/**
 * EntityBean: 付款申请表 : TBL_STLM_PAY_REQ
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class StlmPayReqVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** seqNo : 序号. SEQ_NO: NUMBER(10) */
	private Long seqNo ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** payBillNo : 申请表编号. PAY_BILL_NO: VARCHAR2(60) */
	private String payBillNo ;
	
	/** bgnSday : 开始清算日. BGN_SDAY: CHAR(8) */
	private String bgnSday ;
	
	/** endSday : 结束清算日. END_SDAY: CHAR(8) */
	private String endSday ;
	
	/** bankAccntId : 付款账户序号. BANK_ACCNT_ID: NUMBER(5) */
	private Long bankAccntId ;
	
	/** bankId : 支付机构号. BANK_ID: VARCHAR2(15) */
	private String bankId ;
	
	/** payReqType : 申请类型. PAY_REQ_TYPE: VARCHAR2(2) */
	private String payReqType ;
	
	/** channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(15) */
	private String channelCode ;
	
	/** status : 状态. STATUS: VARCHAR2(2) */
	private String status ;
	
	/** audTime : 审核时间. AUD_TIME: CHAR(14) */
	private String audTime ;
	
	/** audUser : 审核人. AUD_USER: VARCHAR2(30) */
	private String audUser ;
	
	/** audRemark : 审核意见. AUD_REMARK: VARCHAR2(200) */
	private String audRemark ;
	
	/** secAudTime : 确认时间. SEC_AUD_TIME: CHAR(14) */
	private String secAudTime ;
	
	/** secAudUser : 确认用户. SEC_AUD_USER: VARCHAR2(30) */
	private String secAudUser ;
	
	/** secAudRemark : 确认意见. SEC_AUD_REMARK: VARCHAR2(200) */
	private String secAudRemark ;
	
	/** stlmAmt : 清算金额. STLM_AMT: NUMBER(14) */
	private Long stlmAmt ;
	
	/** flowFee : 流量费. FLOW_FEE: NUMBER(12) */
	private Long flowFee ;
	
	/** realAmt : 应付金额（清算金额-流量费）. REAL_AMT: NUMBER(14) */
	private Long realAmt ;
	
	/** bankRealAmt : 实付金额. BANK_REAL_AMT: NUMBER(14) */
	private Long bankRealAmt ;
	
	/** stlmCount : 清算笔数. STLM_COUNT: NUMBER(10) */
	private Long stlmCount ;
	
	/** bankNo : 行号. BANK_NO: VARCHAR2(20) */
	private String bankNo ;
	
	/** accntNo : 账号. ACCNT_NO: VARCHAR2(30) */
	private String accntNo ;
	
	/** bankName : 支行名. BANK_NAME: VARCHAR2(100) */
	private String bankName ;
	
	/** bankTitle : 总行名. BANK_TITLE: VARCHAR2(100) */
	private String bankTitle ;
	
	/** accntName : 账户名称. ACCNT_NAME: VARCHAR2(100) */
	private String accntName ;
	
	/** lastUpdOrg : 最后更新机构. LAST_UPD_ORG: VARCHAR2(30) */
	private String lastUpdOrg ;
	
	/** lastUpdUser : 最后更新用户. LAST_UPD_USER: VARCHAR2(30) */
	private String lastUpdUser ;
	
	/** lastUpdTime : 最后更新时间. LAST_UPD_TIME: CHAR(14) */
	private String lastUpdTime ;
	
	/** createUser : 创建用户. CREATE_USER: VARCHAR2(30) */
	private String createUser ;
	
	/** createTime : 创建时间. CREATE_TIME: CHAR(14) */
	private String createTime ;
	
	/** chnlBankNo : 服务商行号. CHNL_BANK_NO: VARCHAR2(20) */
	private String chnlBankNo ;
	
	/** chnlAccntNo : 服务商账号. CHNL_ACCNT_NO: VARCHAR2(30) */
	private String chnlAccntNo ;
	
	/** chnlBankName : 服务商银行名称. CHNL_BANK_NAME: VARCHAR2(100) */
	private String chnlBankName ;
	
	/** chnlAccntName : 服务商账户名. CHNL_ACCNT_NAME: VARCHAR2(100) */
	private String chnlAccntName ;
	
	/** chnlPersonCardNo : 服务商持卡人证件号. CHNL_PERSON_CARD_NO: VARCHAR2(30) */
	private String chnlPersonCardNo ;
	
	/** transAmt : 交易金额. TRANS_AMT: NUMBER(10) */
	private Long transAmt ;
	
	/** minusAmt : 强扣金额. MINUS_AMT: NUMBER(10) */
	private Long minusAmt ;
	
	/** otherAmt : 其他金额. OTHER_AMT: NUMBER(10) */
	private Long otherAmt ;
	
	/** remark : 备注. REMARK: VARCHAR2(400) */
	private String remark ;
	
	/** crtFailRemark : 申请单剔除备注. CRT_FAIL_REMARK: VARCHAR2(400) */
	private String crtFailRemark ;
	
	/** appFailRemark : 出账剔除备注. APP_FAIL_REMARK: VARCHAR2(400) */
	private String appFailRemark ; 
	
	/** amtFailRemark : 出款失败备注. AMT_FAIL_REMARK: VARCHAR2(400) */
	private String amtFailRemark ;
	
	// -- Extended --
	/** payReqTypeDesc : （描述）申请类型. PAY_REQ_TYPE: VARCHAR2(2) */
	private String payReqTypeDesc ;
	
	/** statusDesc : （描述）状态. STATUS: VARCHAR2(2) */
	private String statusDesc ;
	
	/** bankAccntIdDesc : （描述）付款账户序号. BANK_ACCNT_ID: NUMBER(5) */
	private String bankAccntIdDesc ;
	
	/** channelCodeDesc : （描述）服务商编号. CHANNEL_CODE: VARCHAR2(15) */
	private String channelCodeDesc ;
	
	/** bankAccntList : 商户开户行号集合. */
	private String accntBankStringList ;
	
	/** bankAccntList : (描述)商户开户行号集合. */
	private String accntBankStringListDesc ;
	
	/** bankAccntList : 商户开户行号集合. */
	private List<String> accntBankList ;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public StlmPayReqVo() {
		// Default Construtor
	}
	
	public StlmPayReqVo(Long seqNo) {
		this.seqNo = seqNo;
	}
		
	// -- Setter And Getter
	/**
	 * Set seqNo : 序号. SEQ_NO: NUMBER(10) 
	 */
	public void setSeqNo(Long seqNo){
		this.seqNo = seqNo;	
	}
	
	/**
	 * Get seqNo : 序号. SEQ_NO: NUMBER(10) 
	 */
	public Long getSeqNo(){
		return this.seqNo;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set payBillNo : 申请表编号. PAY_BILL_NO: VARCHAR2(60) 
	 */
	public void setPayBillNo(String payBillNo){
		this.payBillNo = payBillNo;	
	}
	
	/**
	 * Get payBillNo : 申请表编号. PAY_BILL_NO: VARCHAR2(60) 
	 */
	public String getPayBillNo(){
		return this.payBillNo;	
	}
	
	/**
	 * Set bgnSday : 开始清算日. BGN_SDAY: CHAR(8) 
	 */
	public void setBgnSday(String bgnSday){
		this.bgnSday = bgnSday;	
	}
	
	/**
	 * Get bgnSday : 开始清算日. BGN_SDAY: CHAR(8) 
	 */
	public String getBgnSday(){
		return this.bgnSday;	
	}
	
	/**
	 * Set endSday : 结束清算日. END_SDAY: CHAR(8) 
	 */
	public void setEndSday(String endSday){
		this.endSday = endSday;	
	}
	
	/**
	 * Get endSday : 结束清算日. END_SDAY: CHAR(8) 
	 */
	public String getEndSday(){
		return this.endSday;	
	}
	
	/**
	 * Set bankAccntId : 付款账户序号. BANK_ACCNT_ID: NUMBER(5) 
	 */
	public void setBankAccntId(Long bankAccntId){
		this.bankAccntId = bankAccntId;	
	}
	
	/**
	 * Get bankAccntId : 付款账户序号. BANK_ACCNT_ID: NUMBER(5) 
	 */
	public Long getBankAccntId(){
		return this.bankAccntId;	
	}
	
	/**
	 * Set bankId : 支付机构号. BANK_ID: VARCHAR2(15) 
	 */
	public void setBankId(String bankId){
		this.bankId = bankId;	
	}
	
	/**
	 * Get bankId : 支付机构号. BANK_ID: VARCHAR2(15) 
	 */
	public String getBankId(){
		return this.bankId;	
	}
	
	/**
	 * Set payReqType : 申请类型. PAY_REQ_TYPE: VARCHAR2(2) 
	 */
	public void setPayReqType(String payReqType){
		this.payReqType = payReqType;	
	}
	
	/**
	 * Get payReqType : 申请类型. PAY_REQ_TYPE: VARCHAR2(2) 
	 */
	public String getPayReqType(){
		return this.payReqType;	
	}
	
	/**
	 * Set channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(15) 
	 */
	public void setChannelCode(String channelCode){
		this.channelCode = channelCode;	
	}
	
	/**
	 * Get channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(15) 
	 */
	public String getChannelCode(){
		return this.channelCode;	
	}
	
	/**
	 * Set status : 状态. STATUS: VARCHAR2(2) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: VARCHAR2(2) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set audTime : 审核时间. AUD_TIME: CHAR(14) 
	 */
	public void setAudTime(String audTime){
		this.audTime = audTime;	
	}
	
	/**
	 * Get audTime : 审核时间. AUD_TIME: CHAR(14) 
	 */
	public String getAudTime(){
		return this.audTime;	
	}
	
	/**
	 * Set audUser : 审核人. AUD_USER: VARCHAR2(30) 
	 */
	public void setAudUser(String audUser){
		this.audUser = audUser;	
	}
	
	/**
	 * Get audUser : 审核人. AUD_USER: VARCHAR2(30) 
	 */
	public String getAudUser(){
		return this.audUser;	
	}
	
	/**
	 * Set audRemark : 审核意见. AUD_REMARK: VARCHAR2(200) 
	 */
	public void setAudRemark(String audRemark){
		this.audRemark = audRemark;	
	}
	
	/**
	 * Get audRemark : 审核意见. AUD_REMARK: VARCHAR2(200) 
	 */
	public String getAudRemark(){
		return this.audRemark;	
	}
	
	/**
	 * Set secAudTime : 确认时间. SEC_AUD_TIME: CHAR(14) 
	 */
	public void setSecAudTime(String secAudTime){
		this.secAudTime = secAudTime;	
	}
	
	/**
	 * Get secAudTime : 确认时间. SEC_AUD_TIME: CHAR(14) 
	 */
	public String getSecAudTime(){
		return this.secAudTime;	
	}
	
	/**
	 * Set secAudUser : 确认用户. SEC_AUD_USER: VARCHAR2(30) 
	 */
	public void setSecAudUser(String secAudUser){
		this.secAudUser = secAudUser;	
	}
	
	/**
	 * Get secAudUser : 确认用户. SEC_AUD_USER: VARCHAR2(30) 
	 */
	public String getSecAudUser(){
		return this.secAudUser;	
	}
	
	/**
	 * Set secAudRemark : 确认意见. SEC_AUD_REMARK: VARCHAR2(200) 
	 */
	public void setSecAudRemark(String secAudRemark){
		this.secAudRemark = secAudRemark;	
	}
	
	/**
	 * Get secAudRemark : 确认意见. SEC_AUD_REMARK: VARCHAR2(200) 
	 */
	public String getSecAudRemark(){
		return this.secAudRemark;	
	}
	
	/**
	 * Set stlmAmt : 清算金额. STLM_AMT: NUMBER(14) 
	 */
	public void setStlmAmt(Long stlmAmt){
		this.stlmAmt = stlmAmt;	
	}
	
	/**
	 * Get stlmAmt : 清算金额. STLM_AMT: NUMBER(14) 
	 */
	public Long getStlmAmt(){
		return this.stlmAmt;	
	}
	
	/**
	 * Set flowFee : 流量费. FLOW_FEE: NUMBER(12) 
	 */
	public void setFlowFee(Long flowFee){
		this.flowFee = flowFee;	
	}
	
	/**
	 * Get flowFee : 流量费. FLOW_FEE: NUMBER(12) 
	 */
	public Long getFlowFee(){
		return this.flowFee;	
	}
	
	/**
	 * Set realAmt : 应付金额（清算金额-流量费）. REAL_AMT: NUMBER(14) 
	 */
	public void setRealAmt(Long realAmt){
		this.realAmt = realAmt;	
	}
	
	/**
	 * Get realAmt : 应付金额（清算金额-流量费）. REAL_AMT: NUMBER(14) 
	 */
	public Long getRealAmt(){
		return this.realAmt;	
	}
	
	/**
	 * Set bankRealAmt : 实付金额. BANK_REAL_AMT: NUMBER(14) 
	 */
	public void setBankRealAmt(Long bankRealAmt){
		this.bankRealAmt = bankRealAmt;	
	}
	
	/**
	 * Get bankRealAmt : 实付金额. BANK_REAL_AMT: NUMBER(14) 
	 */
	public Long getBankRealAmt(){
		return this.bankRealAmt;	
	}
	
	/**
	 * Set stlmCount : 清算笔数. STLM_COUNT: NUMBER(10) 
	 */
	public void setStlmCount(Long stlmCount){
		this.stlmCount = stlmCount;	
	}
	
	/**
	 * Get stlmCount : 清算笔数. STLM_COUNT: NUMBER(10) 
	 */
	public Long getStlmCount(){
		return this.stlmCount;	
	}
	
	/**
	 * Set bankNo : 行号. BANK_NO: VARCHAR2(20) 
	 */
	public void setBankNo(String bankNo){
		this.bankNo = bankNo;	
	}
	
	/**
	 * Get bankNo : 行号. BANK_NO: VARCHAR2(20) 
	 */
	public String getBankNo(){
		return this.bankNo;	
	}
	
	/**
	 * Set accntNo : 账号. ACCNT_NO: VARCHAR2(30) 
	 */
	public void setAccntNo(String accntNo){
		this.accntNo = accntNo;	
	}
	
	/**
	 * Get accntNo : 账号. ACCNT_NO: VARCHAR2(30) 
	 */
	public String getAccntNo(){
		return this.accntNo;	
	}
	
	/**
	 * Set bankName : 支行名. BANK_NAME: VARCHAR2(100) 
	 */
	public void setBankName(String bankName){
		this.bankName = bankName;	
	}
	
	/**
	 * Get bankName : 支行名. BANK_NAME: VARCHAR2(100) 
	 */
	public String getBankName(){
		return this.bankName;	
	}
	
	/**
	 * Set bankTitle : 总行名. BANK_TITLE: VARCHAR2(100) 
	 */
	public void setBankTitle(String bankTitle){
		this.bankTitle = bankTitle;	
	}
	
	/**
	 * Get bankTitle : 总行名. BANK_TITLE: VARCHAR2(100) 
	 */
	public String getBankTitle(){
		return this.bankTitle;	
	}
	
	/**
	 * Set accntName : 账户名称. ACCNT_NAME: VARCHAR2(100) 
	 */
	public void setAccntName(String accntName){
		this.accntName = accntName;	
	}
	
	/**
	 * Get accntName : 账户名称. ACCNT_NAME: VARCHAR2(100) 
	 */
	public String getAccntName(){
		return this.accntName;	
	}
	
	/**
	 * Set lastUpdOrg : 最后更新机构. LAST_UPD_ORG: VARCHAR2(30) 
	 */
	public void setLastUpdOrg(String lastUpdOrg){
		this.lastUpdOrg = lastUpdOrg;	
	}
	
	/**
	 * Get lastUpdOrg : 最后更新机构. LAST_UPD_ORG: VARCHAR2(30) 
	 */
	public String getLastUpdOrg(){
		return this.lastUpdOrg;	
	}
	
	/**
	 * Set lastUpdUser : 最后更新用户. LAST_UPD_USER: VARCHAR2(30) 
	 */
	public void setLastUpdUser(String lastUpdUser){
		this.lastUpdUser = lastUpdUser;	
	}
	
	/**
	 * Get lastUpdUser : 最后更新用户. LAST_UPD_USER: VARCHAR2(30) 
	 */
	public String getLastUpdUser(){
		return this.lastUpdUser;	
	}
	
	/**
	 * Set lastUpdTime : 最后更新时间. LAST_UPD_TIME: CHAR(14) 
	 */
	public void setLastUpdTime(String lastUpdTime){
		this.lastUpdTime = lastUpdTime;	
	}
	
	/**
	 * Get lastUpdTime : 最后更新时间. LAST_UPD_TIME: CHAR(14) 
	 */
	public String getLastUpdTime(){
		return this.lastUpdTime;	
	}
	
	/**
	 * Set createUser : 创建用户. CREATE_USER: VARCHAR2(30) 
	 */
	public void setCreateUser(String createUser){
		this.createUser = createUser;	
	}
	
	/**
	 * Get createUser : 创建用户. CREATE_USER: VARCHAR2(30) 
	 */
	public String getCreateUser(){
		return this.createUser;	
	}
	
	/**
	 * Set createTime : 创建时间. CREATE_TIME: CHAR(14) 
	 */
	public void setCreateTime(String createTime){
		this.createTime = createTime;	
	}
	
	/**
	 * Get createTime : 创建时间. CREATE_TIME: CHAR(14) 
	 */
	public String getCreateTime(){
		return this.createTime;	
	}
	
	/**
	 * Set chnlBankNo : 服务商行号. CHNL_BANK_NO: VARCHAR2(20) 
	 */
	public void setChnlBankNo(String chnlBankNo){
		this.chnlBankNo = chnlBankNo;	
	}
	
	/**
	 * Get chnlBankNo : 服务商行号. CHNL_BANK_NO: VARCHAR2(20) 
	 */
	public String getChnlBankNo(){
		return this.chnlBankNo;	
	}
	
	/**
	 * Set chnlAccntNo : 服务商账号. CHNL_ACCNT_NO: VARCHAR2(30) 
	 */
	public void setChnlAccntNo(String chnlAccntNo){
		this.chnlAccntNo = chnlAccntNo;	
	}
	
	/**
	 * Get chnlAccntNo : 服务商账号. CHNL_ACCNT_NO: VARCHAR2(30) 
	 */
	public String getChnlAccntNo(){
		return this.chnlAccntNo;	
	}
	
	/**
	 * Set chnlBankName : 服务商银行名称. CHNL_BANK_NAME: VARCHAR2(100) 
	 */
	public void setChnlBankName(String chnlBankName){
		this.chnlBankName = chnlBankName;	
	}
	
	/**
	 * Get chnlBankName : 服务商银行名称. CHNL_BANK_NAME: VARCHAR2(100) 
	 */
	public String getChnlBankName(){
		return this.chnlBankName;	
	}
	
	/**
	 * Set chnlAccntName : 服务商账户名. CHNL_ACCNT_NAME: VARCHAR2(100) 
	 */
	public void setChnlAccntName(String chnlAccntName){
		this.chnlAccntName = chnlAccntName;	
	}
	
	/**
	 * Get chnlAccntName : 服务商账户名. CHNL_ACCNT_NAME: VARCHAR2(100) 
	 */
	public String getChnlAccntName(){
		return this.chnlAccntName;	
	}
	
	/**
	 * Set chnlPersonCardNo : 服务商持卡人证件号. CHNL_PERSON_CARD_NO: VARCHAR2(30) 
	 */
	public void setChnlPersonCardNo(String chnlPersonCardNo){
		this.chnlPersonCardNo = chnlPersonCardNo;	
	}
	
	/**
	 * Get chnlPersonCardNo : 服务商持卡人证件号. CHNL_PERSON_CARD_NO: VARCHAR2(30) 
	 */
	public String getChnlPersonCardNo(){
		return this.chnlPersonCardNo;	
	}

	/**
	 * @return the payReqTypeDesc
	 */
	public String getPayReqTypeDesc() {
		return payReqTypeDesc;
	}

	/**
	 * @param payReqTypeDesc the payReqTypeDesc to set
	 */
	public void setPayReqTypeDesc(String payReqTypeDesc) {
		this.payReqTypeDesc = payReqTypeDesc;
	}

	/**
	 * @return the statusDesc
	 */
	public String getStatusDesc() {
		return statusDesc;
	}

	/**
	 * @param statusDesc the statusDesc to set
	 */
	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	/**
	 * @return the bankAccntIdDesc
	 */
	public String getBankAccntIdDesc() {
		return bankAccntIdDesc;
	}

	/**
	 * @param bankAccntIdDesc the bankAccntIdDesc to set
	 */
	public void setBankAccntIdDesc(String bankAccntIdDesc) {
		this.bankAccntIdDesc = bankAccntIdDesc;
	}

	/**
	 * @return the channelCodeDesc
	 */
	public String getChannelCodeDesc() {
		return channelCodeDesc;
	}

	/**
	 * @param channelCodeDesc the channelCodeDesc to set
	 */
	public void setChannelCodeDesc(String channelCodeDesc) {
		this.channelCodeDesc = channelCodeDesc;
	}

	/**
	 * @return the transAmt
	 */
	public Long getTransAmt() {
		return transAmt;
	}

	/**
	 * @param transAmt the transAmt to set
	 */
	public void setTransAmt(Long transAmt) {
		this.transAmt = transAmt;
	}

	/**
	 * @return the minusAmt
	 */
	public Long getMinusAmt() {
		return minusAmt;
	}

	/**
	 * @param minusAmt the minusAmt to set
	 */
	public void setMinusAmt(Long minusAmt) {
		this.minusAmt = minusAmt;
	}

	/**
	 * @return the otherAmt
	 */
	public Long getOtherAmt() {
		return otherAmt;
	}

	/**
	 * @param otherAmt the otherAmt to set
	 */
	public void setOtherAmt(Long otherAmt) {
		this.otherAmt = otherAmt;
	}

	/**
	 * @return the remark
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * @param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * @return the crtFailRemark
	 */
	public String getCrtFailRemark() {
		return crtFailRemark;
	}

	/**
	 * @param crtFailRemark the crtFailRemark to set
	 */
	public void setCrtFailRemark(String crtFailRemark) {
		this.crtFailRemark = crtFailRemark;
	}

	/**
	 * @return the appFailRemark
	 */
	public String getAppFailRemark() {
		return appFailRemark;
	}

	/**
	 * @param appFailRemark the appFailRemark to set
	 */
	public void setAppFailRemark(String appFailRemark) {
		this.appFailRemark = appFailRemark;
	}

	/**
	 * @return the amtFailRemark
	 */
	public String getAmtFailRemark() {
		return amtFailRemark;
	}

	/**
	 * @param amtFailRemark the amtFailRemark to set
	 */
	public void setAmtFailRemark(String amtFailRemark) {
		this.amtFailRemark = amtFailRemark;
	}

	/**
	 * @return the accntBankStringList
	 */
	public String getAccntBankStringList() {
		return accntBankStringList;
	}

	/**
	 * @param accntBankStringList the accntBankStringList to set
	 */
	public void setAccntBankStringList(String accntBankStringList) {
		this.accntBankStringList = accntBankStringList;
	}

	/**
	 * @return the accntBankList
	 */
	public List<String> getAccntBankList() {
		return accntBankList;
	}

	/**
	 * @param accntBankList the accntBankList to set
	 */
	public void setAccntBankList(List<String> accntBankList) {
		this.accntBankList = accntBankList;
	}

	/**
	 * @return the accntBankStringListDesc
	 */
	public String getAccntBankStringListDesc() {
		return accntBankStringListDesc;
	}

	/**
	 * @param accntBankStringListDesc the accntBankStringListDesc to set
	 */
	public void setAccntBankStringListDesc(String accntBankStringListDesc) {
		this.accntBankStringListDesc = accntBankStringListDesc;
	}
	
}