package com.jiuyv.yl.console.outmer.dao.inter ;


import java.util.Map;

import com.jiuyv.yl.console.common.dao.inter.IBaseDao;
import com.jiuyv.yl.console.outmer.entity.MhtAttachInfoVo;

// Generated by AutoCode4J
/**
 * Interface: 商户附件信息表 TBL_MHT_ATTACH_INFO : TBL_MHT_ATTACH_INFO
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface IMhtAttachInfoDao extends IBaseDao<MhtAttachInfoVo> {

	/**
	 * Find MhtAttachInfoVo by Primary Key
	 * 
	 * @param athNo : 附件编号	 
	 * @return MhtAttachInfoVo : 商户附件信息表 TBL_MHT_ATTACH_INFO
	 */
	MhtAttachInfoVo findByPK(Long athNo ) ;

	/**
	 * 根据mid查询商户附件Map，
	 * key为athType
	 * @param mid
	 * @return
	 */
	Map<String, MhtAttachInfoVo> findAthTypeMapByMid(String mid);

	/**
	 * 生成athNo编号
	 * @param athInfoVo
	 */
	MhtAttachInfoVo insertWithKey(MhtAttachInfoVo athInfoVo);

}