package com.jiuyv.yl.console.outmer.dao.inter ;


import com.jiuyv.yl.console.common.dao.inter.IBaseDao;
import com.jiuyv.yl.console.outmer.entity.MhtAttachInfoHisVo;

// Generated by AutoCode4J
/**
 * Interface: 商户附件信息历史表 TBL_MHT_ATTACH_INFO_HIS : TBL_MHT_ATTACH_INFO_HIS
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface IMhtAttachInfoHisDao extends IBaseDao<MhtAttachInfoHisVo> {

	/**
	 * Find MhtAttachInfoHisVo by Primary Key
	 * 
	 * @param athNo : 附件编号
	 * @param oprNo : 日志流水号	 
	 * @return MhtAttachInfoHisVo : 商户附件信息历史表 TBL_MHT_ATTACH_INFO_HIS
	 */
	MhtAttachInfoHisVo findByPK(Long athNo , Long oprNo ) ;

}