package com.jiuyv.yl.console.outmer.dao.inter ;


import java.util.Map;

import com.jiuyv.yl.console.common.dao.inter.IBaseDao;
import com.jiuyv.yl.console.outmer.entity.MhtAttachInfoAddVo;

// Generated by AutoCode4J
/**
 * Interface: 商户进件附件信息表 TBL_MHT_ATTACH_INFO_ADD : TBL_MHT_ATTACH_INFO_ADD
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface IMhtAttachInfoAddDao extends IBaseDao<MhtAttachInfoAddVo> {

	/**
	 * Find MhtAttachInfoAddVo by Primary Key
	 * 
	 * @param athNo : 附件编号	 
	 * @return MhtAttachInfoAddVo : 商户进件附件信息表 TBL_MHT_ATTACH_INFO_ADD
	 */
	MhtAttachInfoAddVo findByPK(Long athNo ) ;

	/**
	 * 根据orgCode查询进件附件Map
	 * @param orgCode
	 * @return
	 */
	Map<String, MhtAttachInfoAddVo> findAthTypeMapByOrgCode(String orgCode);

}