package com.jiuyv.yl.console.trans.entity;

//Generated by AutoCode4J
/**
* EntityBean: 优惠券交易流水表 : TBL_COUPON_TRANS
* This is a value object(VO). 
* Description: 
* 
* @author AutoCode4J
* @version 1.0
*/
public class CouponTransVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** localSeq : 本模块流水号. LOCAL_SEQ: NUMBER(12) */
	private Long localSeq ;
	
	/** txnLock : 交易锁定标志. TXN_LOCK: NUMBER(1) */
	private Long txnLock ;
	
	/** txnLockTime : 交易锁定时间. TXN_LOCK_TIME: CHAR(14) */
	private String txnLockTime ;
	
	/** transTime : 中心交易时间. TRANS_TIME: CHAR(14) */
	private String transTime ;
	
	/** transSeq : 中心交易流水(域37). TRANS_SEQ: NUMBER(12) */
	private Long transSeq ;
	
	/** pospStmt : 本系统清算日. POSP_STMT: CHAR(8) */
	private String pospStmt ;
	
	/** txnType : 交易类型. TXN_TYPE: VARCHAR2(5) */
	private String txnType ;
	
	/** destOrgCode : 对方机构代码. DEST_ORG_CODE: VARCHAR2(15 ) */
	private String destOrgCode ;
	
	/** destTransTime : 对方交易时间. DEST_TRANS_TIME: VARCHAR2(8) */
	private String destTransTime ;
	
	/** destTransSeq : 对方交易流水号. DEST_TRANS_SEQ: VARCHAR2(20) */
	private String destTransSeq ;
	
	/** destRepCode : 对方应答码. DEST_REP_CODE: VARCHAR2(2) */
	private String destRepCode ;
	
	/** msgType : 消息类型(请求). MSG_TYPE: CHAR(4) */
	private String msgType ;
	
	/** pan : 主帐号(2域). PAN: VARCHAR2(19) */
	private String pan ;
	
	/** cardIndex : 卡索引号. CARD_INDEX: VARCHAR2(12) */
	private String cardIndex ;
	
	/** procCode : 交易处理码(3域). PROC_CODE: CHAR(6) */
	private String procCode ;
	
	/** transAmtBefore : 交易前金额(4域). TRANS_AMT_BEFORE: NUMBER(12) */
	private Long transAmtBefore ;
	
	/** couponFee : 优惠金额. COUPON_FEE: NUMBER(10) */
	private Long couponFee ;
	
	/** transAmtAfter : 实扣金额(4域). TRANS_AMT_AFTER: NUMBER(12) */
	private Long transAmtAfter ;
	
	/** tidSeq : 终端交易流水号(11域). TID_SEQ: NUMBER(6) */
	private Long tidSeq ;
	
	/** askReferenceNum : 请求参考号(37). ASK_REFERENCE_NUM: NUMBER(12) */
	private Long askReferenceNum ;
	
	/** respCode : 应答码(39). RESP_CODE: VARCHAR2(2) */
	private String respCode ;
	
	/** tid : 终端标识号(41). TID: VARCHAR2(8) */
	private String tid ;
	
	/** mid : 商户号(42). MID: VARCHAR2(15) */
	private String mid ;
	
	/** batchNo : 批次号(60.2). BATCH_NO: VARCHAR2(6) */
	private String batchNo ;
	
	/** markerFee : 营销费. MARKER_FEE: NUMBER(10) */
	private Long markerFee ;
	
	/** coin : 乐币. COIN: NUMBER(10) */
	private Long coin ;
	
	/** bean : 乐豆. BEAN: NUMBER(10) */
	private Long bean ;
	
	/** giftAmt : 赠送金额. GIFT_AMT: NUMBER(10) */
	private Long giftAmt ;
	
	/** giftScore : 赠送积分. GIFT_SCORE: NUMBER(10) */
	private Long giftScore ;
	
	/** platformCommission : 平台佣金. PLATFORM_COMMISSION: NUMBER(10) */
	private Long platformCommission ;
	
	/** serviceType : 服务性质. SERVICE_TYPE: VARCHAR2(1) */
	private String serviceType ;
	
	/** oriLocalSeq : 原本模块流水号. ORI_LOCAL_SEQ: NUMBER(12) */
	private Long oriLocalSeq ;
	
	/** oriTransTime : 原中心交易时间. ORI_TRANS_TIME: CHAR(14) */
	private String oriTransTime ;
	
	/** oriBatchNo : 原始交易批次号(61.1). ORI_BATCH_NO: VARCHAR2(6) */
	private String oriBatchNo ;
	
	/** oriTidSeq : 原始交易POS流水(61.2). ORI_TID_SEQ: NUMBER(6) */
	private Long oriTidSeq ;
	
	/** rollbackFlag : 冲正标志. ROLLBACK_FLAG: VARCHAR2(1) */
	private String rollbackFlag ;
	
	/** cancelFlag : 撤销标志. CANCEL_FLAG: VARCHAR2(1) */
	private String cancelFlag ;
	
	/** settleFlag : 清算标志. SETTLE_FLAG: VARCHAR2(1) */
	private String settleFlag ;
	
	/** rsv1 : RSV1. RSV1: VARCHAR2(100) */
	private String rsv1 ;
	
	/** rsv2 : RSV2. RSV2: VARCHAR2(100) */
	private String rsv2 ;
	
	/** rsv3 : RSV3. RSV3: VARCHAR2(100) */
	private String rsv3 ;
	
	/** 备注（广告）	ANS200. */
	private String comments;
	
	/** checkUpFlag : 对帐标志. CHECK_UP_FLAG: VARCHAR2(2) */
	private String checkUpFlag ;
	
	
	/** destTransTime : 原交易对方交易时间. DEST_TRANS_TIME: VARCHAR2(8) */
	private String oriDestTransTime ;
	
	/** destTransSeq : 原交易对方交易流水号. DEST_TRANS_SEQ: VARCHAR2(20) */
	private String oriDestTransSeq ;
	
	/** routeFlag : 是否是透传. 0未透传  1透传*/
	private String routeFlag ;
	
	/** oriTransSeq : 原交易中心流水号*/
	private Long oriTransSeq;
	
	public String getRouteFlag() {
		return routeFlag;
	}

	public void setRouteFlag(String routeFlag) {
		this.routeFlag = routeFlag;
	}

	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CouponTransVo() {
		// Default Construtor
	}
	
	public CouponTransVo(Long localSeq) {
		this.localSeq = localSeq;
	}
		
	// -- Setter And Getter
	/**
	 * Set localSeq : 本模块流水号. LOCAL_SEQ: NUMBER(12) 
	 */
	public void setLocalSeq(Long localSeq){
		this.localSeq = localSeq;	
	}
	
	/**
	 * Get localSeq : 本模块流水号. LOCAL_SEQ: NUMBER(12) 
	 */
	public Long getLocalSeq(){
		return this.localSeq;	
	}
	
	/**
	 * Set txnLock : 交易锁定标志. TXN_LOCK: NUMBER(1) 
	 */
	public void setTxnLock(Long txnLock){
		this.txnLock = txnLock;	
	}
	
	/**
	 * Get txnLock : 交易锁定标志. TXN_LOCK: NUMBER(1) 
	 */
	public Long getTxnLock(){
		return this.txnLock;	
	}
	
	/**
	 * Set txnLockTime : 交易锁定时间. TXN_LOCK_TIME: CHAR(14) 
	 */
	public void setTxnLockTime(String txnLockTime){
		this.txnLockTime = txnLockTime;	
	}
	
	/**
	 * Get txnLockTime : 交易锁定时间. TXN_LOCK_TIME: CHAR(14) 
	 */
	public String getTxnLockTime(){
		return this.txnLockTime;	
	}
	
	/**
	 * Set transTime : 中心交易时间. TRANS_TIME: CHAR(14) 
	 */
	public void setTransTime(String transTime){
		this.transTime = transTime;	
	}
	
	/**
	 * Get transTime : 中心交易时间. TRANS_TIME: CHAR(14) 
	 */
	public String getTransTime(){
		return this.transTime;	
	}
	
	/**
	 * Set transSeq : 中心交易流水(域37). TRANS_SEQ: NUMBER(12) 
	 */
	public void setTransSeq(Long transSeq){
		this.transSeq = transSeq;	
	}
	
	/**
	 * Get transSeq : 中心交易流水(域37). TRANS_SEQ: NUMBER(12) 
	 */
	public Long getTransSeq(){
		return this.transSeq;	
	}
	
	/**
	 * Set pospStmt : 本系统清算日. POSP_STMT: CHAR(8) 
	 */
	public void setPospStmt(String pospStmt){
		this.pospStmt = pospStmt;	
	}
	
	/**
	 * Get pospStmt : 本系统清算日. POSP_STMT: CHAR(8) 
	 */
	public String getPospStmt(){
		return this.pospStmt;	
	}
	
	/**
	 * Set txnType : 交易类型. TXN_TYPE: VARCHAR2(5) 
	 */
	public void setTxnType(String txnType){
		this.txnType = txnType;	
	}
	
	/**
	 * Get txnType : 交易类型. TXN_TYPE: VARCHAR2(5) 
	 */
	public String getTxnType(){
		return this.txnType;	
	}
	
	/**
	 * Set destOrgCode : 对方机构代码. DEST_ORG_CODE: VARCHAR2(15 ) 
	 */
	public void setDestOrgCode(String destOrgCode){
		this.destOrgCode = destOrgCode;	
	}
	
	/**
	 * Get destOrgCode : 对方机构代码. DEST_ORG_CODE: VARCHAR2(15 ) 
	 */
	public String getDestOrgCode(){
		return this.destOrgCode;	
	}
	
	/**
	 * Set destTransTime : 对方交易时间. DEST_TRANS_TIME: VARCHAR2(8) 
	 */
	public void setDestTransTime(String destTransTime){
		this.destTransTime = destTransTime;	
	}
	
	/**
	 * Get destTransTime : 对方交易时间. DEST_TRANS_TIME: VARCHAR2(8) 
	 */
	public String getDestTransTime(){
		return this.destTransTime;	
	}
	
	/**
	 * Set destTransSeq : 对方交易流水号. DEST_TRANS_SEQ: VARCHAR2(20) 
	 */
	public void setDestTransSeq(String destTransSeq){
		this.destTransSeq = destTransSeq;	
	}
	
	/**
	 * Get destTransSeq : 对方交易流水号. DEST_TRANS_SEQ: VARCHAR2(20) 
	 */
	public String getDestTransSeq(){
		return this.destTransSeq;	
	}
	
	/**
	 * Set destRepCode : 对方应答码. DEST_REP_CODE: VARCHAR2(2) 
	 */
	public void setDestRepCode(String destRepCode){
		this.destRepCode = destRepCode;	
	}
	
	/**
	 * Get destRepCode : 对方应答码. DEST_REP_CODE: VARCHAR2(2) 
	 */
	public String getDestRepCode(){
		return this.destRepCode;	
	}
	
	/**
	 * Set msgType : 消息类型(请求). MSG_TYPE: CHAR(4) 
	 */
	public void setMsgType(String msgType){
		this.msgType = msgType;	
	}
	
	/**
	 * Get msgType : 消息类型(请求). MSG_TYPE: CHAR(4) 
	 */
	public String getMsgType(){
		return this.msgType;	
	}
	
	/**
	 * Set pan : 主帐号(2域). PAN: VARCHAR2(19) 
	 */
	public void setPan(String pan){
		this.pan = pan;	
	}
	
	/**
	 * Get pan : 主帐号(2域). PAN: VARCHAR2(19) 
	 */
	public String getPan(){
		return this.pan;	
	}
	
	/**
	 * Set cardIndex : 卡索引号. CARD_INDEX: VARCHAR2(12) 
	 */
	public void setCardIndex(String cardIndex){
		this.cardIndex = cardIndex;	
	}
	
	/**
	 * Get cardIndex : 卡索引号. CARD_INDEX: VARCHAR2(12) 
	 */
	public String getCardIndex(){
		return this.cardIndex;	
	}
	
	/**
	 * Set procCode : 交易处理码(3域). PROC_CODE: CHAR(6) 
	 */
	public void setProcCode(String procCode){
		this.procCode = procCode;	
	}
	
	/**
	 * Get procCode : 交易处理码(3域). PROC_CODE: CHAR(6) 
	 */
	public String getProcCode(){
		return this.procCode;	
	}
	
	/**
	 * Set transAmtBefore : 交易前金额(4域). TRANS_AMT_BEFORE: NUMBER(12) 
	 */
	public void setTransAmtBefore(Long transAmtBefore){
		this.transAmtBefore = transAmtBefore;	
	}
	
	/**
	 * Get transAmtBefore : 交易前金额(4域). TRANS_AMT_BEFORE: NUMBER(12) 
	 */
	public Long getTransAmtBefore(){
		return this.transAmtBefore;	
	}
	
	/**
	 * Set couponFee : 优惠金额. COUPON_FEE: NUMBER(10) 
	 */
	public void setCouponFee(Long couponFee){
		this.couponFee = couponFee;	
	}
	
	/**
	 * Get couponFee : 优惠金额. COUPON_FEE: NUMBER(10) 
	 */
	public Long getCouponFee(){
		return this.couponFee;	
	}
	
	/**
	 * Set transAmtAfter : 优惠后交易金额(4域). TRANS_AMT_AFTER: NUMBER(12) 
	 */
	public void setTransAmtAfter(Long transAmtAfter){
		this.transAmtAfter = transAmtAfter;	
	}
	
	/**
	 * Get transAmtAfter : 优惠后交易金额(4域). TRANS_AMT_AFTER: NUMBER(12) 
	 */
	public Long getTransAmtAfter(){
		return this.transAmtAfter;	
	}
	
	/**
	 * Set tidSeq : 终端交易流水号(11域). TID_SEQ: NUMBER(6) 
	 */
	public void setTidSeq(Long tidSeq){
		this.tidSeq = tidSeq;	
	}
	
	/**
	 * Get tidSeq : 终端交易流水号(11域). TID_SEQ: NUMBER(6) 
	 */
	public Long getTidSeq(){
		return this.tidSeq;	
	}
	
	/**
	 * Set askReferenceNum : 请求参考号(37). ASK_REFERENCE_NUM: NUMBER(12) 
	 */
	public void setAskReferenceNum(Long askReferenceNum){
		this.askReferenceNum = askReferenceNum;	
	}
	
	/**
	 * Get askReferenceNum : 请求参考号(37). ASK_REFERENCE_NUM: NUMBER(12) 
	 */
	public Long getAskReferenceNum(){
		return this.askReferenceNum;	
	}
	
	/**
	 * Set respCode : 应答码(39). RESP_CODE: VARCHAR2(2) 
	 */
	public void setRespCode(String respCode){
		this.respCode = respCode;	
	}
	
	/**
	 * Get respCode : 应答码(39). RESP_CODE: VARCHAR2(2) 
	 */
	public String getRespCode(){
		return this.respCode;	
	}
	
	/**
	 * Set tid : 终端标识号(41). TID: VARCHAR2(8) 
	 */
	public void setTid(String tid){
		this.tid = tid;	
	}
	
	/**
	 * Get tid : 终端标识号(41). TID: VARCHAR2(8) 
	 */
	public String getTid(){
		return this.tid;	
	}
	
	/**
	 * Set mid : 商户号(42). MID: VARCHAR2(15) 
	 */
	public void setMid(String mid){
		this.mid = mid;	
	}
	
	/**
	 * Get mid : 商户号(42). MID: VARCHAR2(15) 
	 */
	public String getMid(){
		return this.mid;	
	}
	
	/**
	 * Set batchNo : 批次号(60.2). BATCH_NO: VARCHAR2(6) 
	 */
	public void setBatchNo(String batchNo){
		this.batchNo = batchNo;	
	}
	
	/**
	 * Get batchNo : 批次号(60.2). BATCH_NO: VARCHAR2(6) 
	 */
	public String getBatchNo(){
		return this.batchNo;	
	}
	
	/**
	 * Set markerFee : 营销费. MARKER_FEE: NUMBER(10) 
	 */
	public void setMarkerFee(Long markerFee){
		this.markerFee = markerFee;	
	}
	
	/**
	 * Get markerFee : 营销费. MARKER_FEE: NUMBER(10) 
	 */
	public Long getMarkerFee(){
		return this.markerFee;	
	}
	
	/**
	 * Set coin : 乐币. COIN: NUMBER(10) 
	 */
	public void setCoin(Long coin){
		this.coin = coin;	
	}
	
	/**
	 * Get coin : 乐币. COIN: NUMBER(10) 
	 */
	public Long getCoin(){
		return this.coin;	
	}
	
	/**
	 * Set bean : 乐豆. BEAN: NUMBER(10) 
	 */
	public void setBean(Long bean){
		this.bean = bean;	
	}
	
	/**
	 * Get bean : 乐豆. BEAN: NUMBER(10) 
	 */
	public Long getBean(){
		return this.bean;	
	}
	
	/**
	 * Set giftAmt : 赠送金额. GIFT_AMT: NUMBER(10) 
	 */
	public void setGiftAmt(Long giftAmt){
		this.giftAmt = giftAmt;	
	}
	
	/**
	 * Get giftAmt : 赠送金额. GIFT_AMT: NUMBER(10) 
	 */
	public Long getGiftAmt(){
		return this.giftAmt;	
	}
	
	/**
	 * Set giftScore : 赠送积分. GIFT_SCORE: NUMBER(10) 
	 */
	public void setGiftScore(Long giftScore){
		this.giftScore = giftScore;	
	}
	
	/**
	 * Get giftScore : 赠送积分. GIFT_SCORE: NUMBER(10) 
	 */
	public Long getGiftScore(){
		return this.giftScore;	
	}
	
	/**
	 * Set platformCommission : 平台佣金. PLATFORM_COMMISSION: NUMBER(10) 
	 */
	public void setPlatformCommission(Long platformCommission){
		this.platformCommission = platformCommission;	
	}
	
	/**
	 * Get platformCommission : 平台佣金. PLATFORM_COMMISSION: NUMBER(10) 
	 */
	public Long getPlatformCommission(){
		return this.platformCommission;	
	}
	
	/**
	 * Set serviceType : 服务性质. SERVICE_TYPE: VARCHAR2(1) 
	 */
	public void setServiceType(String serviceType){
		this.serviceType = serviceType;	
	}
	
	/**
	 * Get serviceType : 服务性质. SERVICE_TYPE: VARCHAR2(1) 
	 */
	public String getServiceType(){
		return this.serviceType;	
	}
	
	/**
	 * Set oriLocalSeq : 原本模块流水号. ORI_LOCAL_SEQ: NUMBER(12) 
	 */
	public void setOriLocalSeq(Long oriLocalSeq){
		this.oriLocalSeq = oriLocalSeq;	
	}
	
	/**
	 * Get oriLocalSeq : 原本模块流水号. ORI_LOCAL_SEQ: NUMBER(12) 
	 */
	public Long getOriLocalSeq(){
		return this.oriLocalSeq;	
	}
	
	/**
	 * Set oriTransTime : 原中心交易时间. ORI_TRANS_TIME: CHAR(14) 
	 */
	public void setOriTransTime(String oriTransTime){
		this.oriTransTime = oriTransTime;	
	}
	
	/**
	 * Get oriTransTime : 原中心交易时间. ORI_TRANS_TIME: CHAR(14) 
	 */
	public String getOriTransTime(){
		return this.oriTransTime;	
	}
	
	/**
	 * Set oriBatchNo : 原始交易批次号(61.1). ORI_BATCH_NO: VARCHAR2(6) 
	 */
	public void setOriBatchNo(String oriBatchNo){
		this.oriBatchNo = oriBatchNo;	
	}
	
	/**
	 * Get oriBatchNo : 原始交易批次号(61.1). ORI_BATCH_NO: VARCHAR2(6) 
	 */
	public String getOriBatchNo(){
		return this.oriBatchNo;	
	}
	
	/**
	 * Set oriTidSeq : 原始交易POS流水(61.2). ORI_TID_SEQ: NUMBER(6) 
	 */
	public void setOriTidSeq(Long oriTidSeq){
		this.oriTidSeq = oriTidSeq;	
	}
	
	/**
	 * Get oriTidSeq : 原始交易POS流水(61.2). ORI_TID_SEQ: NUMBER(6) 
	 */
	public Long getOriTidSeq(){
		return this.oriTidSeq;	
	}
	
	/**
	 * Set rollbackFlag : 冲正标志. ROLLBACK_FLAG: VARCHAR2(1) 
	 */
	public void setRollbackFlag(String rollbackFlag){
		this.rollbackFlag = rollbackFlag;	
	}
	
	/**
	 * Get rollbackFlag : 冲正标志. ROLLBACK_FLAG: VARCHAR2(1) 
	 */
	public String getRollbackFlag(){
		return this.rollbackFlag;	
	}
	
	/**
	 * Set cancelFlag : 撤销标志. CANCEL_FLAG: VARCHAR2(1) 
	 */
	public void setCancelFlag(String cancelFlag){
		this.cancelFlag = cancelFlag;	
	}
	
	/**
	 * Get cancelFlag : 撤销标志. CANCEL_FLAG: VARCHAR2(1) 
	 */
	public String getCancelFlag(){
		return this.cancelFlag;	
	}
	
	/**
	 * Set settleFlag : 清算标志. SETTLE_FLAG: VARCHAR2(1) 
	 */
	public void setSettleFlag(String settleFlag){
		this.settleFlag = settleFlag;	
	}
	
	/**
	 * Get settleFlag : 清算标志. SETTLE_FLAG: VARCHAR2(1) 
	 */
	public String getSettleFlag(){
		return this.settleFlag;	
	}
	
	/**
	 * Set rsv1 : RSV1. RSV1: VARCHAR2(100) 
	 */
	public void setRsv1(String rsv1){
		this.rsv1 = rsv1;	
	}
	
	/**
	 * Get rsv1 : RSV1. RSV1: VARCHAR2(100) 
	 */
	public String getRsv1(){
		return this.rsv1;	
	}
	
	/**
	 * Set rsv2 : RSV2. RSV2: VARCHAR2(100) 
	 */
	public void setRsv2(String rsv2){
		this.rsv2 = rsv2;	
	}
	
	/**
	 * Get rsv2 : RSV2. RSV2: VARCHAR2(100) 
	 */
	public String getRsv2(){
		return this.rsv2;	
	}
	
	/**
	 * Set rsv3 : RSV3. RSV3: VARCHAR2(100) 
	 */
	public void setRsv3(String rsv3){
		this.rsv3 = rsv3;	
	}
	
	/**
	 * Get rsv3 : RSV3. RSV3: VARCHAR2(100) 
	 */
	public String getRsv3(){
		return this.rsv3;	
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCheckUpFlag() {
		return checkUpFlag;
	}

	public void setCheckUpFlag(String checkUpFlag) {
		this.checkUpFlag = checkUpFlag;
	}

	public String getOriDestTransTime() {
		return oriDestTransTime;
	}

	public void setOriDestTransTime(String oriDestTransTime) {
		this.oriDestTransTime = oriDestTransTime;
	}

	public String getOriDestTransSeq() {
		return oriDestTransSeq;
	}

	public void setOriDestTransSeq(String oriDestTransSeq) {
		this.oriDestTransSeq = oriDestTransSeq;
	}

	public Long getOriTransSeq() {
		return oriTransSeq;
	}

	public void setOriTransSeq(Long oriTransSeq) {
		this.oriTransSeq = oriTransSeq;
	}
	
	
	
}