package com.jiuyv.yl.console.notice.dao.inter ;

import java.util.List;

import com.jiuyv.yl.console.notice.entity.ConsoleNoticeInfoVo;
import com.jiuyv.common.ibatis.vo.ExtData;
import com.jiuyv.common.ibatis.vo.Filter;
import com.jiuyv.common.ibatis.vo.Page;

// Generated by AutoCode4J
/**
 * Interface: [New]公告信息表 : TBL_NOTICE_INFO
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface ConsoleNoticeInfoDao{
	
	ExtData<ConsoleNoticeInfoVo> filterQueryPage(List<Filter> filters,Page page)throws Exception;
	
	ExtData<ConsoleNoticeInfoVo> filterAuditQueryPage(List<Filter> filters,Page pageInfo) throws Exception;
			
	/**
	 * Find ConsoleNoticeInfoVo by Primary Key. 
	 * 
	 * @param noticeSeq : 公告序号	 
	 * @return ConsoleNoticeInfoVo : [New]公告信息表
	 */
	ConsoleNoticeInfoVo findByKey(Long noticeSeq )throws Exception ;
	
	/**
	 * Update ConsoleNoticeInfoVo by Primary Key.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	ExtData<ConsoleNoticeInfoVo> updateByKey(ConsoleNoticeInfoVo vo,List<Filter> filters)throws Exception;
	

	/**
	 * Insert ConsoleNoticeInfoVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	ExtData<ConsoleNoticeInfoVo> insert(ConsoleNoticeInfoVo vo,List<Filter> filters)throws Exception ;

	
	Long findNoticeSeq();
	
}