package com.jiuyv.yl.console.notice.dao.inter ;

import java.util.List;

import com.jiuyv.yl.console.notice.entity.NoticeChannelRelVo;
import com.jiuyv.yl.console.notice.entity.NoticeInfoVo;
import com.jiuyv.common.ibatis.vo.ExtData;
import com.jiuyv.common.ibatis.vo.Filter;
import com.jiuyv.common.ibatis.vo.Page;

// Generated by AutoCode4J
/**
 * Interface: [New]公告信息表 : TBL_NOTICE_INFO
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface NoticeChannelRelDao{
	
	ExtData<NoticeChannelRelVo> filterQueryPage(List<Filter> filters,Page page)throws Exception;
	
	/**
	 * Find NoticeInfoVo by Primary Key. 
	 * 
	 * @param noticeSeq : 公告序号	 
	 * @return NoticeInfoVo : [New]公告信息表
	 */
	NoticeChannelRelVo findByKey(NoticeChannelRelVo vo)throws Exception ;
	
	/**
	 * Insert NoticeInfoVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	ExtData<NoticeChannelRelVo> insert(NoticeChannelRelVo vo)throws Exception ;

	void deleteByNoticeSeq(Long noticeSeq);
	
	List<String> findChannelByNoticeSeq(Long noticeSeq);

}