package com.jiuyv.yl.console.lottery.dao.inter;

import com.jiuyv.yl.console.lottery.entity.TblLotteryWelfare;
import com.jiuyv.yl.console.lottery.entity.TblLotteryWelfareExample;
import java.sql.SQLException;
import java.util.List;

public interface TblLotteryWelfareDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    int countByExample(TblLotteryWelfareExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    int deleteByExample(TblLotteryWelfareExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    void insert(TblLotteryWelfare record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    void insertSelective(TblLotteryWelfare record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    List selectByExample(TblLotteryWelfareExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    TblLotteryWelfare selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    int updateByExampleSelective(TblLotteryWelfare record, TblLotteryWelfareExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    int updateByExample(TblLotteryWelfare record, TblLotteryWelfareExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    int updateByPrimaryKeySelective(TblLotteryWelfare record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    int updateByPrimaryKey(TblLotteryWelfare record) throws SQLException;
}