package com.jiuyv.yl.console.lottery.dao.inter;

import com.jiuyv.common.ibatis.vo.ExtData;
import com.jiuyv.common.ibatis.vo.Filter;
import com.jiuyv.common.ibatis.vo.Page;
import com.jiuyv.yl.console.common.dao.inter.IBaseDao;
import com.jiuyv.yl.console.lottery.entity.TblLotteryMerchant;
import com.jiuyv.yl.console.lottery.entity.TblLotteryMerchantExample;
import com.jiuyv.yl.console.outmer.entity.MhtAttachInfoAddVo;

import java.sql.SQLException;
import java.util.List;

public interface TblLotteryMerchantDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    int countByExample(TblLotteryMerchantExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    int deleteByExample(TblLotteryMerchantExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    int deleteByPrimaryKey(String merid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    void insert(TblLotteryMerchant record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    void insertSelective(TblLotteryMerchant record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    List selectByExample(TblLotteryMerchantExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    TblLotteryMerchant selectByPrimaryKey(String merid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    int updateByExampleSelective(TblLotteryMerchant record, TblLotteryMerchantExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    int updateByExample(TblLotteryMerchant record, TblLotteryMerchantExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    int updateByPrimaryKeySelective(TblLotteryMerchant record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_merchant
     *
     * @ibatorgenerated Sat Oct 21 22:17:14 CST 2017
     */
    int updateByPrimaryKey(TblLotteryMerchant record) throws SQLException;

	String queryMerSeq()  throws Exception;

	List<TblLotteryMerchant> findOutQrcMerApply(List<Filter> filters,
			Page pageInfo) throws Exception;
	
	public void updateMerAmt(TblLotteryMerchant merchant) throws Exception;
}