package com.jiuyv.yl.console.lottery.dao.inter;

import com.jiuyv.yl.console.lottery.entity.TblLotteryOrder;
import com.jiuyv.yl.console.lottery.entity.TblLotteryOrderExample;
import java.sql.SQLException;
import java.util.List;

public interface TblLotteryOrderDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    int countByExample(TblLotteryOrderExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    int deleteByExample(TblLotteryOrderExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    void insert(TblLotteryOrder record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    void insertSelective(TblLotteryOrder record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    List selectByExample(TblLotteryOrderExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    TblLotteryOrder selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    int updateByExampleSelective(TblLotteryOrder record, TblLotteryOrderExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    int updateByExample(TblLotteryOrder record, TblLotteryOrderExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    int updateByPrimaryKeySelective(TblLotteryOrder record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    int updateByPrimaryKey(TblLotteryOrder record) throws SQLException;
    
    public List selectOrderGroupMerid() throws SQLException;
    
    public TblLotteryOrder selectOrderByMsgId(TblLotteryOrder order) throws SQLException;
    
    int updateCancleOrder(TblLotteryOrder record) throws SQLException;

}