package com.jiuyv.yl.console.lottery.dao.inter;

import com.jiuyv.yl.console.lottery.entity.TblWebchantMerchant;
import com.jiuyv.yl.console.lottery.entity.TblWebchantMerchantExample;

import java.sql.SQLException;
import java.util.List;

public interface TblWebchantMerchantDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	int countByExample(TblWebchantMerchantExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	int deleteByExample(TblWebchantMerchantExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	int deleteByPrimaryKey(String merid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	void insert(TblWebchantMerchant record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	void insertSelective(TblWebchantMerchant record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	List selectByExample(TblWebchantMerchantExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	TblWebchantMerchant selectByPrimaryKey(String merid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	int updateByExampleSelective(TblWebchantMerchant record,
			TblWebchantMerchantExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	int updateByExample(TblWebchantMerchant record,
			TblWebchantMerchantExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	int updateByPrimaryKeySelective(TblWebchantMerchant record)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_webchant_merchant
	 * @ibatorgenerated  Sat Oct 28 23:54:59 CST 2017
	 */
	int updateByPrimaryKey(TblWebchantMerchant record) throws SQLException;
	
	public List<TblWebchantMerchant> selectByNickname(String nickname)
			throws SQLException;
}