package com.jiuyv.yl.console.outmer.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户进件附件信息表 TBL_MHT_ATTACH_INFO_ADD : TBL_MHT_ATTACH_INFO_ADD
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtAttachInfoAddVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** athNo : 附件编号. ATH_NO: NUMBER(10) */
	private Long athNo ;
	
	/** addOrgCode : 代理商内部号. ADD_ORG_CODE: VARCHAR2(15) */
	private String addOrgCode ;
	
	/** mid : 商户号. MID: VARCHAR2(15) */
	private String mid ;
	
	/** athType : 附件类别. ATH_TYPE: VARCHAR2(20) */
	private String athType ;
	
	/** inMedSeq : 进件附件序号. IN_MED_SEQ: VARCHAR2(200) */
	private String inMedSeq ;
	
	/** updMedSeq : 变更附件序号. UPD_MED_SEQ: VARCHAR2(200) */
	private String updMedSeq ;
	
	/** oprAcc : 上传用户. OPR_ACC: VARCHAR2(30) */
	private String oprAcc ;
	
	/** oprTime : 上传时间. OPR_TIME: VARCHAR2(14) */
	private String oprTime ;
	
	/** lastUptAcc : 最后修改人. LAST_UPT_ACC: VARCHAR2(30) */
	private String lastUptAcc ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: VARCHAR2(14) */
	private String lastUptTime ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MhtAttachInfoAddVo() {
		// Default Construtor
	}
	
	public MhtAttachInfoAddVo(Long athNo) {
		this.athNo = athNo;
	}
		
	// -- Setter And Getter
	/**
	 * Set athNo : 附件编号. ATH_NO: NUMBER(10) 
	 */
	public void setAthNo(Long athNo){
		this.athNo = athNo;	
	}
	
	/**
	 * Get athNo : 附件编号. ATH_NO: NUMBER(10) 
	 */
	public Long getAthNo(){
		return this.athNo;	
	}
	
	/**
	 * Set addOrgCode : 代理商内部号. ADD_ORG_CODE: VARCHAR2(15) 
	 */
	public void setAddOrgCode(String addOrgCode){
		this.addOrgCode = addOrgCode;	
	}
	
	/**
	 * Get addOrgCode : 代理商内部号. ADD_ORG_CODE: VARCHAR2(15) 
	 */
	public String getAddOrgCode(){
		return this.addOrgCode;	
	}
	
	/**
	 * Set mid : 商户号. MID: VARCHAR2(15) 
	 */
	public void setMid(String mid){
		this.mid = mid;	
	}
	
	/**
	 * Get mid : 商户号. MID: VARCHAR2(15) 
	 */
	public String getMid(){
		return this.mid;	
	}
	
	/**
	 * Set athType : 附件类别. ATH_TYPE: VARCHAR2(20) 
	 */
	public void setAthType(String athType){
		this.athType = athType;	
	}
	
	/**
	 * Get athType : 附件类别. ATH_TYPE: VARCHAR2(20) 
	 */
	public String getAthType(){
		return this.athType;	
	}
	
	/**
	 * Set inMedSeq : 进件附件序号. IN_MED_SEQ: VARCHAR2(200) 
	 */
	public void setInMedSeq(String inMedSeq){
		this.inMedSeq = inMedSeq;	
	}
	
	/**
	 * Get inMedSeq : 进件附件序号. IN_MED_SEQ: VARCHAR2(200) 
	 */
	public String getInMedSeq(){
		return this.inMedSeq;	
	}
	
	/**
	 * Set updMedSeq : 变更附件序号. UPD_MED_SEQ: VARCHAR2(200) 
	 */
	public void setUpdMedSeq(String updMedSeq){
		this.updMedSeq = updMedSeq;	
	}
	
	/**
	 * Get updMedSeq : 变更附件序号. UPD_MED_SEQ: VARCHAR2(200) 
	 */
	public String getUpdMedSeq(){
		return this.updMedSeq;	
	}
	
	/**
	 * Set oprAcc : 上传用户. OPR_ACC: VARCHAR2(30) 
	 */
	public void setOprAcc(String oprAcc){
		this.oprAcc = oprAcc;	
	}
	
	/**
	 * Get oprAcc : 上传用户. OPR_ACC: VARCHAR2(30) 
	 */
	public String getOprAcc(){
		return this.oprAcc;	
	}
	
	/**
	 * Set oprTime : 上传时间. OPR_TIME: VARCHAR2(14) 
	 */
	public void setOprTime(String oprTime){
		this.oprTime = oprTime;	
	}
	
	/**
	 * Get oprTime : 上传时间. OPR_TIME: VARCHAR2(14) 
	 */
	public String getOprTime(){
		return this.oprTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后修改人. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后修改人. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: VARCHAR2(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: VARCHAR2(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
}