package com.jiuyv.yl.console.outmer.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户附件信息历史表 TBL_MHT_ATTACH_INFO_HIS : TBL_MHT_ATTACH_INFO_HIS
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtAttachInfoHisVo extends MhtAttachInfoAddVo {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	
	/** oprNo : 日志流水号. OPR_NO: NUMBER(10) */
	private Long oprNo ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MhtAttachInfoHisVo() {
		// Default Construtor
	}
	
	public MhtAttachInfoHisVo(Long athNo, Long oprNo) {
		super(athNo);
		this.oprNo = oprNo;
	}
	
	public MhtAttachInfoHisVo( MhtAttachInfoAddVo addVo ){
		if ( addVo != null ) {
			setAthNo(addVo.getAthNo());
			setAddOrgCode(addVo.getAddOrgCode());
			setMid(addVo.getMid());
			setAthType(addVo.getAthType());
			setInMedSeq(addVo.getInMedSeq());
			setUpdMedSeq(addVo.getUpdMedSeq());
			setOprAcc(addVo.getOprAcc());
			setOprTime(addVo.getOprTime());
			setLastUptAcc(addVo.getLastUptAcc());
			setLastUptTime(addVo.getLastUptTime());
		}
	}
		
	// -- Setter And Getter
	/**
	 * Set oprNo : 日志流水号. OPR_NO: NUMBER(10) 
	 */
	public void setOprNo(Long oprNo){
		this.oprNo = oprNo;	
	}
	
	/**
	 * Get oprNo : 日志流水号. OPR_NO: NUMBER(10) 
	 */
	public Long getOprNo(){
		return this.oprNo;	
	}
	
}