package com.jiuyv.yl.console.outmer.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户附件信息表 TBL_MHT_ATTACH_INFO : TBL_MHT_ATTACH_INFO
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtAttachInfoVo extends MhtAttachInfoAddVo {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	
	public MhtAttachInfoVo(){
		
	}
	
	public MhtAttachInfoVo( MhtAttachInfoAddVo addVo ){
		if ( addVo != null ) {
			setAthNo(addVo.getAthNo());
			setAddOrgCode(addVo.getAddOrgCode());
			setMid(addVo.getMid());
			setAthType(addVo.getAthType());
			setInMedSeq(addVo.getInMedSeq());
			setUpdMedSeq(addVo.getUpdMedSeq());
			setOprAcc(addVo.getOprAcc());
			setOprTime(addVo.getOprTime());
			setLastUptAcc(addVo.getLastUptAcc());
			setLastUptTime(addVo.getLastUptTime());
		}
	}
	
}