package com.jiuyv.yl.console.lottery.dao.impl;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.jiuyv.yl.console.lottery.dao.inter.TblLotteryWelfareDAO;
import com.jiuyv.yl.console.lottery.entity.TblLotteryWelfare;
import com.jiuyv.yl.console.lottery.entity.TblLotteryWelfareExample;

public class TblLotteryWelfareDAOImpl implements TblLotteryWelfareDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public TblLotteryWelfareDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public int countByExample(TblLotteryWelfareExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("tbl_lottery_welfare.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public int deleteByExample(TblLotteryWelfareExample example) throws SQLException {
        int rows = sqlMapClient.delete("tbl_lottery_welfare.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        TblLotteryWelfare key = new TblLotteryWelfare();
        key.setId(id);
        int rows = sqlMapClient.delete("tbl_lottery_welfare.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public void insert(TblLotteryWelfare record) throws SQLException {
        sqlMapClient.insert("tbl_lottery_welfare.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public void insertSelective(TblLotteryWelfare record) throws SQLException {
        sqlMapClient.insert("tbl_lottery_welfare.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public List selectByExample(TblLotteryWelfareExample example) throws SQLException {
        List list = sqlMapClient.queryForList("tbl_lottery_welfare.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public TblLotteryWelfare selectByPrimaryKey(Integer id) throws SQLException {
        TblLotteryWelfare key = new TblLotteryWelfare();
        key.setId(id);
        TblLotteryWelfare record = (TblLotteryWelfare) sqlMapClient.queryForObject("tbl_lottery_welfare.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public int updateByExampleSelective(TblLotteryWelfare record, TblLotteryWelfareExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_lottery_welfare.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public int updateByExample(TblLotteryWelfare record, TblLotteryWelfareExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_lottery_welfare.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public int updateByPrimaryKeySelective(TblLotteryWelfare record) throws SQLException {
        int rows = sqlMapClient.update("tbl_lottery_welfare.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public int updateByPrimaryKey(TblLotteryWelfare record) throws SQLException {
        int rows = sqlMapClient.update("tbl_lottery_welfare.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_lottery_welfare
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    private static class UpdateByExampleParms extends TblLotteryWelfareExample {
        private Object record;

        public UpdateByExampleParms(Object record, TblLotteryWelfareExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}