package com.jiuyv.yl.console.lottery.dao.impl;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.jiuyv.yl.console.lottery.dao.inter.TblLotteryOrderDAO;
import com.jiuyv.yl.console.lottery.entity.TblLotteryOrder;
import com.jiuyv.yl.console.lottery.entity.TblLotteryOrderExample;

public class TblLotteryOrderDAOImpl implements TblLotteryOrderDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public TblLotteryOrderDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public int countByExample(TblLotteryOrderExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("tbl_lottery_order.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public int deleteByExample(TblLotteryOrderExample example) throws SQLException {
        int rows = sqlMapClient.delete("tbl_lottery_order.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        TblLotteryOrder key = new TblLotteryOrder();
        key.setId(id);
        int rows = sqlMapClient.delete("tbl_lottery_order.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void insert(TblLotteryOrder record) throws SQLException {
        sqlMapClient.insert("tbl_lottery_order.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void insertSelective(TblLotteryOrder record) throws SQLException {
        sqlMapClient.insert("tbl_lottery_order.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public List selectByExample(TblLotteryOrderExample example) throws SQLException {
        List list = sqlMapClient.queryForList("tbl_lottery_order.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public TblLotteryOrder selectByPrimaryKey(Integer id) throws SQLException {
        TblLotteryOrder key = new TblLotteryOrder();
        key.setId(id);
        TblLotteryOrder record = (TblLotteryOrder) sqlMapClient.queryForObject("tbl_lottery_order.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public int updateByExampleSelective(TblLotteryOrder record, TblLotteryOrderExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_lottery_order.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public int updateByExample(TblLotteryOrder record, TblLotteryOrderExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_lottery_order.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public int updateByPrimaryKeySelective(TblLotteryOrder record) throws SQLException {
        int rows = sqlMapClient.update("tbl_lottery_order.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public int updateByPrimaryKey(TblLotteryOrder record) throws SQLException {
        int rows = sqlMapClient.update("tbl_lottery_order.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_lottery_order
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private static class UpdateByExampleParms extends TblLotteryOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, TblLotteryOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    public List selectOrderGroupMerid() throws SQLException {
        List list = sqlMapClient.queryForList("tbl_lottery_order.selectOrderGroupMerid");
        return list;
    }

	public TblLotteryOrder selectOrderByMsgId(TblLotteryOrder order)
			throws SQLException {
		return  (TblLotteryOrder)sqlMapClient.queryForObject("tbl_lottery_order.selectOrderByMsgId", order);
	}

	@Override
	public int updateCancleOrder(TblLotteryOrder record) throws SQLException {
		return sqlMapClient.update("tbl_lottery_order.cancleOrder", record);
	}
}