package com.jiuyv.yl.console.notice.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 综控台公告用户关联表 TBL_CONSOLE_NOTICE_USER_REL : TBL_CONSOLE_NOTICE_USER_REL
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class ConsoleNoticeUserRelVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** noticeSeq : 公告序号. NOTICE_SEQ: NUMBER(10) */
	private Long noticeSeq ;
	
	/** userId : 用户编号. USER_ID: NUMBER(10) */
	private Long userId ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public ConsoleNoticeUserRelVo() {
		// Default Construtor
	}
	
	public ConsoleNoticeUserRelVo(Long noticeSeq, Long userId) {
		this.noticeSeq = noticeSeq;
		this.userId = userId;
	}
		
	// -- Setter And Getter
	/**
	 * Set noticeSeq : 公告序号. NOTICE_SEQ: NUMBER(10) 
	 */
	public void setNoticeSeq(Long noticeSeq){
		this.noticeSeq = noticeSeq;	
	}
	
	/**
	 * Get noticeSeq : 公告序号. NOTICE_SEQ: NUMBER(10) 
	 */
	public Long getNoticeSeq(){
		return this.noticeSeq;	
	}
	
	/**
	 * Set userId : 用户编号. USER_ID: NUMBER(10) 
	 */
	public void setUserId(Long userId){
		this.userId = userId;	
	}
	
	/**
	 * Get userId : 用户编号. USER_ID: NUMBER(10) 
	 */
	public Long getUserId(){
		return this.userId;	
	}
	
}