package com.jiuyv.yl.console.notice.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: [New]公告服务商关联表: TBL_NOTICE_CHANNEL_REL
 * This is a value object(VO). 
 * Description: 公告与商户服务商的关联表，用于将公告投放到特定服务商
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class NoticeChannelRelVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** noticeSeq : 公告序号. NOTICE_SEQ: NUMBER(10) */
	private Long noticeSeq ;
	
	/** channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(15) */
	private String channelCode;

	public Long getNoticeSeq() {
		return noticeSeq;
	}

	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public NoticeChannelRelVo() {
		// Default Construtor
	}
	
	public NoticeChannelRelVo(Long noticeSeq,String channelCode) {
		this.noticeSeq = noticeSeq;
		this.channelCode = channelCode;
	}
		
	public void setNoticeSeq(Long noticeSeq) {
		this.noticeSeq = noticeSeq;
	}

	public String getChannelCode() {
		return channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}
	
}