package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 服务商保证金信息表 TBL_CHANNEL_BAIL : TBL_CHANNEL_BAIL
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class ChannelBailVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(15) */
	private String channelCode ;
	
	/** bailAmt : 保证金金额. BAIL_AMT: NUMBER(14) */
	private Long bailAmt ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public ChannelBailVo() {
		// Default Construtor
	}
	
	public ChannelBailVo(String channelCode) {
		this.channelCode = channelCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(15) 
	 */
	public void setChannelCode(String channelCode){
		this.channelCode = channelCode;	
	}
	
	/**
	 * Get channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(15) 
	 */
	public String getChannelCode(){
		return this.channelCode;	
	}
	
	/**
	 * Set bailAmt : 保证金金额. BAIL_AMT: NUMBER(14) 
	 */
	public void setBailAmt(Long bailAmt){
		this.bailAmt = bailAmt;	
	}
	
	/**
	 * Get bailAmt : 保证金金额. BAIL_AMT: NUMBER(14) 
	 */
	public Long getBailAmt(){
		return this.bailAmt;	
	}
	
}