package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: [MER]商户服务商信息表 : TBL_CORE_MER_CHANNEL
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CoreMerChannelVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** channelCode : 服务商编码. CHANNEL_CODE: VARCHAR2(15) */
	private String channelCode ;
	
	/** version : 版本号. VERSION: NUMBER(10) */
	private Long version ;
	
	/** channelName : 服务商名称. CHANNEL_NAME: VARCHAR2(100) */
	private String channelName ;
	
	/** oprTime : 创建时间. OPR_TIME: CHAR(14) */
	private String opTime ;
	
	/** oprAcc : 创建人账号. OPR_ACC: VARCHAR2(16) */
	private String opAcc ;
	
	/** status : 状态. STATUS: VARCHAR2(2) */
	private String status ;
	
	/** remark : 备注. REMARK: VARCHAR2(200) */
	private String remark ;
	
	/** luTime : 最后更新时间. LU_TIME: CHAR(14) */
	private String luTime ;
	
	/** luOrg : 最后更新机构. LU_ORG: VARCHAR2(30) */
	private String luOrg ;
	
	/** fatherId : 上级服务商号. FATHER_ID: VARCHAR2(15) */
	private String fatherId ;
	
	/** phone : 联系人电话. PHONE: VARCHAR2(30) */
	private String phone ;
	
	/** person : 联系人姓名. PERSON: VARCHAR2(30) */
	private String person ;
	
	//邀请码
	private String inviteCode;
	
	//邀请码二维码
	private byte[] inviteCodePic;
	
	// -- extend
	/** statusDesc : 商户服务商状态 */
	private String statusDesc;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CoreMerChannelVo() {
		// Default Construtor
	}
	
	public CoreMerChannelVo(String channelCode) {
		this.channelCode = channelCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set channelCode : 服务商编码. CHANNEL_CODE: VARCHAR2(15) 
	 */
	
	public void setChannelCode(String channelCode){
		this.channelCode = channelCode;	
	}
	
	public String getInviteCode() {
        return inviteCode;
    }

    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    public byte[] getInviteCodePic() {
        return inviteCodePic;
    }

    public void setInviteCodePic(byte[] inviteCodePic) {
        this.inviteCodePic = inviteCodePic;
    }

    /**
	 * Get channelCode : 服务商编码. CHANNEL_CODE: VARCHAR2(15) 
	 */
	public String getChannelCode(){
		return this.channelCode;	
	}
	
	/**
	 * Set version : 版本号. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : 版本号. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set channelName : 服务商名称. CHANNEL_NAME: VARCHAR2(100) 
	 */
	public void setChannelName(String channelName){
		this.channelName = channelName;	
	}
	
	/**
	 * Get channelName : 服务商名称. CHANNEL_NAME: VARCHAR2(100) 
	 */
	public String getChannelName(){
		return this.channelName;	
	}
	
	public String getOpTime() {
		return opTime;
	}

	public void setOpTime(String opTime) {
		this.opTime = opTime;
	}

	public String getOpAcc() {
		return opAcc;
	}

	public void setOpAcc(String opAcc) {
		this.opAcc = opAcc;
	}

	/**
	 * Set status : 状态. STATUS: VARCHAR2(2) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: VARCHAR2(2) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR2(200) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR2(200) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set luTime : 最后更新时间. LU_TIME: CHAR(14) 
	 */
	public void setLuTime(String luTime){
		this.luTime = luTime;	
	}
	
	/**
	 * Get luTime : 最后更新时间. LU_TIME: CHAR(14) 
	 */
	public String getLuTime(){
		return this.luTime;	
	}
	
	/**
	 * Set luOrg : 最后更新机构. LU_ORG: VARCHAR2(30) 
	 */
	public void setLuOrg(String luOrg){
		this.luOrg = luOrg;	
	}
	
	/**
	 * Get luOrg : 最后更新机构. LU_ORG: VARCHAR2(30) 
	 */
	public String getLuOrg(){
		return this.luOrg;	
	}
	
	/**
	 * Set fatherId : 上级服务商号. FATHER_ID: VARCHAR2(15) 
	 */
	public void setFatherId(String fatherId){
		this.fatherId = fatherId;	
	}
	
	/**
	 * Get fatherId : 上级服务商号. FATHER_ID: VARCHAR2(15) 
	 */
	public String getFatherId(){
		return this.fatherId;	
	}
	
	/**
	 * Set phone : 联系人电话. PHONE: VARCHAR2(30) 
	 */
	public void setPhone(String phone){
		this.phone = phone;	
	}
	
	/**
	 * Get phone : 联系人电话. PHONE: VARCHAR2(30) 
	 */
	public String getPhone(){
		return this.phone;	
	}
	
	/**
	 * Set person : 联系人姓名. PERSON: VARCHAR2(30) 
	 */
	public void setPerson(String person){
		this.person = person;	
	}
	
	/**
	 * Get person : 联系人姓名. PERSON: VARCHAR2(30) 
	 */
	public String getPerson(){
		return this.person;	
	}

	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}
	
}