package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 服务商信息表 TBL_CORE_CHANNEL : TBL_CORE_CHANNEL
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CoreChannelVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** channelCode : 服务商编码. CHANNEL_CODE: VARCHAR2(15) */
	private String channelCode ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** channelName : 服务商名称. CHANNEL_NAME: VARCHAR2(100) */
	private String channelName ;
	
	/** channelType : 服务商类别. CHANNEL_TYPE: CHAR(14) */
	private String channelType ;
	
	/** profitRate : 服务商分润比例. PROFIT_RATE: NUMBER(5) */
	private Long profitRate ;
	
	/** brandFeeRate : 品牌服务费比例. BRAND_FEE_RATE: NUMBER(5) */
	private Long brandFeeRate ;
	
	/** contactName : 联系人姓名. CONTACT_NAME: VARCHAR2(30) */
	private String contactName ;
	
	/** contactPhone : 联系人电话. CONTACT_PHONE: VARCHAR2(30) */
	private String contactPhone ;
	
	/** oprTime : 创建时间. OPR_TIME: CHAR(14) */
	private String oprTime ;
	
	/** oprAcc : 创建人. OPR_ACC: VARCHAR2(16) */
	private String oprAcc ;
	
	/** status : 状态. STATUS: VARCHAR2(2) */
	private String status ;
	
	/** confStatus : 审批状态. CONF_STATUS: VARCHAR2(2) */
	private String confStatus ;
	
	/** remark : 备注. REMARK: VARCHAR2(200) */
	private String remark ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后修改人. LAST_UPT_ACC: VARCHAR2(16) */
	private String lastUptAcc ;
	
	/** lastUptOrg : 最后修改机构. LAST_UPT_ORG: VARCHAR2(30) */
	private String lastUptOrg ;
	
	/** liquidateFlag : 清算标识位. LIQUIDATE_FLAG: VARCHAR2(2) */
	private String liquidateFlag ;
	
	/** accntType : 账户类型. ACCNT_TYPE: VARCHAR2(2) */
	private String accntType ;
	
	/** accntNoPrivate : 账号. ACCNT_NO_PRIVATE: VARCHAR2(30) */
	private String accntNoPrivate ;
	
	/** accntNamePrivate : 账户名称. ACCNT_NAME_PRIVATE: VARCHAR2(100) */
	private String accntNamePrivate ;
	
	/** spdFlag : 是否浦发. SPD_FLAG: VARCHAR2(2) */
	private String spdFlag ;
	
	/** cardPersonNo : 开户人身份证. CARD_PERSON_NO: VARCHAR2(30) */
	private String cardPersonNo ;
	
	/** bankAccntId : 对公账户代码. BANK_ACCNT_ID: NUMBER */
	private Long bankAccntId ;
	
	/** accntBankPrivate : 开户行号. ACCNT_BANK_PRIVATE: VARCHAR2(100) */
	private String accntBankPrivate ;
	
	/** exportFlag : 服务商是否导出对帐文件标识. EXPORT_FLAG: VARCHAR2(2) */
	private String exportFlag ;
	
	/** downFlag : 服务商是否需要下载商户进件，和商户反馈. DOWN_FLAG: VARCHAR2(2) */
	private String downFlag ;
	
	/** cbcProfitRate : 分期业务服务商分润 -建行成本  （十万级）. CBC_PROFIT_RATE: NUMBER(6) */
	private Long cbcProfitRate ;
	
	/** channelUserid : 服务商管理用户id. CHANNEL_USERID: VARCHAR2(20) */
	private String channelUserid;
	
	/** accntBankNo : 开户行号.  ACCNT_BANK_NO VARCHAR2(20)	 */
	private String accntBankNo ;
	
	/** recNo  : 修改记录编号. REC_NO NUMBER(10)  */
	private Long recNo;
	
	/** bailRecNo  : 保证金修改记录编号. BAIL_REC_NO NUMBER(10)  */
	private Long bailRecNo;
	
    /** conBgnTime  : 合同开始日期. CON_BGN_TIME CHAR(14)  */
	private String conBgnTime;
	
	/** conEndTime  : 合同结束日期. CON_END_TIME CHAR(14)  */
	private String conEndTime;
	
	// -- Extended --
	/** statusDesc : 状态. */
	private String statusDesc ;
	
	/** confStatusDesc : 审批状态. */
	private String confStatusDesc ;
	
	/** accntBankPrivateDesc : 开户行名称.*/
	private String accntBankPrivateDesc ;

	/** 分润记录修改记录状态  */
	private String recStatus;
	/** 分润记录Version */
	private Long recVersion;
	/** 分润记录审核时间 */
	private String recAudTime;
	/** 分润记录审核人*/
	private String recAudAcct;
	/** 分润记录审核意见*/
	private String recAudRemark;
	
	/** 保证金修改记录状态  */
	private String bailStatus;
	
	/** 保证金修改记录状态  */
	private String bailStatusDesc;
	
	/** recStatusDesc: 分润记录修改记录状态  */
	private String recStatusDesc;
	
	/** 保证金记录Version */
	private Long bailRecVersion;
	
	/** 保证金数额  */
	private Long bailAmt;
	
	/** 修改后保证金数额 */
	private Long endAmt;
	
	/** 保证金记录审核时间 */
	private String bailRecAudTime;
	/** 保证金记录审核人*/
	private String bailRecAudUser;
	/** 保证金记录审核意见*/
	private String bailRecAudRemark;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	
	//邀请码
	private String inviteCode;
	private byte[] inviteCodePic;  //BLOB 二维码图片
	
	public String getInviteCode() {
        return inviteCode;
    }

    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    public byte[] getInviteCodePic() {
        return inviteCodePic;
    }

    public void setInviteCodePic(byte[] inviteCodePic) {
        this.inviteCodePic = inviteCodePic;
    }

    public CoreChannelVo() {
		// Default Construtor
	}
	
	public CoreChannelVo(String channelCode) {
		this.channelCode = channelCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set channelCode : 服务商编码. CHANNEL_CODE: VARCHAR2(15) 
	 */
	public void setChannelCode(String channelCode){
		this.channelCode = channelCode;	
	}
	
	/**
	 * Get channelCode : 服务商编码. CHANNEL_CODE: VARCHAR2(15) 
	 */
	public String getChannelCode(){
		return this.channelCode;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set channelName : 服务商名称. CHANNEL_NAME: VARCHAR2(100) 
	 */
	public void setChannelName(String channelName){
		this.channelName = channelName;	
	}
	
	/**
	 * Get channelName : 服务商名称. CHANNEL_NAME: VARCHAR2(100) 
	 */
	public String getChannelName(){
		return this.channelName;	
	}
	
	/**
	 * Set channelType : 服务商类别. CHANNEL_TYPE: CHAR(14) 
	 */
	public void setChannelType(String channelType){
		this.channelType = channelType;	
	}
	
	/**
	 * Get channelType : 服务商类别. CHANNEL_TYPE: CHAR(14) 
	 */
	public String getChannelType(){
		return this.channelType;	
	}
	
	/**
	 * Set profitRate : 服务商分润比例. PROFIT_RATE: NUMBER(5) 
	 */
	public void setProfitRate(Long profitRate){
		this.profitRate = profitRate;	
	}
	
	/**
	 * Get profitRate : 服务商分润比例. PROFIT_RATE: NUMBER(5) 
	 */
	public Long getProfitRate(){
		return this.profitRate;	
	}
	
	/**
	 * Set brandFeeRate : 品牌服务费比例. BRAND_FEE_RATE: NUMBER(5) 
	 */
	public void setBrandFeeRate(Long brandFeeRate){
		this.brandFeeRate = brandFeeRate;	
	}
	
	/**
	 * Get brandFeeRate : 品牌服务费比例. BRAND_FEE_RATE: NUMBER(5) 
	 */
	public Long getBrandFeeRate(){
		return this.brandFeeRate;	
	}
	
	/**
	 * Set contactName : 联系人姓名. CONTACT_NAME: VARCHAR2(30) 
	 */
	public void setContactName(String contactName){
		this.contactName = contactName;	
	}
	
	/**
	 * Get contactName : 联系人姓名. CONTACT_NAME: VARCHAR2(30) 
	 */
	public String getContactName(){
		return this.contactName;	
	}
	
	/**
	 * Set contactPhone : 联系人电话. CONTACT_PHONE: VARCHAR2(30) 
	 */
	public void setContactPhone(String contactPhone){
		this.contactPhone = contactPhone;	
	}
	
	/**
	 * Get contactPhone : 联系人电话. CONTACT_PHONE: VARCHAR2(30) 
	 */
	public String getContactPhone(){
		return this.contactPhone;	
	}
	
	/**
	 * Set oprTime : 创建时间. OPR_TIME: CHAR(14) 
	 */
	public void setOprTime(String oprTime){
		this.oprTime = oprTime;	
	}
	
	/**
	 * Get oprTime : 创建时间. OPR_TIME: CHAR(14) 
	 */
	public String getOprTime(){
		return this.oprTime;	
	}
	
	/**
	 * Set oprAcc : 创建人. OPR_ACC: VARCHAR2(16) 
	 */
	public void setOprAcc(String oprAcc){
		this.oprAcc = oprAcc;	
	}
	
	/**
	 * Get oprAcc : 创建人. OPR_ACC: VARCHAR2(16) 
	 */
	public String getOprAcc(){
		return this.oprAcc;	
	}
	
	/**
	 * Set status : 状态. STATUS: VARCHAR2(2) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: VARCHAR2(2) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set confStatus : 审批状态. CONF_STATUS: VARCHAR2(2) 
	 */
	public void setConfStatus(String confStatus){
		this.confStatus = confStatus;	
	}
	
	/**
	 * Get confStatus : 审批状态. CONF_STATUS: VARCHAR2(2) 
	 */
	public String getConfStatus(){
		return this.confStatus;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR2(200) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR2(200) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后修改人. LAST_UPT_ACC: VARCHAR2(16) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后修改人. LAST_UPT_ACC: VARCHAR2(16) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后修改机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后修改机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}
	
	/**
	 * Set liquidateFlag : 清算标识位. LIQUIDATE_FLAG: VARCHAR2(2) 
	 */
	public void setLiquidateFlag(String liquidateFlag){
		this.liquidateFlag = liquidateFlag;	
	}
	
	/**
	 * Get liquidateFlag : 清算标识位. LIQUIDATE_FLAG: VARCHAR2(2) 
	 */
	public String getLiquidateFlag(){
		return this.liquidateFlag;	
	}
	
	/**
	 * Set accntType : 账户类型. ACCNT_TYPE: VARCHAR2(2) 
	 */
	public void setAccntType(String accntType){
		this.accntType = accntType;	
	}
	
	/**
	 * Get accntType : 账户类型. ACCNT_TYPE: VARCHAR2(2) 
	 */
	public String getAccntType(){
		return this.accntType;	
	}
	
	/**
	 * Set accntNoPrivate : 账号. ACCNT_NO_PRIVATE: VARCHAR2(30) 
	 */
	public void setAccntNoPrivate(String accntNoPrivate){
		this.accntNoPrivate = accntNoPrivate;	
	}
	
	/**
	 * Get accntNoPrivate : 账号. ACCNT_NO_PRIVATE: VARCHAR2(30) 
	 */
	public String getAccntNoPrivate(){
		return this.accntNoPrivate;	
	}
	
	/**
	 * Set accntNamePrivate : 账户名称. ACCNT_NAME_PRIVATE: VARCHAR2(100) 
	 */
	public void setAccntNamePrivate(String accntNamePrivate){
		this.accntNamePrivate = accntNamePrivate;	
	}
	
	/**
	 * Get accntNamePrivate : 账户名称. ACCNT_NAME_PRIVATE: VARCHAR2(100) 
	 */
	public String getAccntNamePrivate(){
		return this.accntNamePrivate;	
	}
	
	/**
	 * Set spdFlag : 是否浦发. SPD_FLAG: VARCHAR2(2) 
	 */
	public void setSpdFlag(String spdFlag){
		this.spdFlag = spdFlag;	
	}
	
	/**
	 * Get spdFlag : 是否浦发. SPD_FLAG: VARCHAR2(2) 
	 */
	public String getSpdFlag(){
		return this.spdFlag;	
	}
	
	/**
	 * Set cardPersonNo : 开户人身份证. CARD_PERSON_NO: NUMBER(5) 
	 */
	public void setCardPersonNo(String cardPersonNo){
		this.cardPersonNo = cardPersonNo;	
	}
	
	/**
	 * Get cardPersonNo : 开户人身份证. CARD_PERSON_NO: NUMBER(5) 
	 */
	public String getCardPersonNo(){
		return this.cardPersonNo;	
	}
	
	/**
	 * Set bankAccntId : 开户行代码. BANK_ACCNT_ID: NUMBER 
	 */
	public void setBankAccntId(Long bankAccntId){
		this.bankAccntId = bankAccntId;	
	}
	
	/**
	 * Get bankAccntId : 开户行代码. BANK_ACCNT_ID: NUMBER 
	 */
	public Long getBankAccntId(){
		return this.bankAccntId;	
	}
	
	/**
	 * Set accntBankPrivate : 开户行名称. ACCNT_BANK_PRIVATE: VARCHAR2(100) 
	 */
	public void setAccntBankPrivate(String accntBankPrivate){
		this.accntBankPrivate = accntBankPrivate;	
	}
	
	/**
	 * Get accntBankPrivate : 开户行名称. ACCNT_BANK_PRIVATE: VARCHAR2(100) 
	 */
	public String getAccntBankPrivate(){
		return this.accntBankPrivate;	
	}
	
	/**
	 * Set exportFlag : 服务商是否导出对帐文件标识. EXPORT_FLAG: VARCHAR2(2) 
	 */
	public void setExportFlag(String exportFlag){
		this.exportFlag = exportFlag;	
	}
	
	/**
	 * Get exportFlag : 服务商是否导出对帐文件标识. EXPORT_FLAG: VARCHAR2(2) 
	 */
	public String getExportFlag(){
		return this.exportFlag;	
	}
	
	/**
	 * Set downFlag : 服务商是否需要下载商户进件，和商户反馈. DOWN_FLAG: VARCHAR2(2) 
	 */
	public void setDownFlag(String downFlag){
		this.downFlag = downFlag;	
	}
	
	/**
	 * Get downFlag : 服务商是否需要下载商户进件，和商户反馈. DOWN_FLAG: VARCHAR2(2) 
	 */
	public String getDownFlag(){
		return this.downFlag;	
	}
	
	/**
	 * Set cbcProfitRate : 分期业务服务商分润 -建行成本  （十万级）. CBC_PROFIT_RATE: NUMBER(6) 
	 */
	public void setCbcProfitRate(Long cbcProfitRate){
		this.cbcProfitRate = cbcProfitRate;	
	}
	
	/**
	 * Get cbcProfitRate : 分期业务服务商分润 -建行成本  （十万级）. CBC_PROFIT_RATE: NUMBER(6) 
	 */
	public Long getCbcProfitRate(){
		return this.cbcProfitRate;	
	}

	/**
	 * @return the statusDesc
	 */
	public String getStatusDesc() {
		return statusDesc;
	}

	/**
	 * @param statusDesc the statusDesc to set
	 */
	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	/**
	 * @return the confStatusDesc
	 */
	public String getConfStatusDesc() {
		return confStatusDesc;
	}

	/**
	 * @param confStatusDesc the confStatusDesc to set
	 */
	public void setConfStatusDesc(String confStatusDesc) {
		this.confStatusDesc = confStatusDesc;
	}

	/**
	 * @return the channelUserid
	 */
	public String getChannelUserid() {
		return channelUserid;
	}

	/**
	 * @param channelUserid the channelUserid to set
	 */
	public void setChannelUserid(String channelUserid) {
		this.channelUserid = channelUserid;
	}

	/**
	 * @return the accntBankNo
	 */
	public String getAccntBankNo() {
		return accntBankNo;
	}

	/**
	 * @param accntBankNo the accntBankNo to set
	 */
	public void setAccntBankNo(String accntBankNo) {
		this.accntBankNo = accntBankNo;
	}

	/**
	 * @return the accntBankPrivateDesc
	 */
	public String getAccntBankPrivateDesc() {
		return accntBankPrivateDesc;
	}

	/**
	 * @param accntBankPrivateDesc the accntBankPrivateDesc to set
	 */
	public void setAccntBankPrivateDesc(String accntBankPrivateDesc) {
		this.accntBankPrivateDesc = accntBankPrivateDesc;
	}

	/**
	 * @return the recNo
	 */
	public Long getRecNo() {
		return recNo;
	}

	/**
	 * @param recNo the recNo to set
	 */
	public void setRecNo(Long recNo) {
		this.recNo = recNo;
	}

	/**
	 * @return the recStatus
	 */
	public String getRecStatus() {
		return recStatus;
	}

	/**
	 * @param recStatus the recStatus to set
	 */
	public void setRecStatus(String recStatus) {
		this.recStatus = recStatus;
	}

	/**
	 * @return the recVersion
	 */
	public Long getRecVersion() {
		return recVersion;
	}

	/**
	 * @param recVersion the recVersion to set
	 */
	public void setRecVersion(Long recVersion) {
		this.recVersion = recVersion;
	}

	/**
	 * @return the recStatusDesc
	 */
	public String getRecStatusDesc() {
		return recStatusDesc;
	}

	/**
	 * @param recStatusDesc the recStatusDesc to set
	 */
	public void setRecStatusDesc(String recStatusDesc) {
		this.recStatusDesc = recStatusDesc;
	}

	/**
	 * @return the recAudTime
	 */
	public String getRecAudTime() {
		return recAudTime;
	}

	/**
	 * @param recAudTime the recAudTime to set
	 */
	public void setRecAudTime(String recAudTime) {
		this.recAudTime = recAudTime;
	}

	/**
	 * @return the recAudAcct
	 */
	public String getRecAudAcct() {
		return recAudAcct;
	}

	/**
	 * @param recAudAcct the recAudAcct to set
	 */
	public void setRecAudAcct(String recAudAcct) {
		this.recAudAcct = recAudAcct;
	}

	/**
	 * @return the recAudRemark
	 */
	public String getRecAudRemark() {
		return recAudRemark;
	}

	/**
	 * @param recAudRemark the recAudRemark to set
	 */
	public void setRecAudRemark(String recAudRemark) {
		this.recAudRemark = recAudRemark;
	}

	/**
	 * @return the bailRecNo
	 */
	public Long getBailRecNo() {
		return bailRecNo;
	}

	/**
	 * @param bailRecNo the bailRecNo to set
	 */
	public void setBailRecNo(Long bailRecNo) {
		this.bailRecNo = bailRecNo;
	}

	/**
	 * @return the bailStatus
	 */
	public String getBailStatus() {
		return bailStatus;
	}

	/**
	 * @param bailStatus the bailStatus to set
	 */
	public void setBailStatus(String bailStatus) {
		this.bailStatus = bailStatus;
	}

	/**
	 * @return the bailStatusDesc
	 */
	public String getBailStatusDesc() {
		return bailStatusDesc;
	}

	/**
	 * @param bailStatusDesc the bailStatusDesc to set
	 */
	public void setBailStatusDesc(String bailStatusDesc) {
		this.bailStatusDesc = bailStatusDesc;
	}

	/**
	 * @return the conBgnTime
	 */
	public String getConBgnTime() {
		return conBgnTime;
	}

	/**
	 * @param conBgnTime the conBgnTime to set
	 */
	public void setConBgnTime(String conBgnTime) {
		this.conBgnTime = conBgnTime;
	}

	/**
	 * @return the conEndTime
	 */
	public String getConEndTime() {
		return conEndTime;
	}

	/**
	 * @param conEndTime the conEndTime to set
	 */
	public void setConEndTime(String conEndTime) {
		this.conEndTime = conEndTime;
	}

	/**
	 * @return the bailAmt
	 */
	public Long getBailAmt() {
		return bailAmt;
	}

	/**
	 * @param bailAmt the bailAmt to set
	 */
	public void setBailAmt(Long bailAmt) {
		this.bailAmt = bailAmt;
	}

	/**
	 * @return the bailRecVersion
	 */
	public Long getBailRecVersion() {
		return bailRecVersion;
	}

	/**
	 * @param bailRecVersion the bailRecVersion to set
	 */
	public void setBailRecVersion(Long bailRecVersion) {
		this.bailRecVersion = bailRecVersion;
	}

	/**
	 * @return the endAmt
	 */
	public Long getEndAmt() {
		return endAmt;
	}

	/**
	 * @param endAmt the endAmt to set
	 */
	public void setEndAmt(Long endAmt) {
		this.endAmt = endAmt;
	}

	/**
	 * @return the bailRecAudTime
	 */
	public String getBailRecAudTime() {
		return bailRecAudTime;
	}

	/**
	 * @param bailRecAudTime the bailRecAudTime to set
	 */
	public void setBailRecAudTime(String bailRecAudTime) {
		this.bailRecAudTime = bailRecAudTime;
	}

	/**
	 * @return the bailRecAudUser
	 */
	public String getBailRecAudUser() {
		return bailRecAudUser;
	}

	/**
	 * @param bailRecAudUser the bailRecAudUser to set
	 */
	public void setBailRecAudUser(String bailRecAudUser) {
		this.bailRecAudUser = bailRecAudUser;
	}

	/**
	 * @return the bailRecAudRemark
	 */
	public String getBailRecAudRemark() {
		return bailRecAudRemark;
	}

	/**
	 * @param bailRecAudRemark the bailRecAudRemark to set
	 */
	public void setBailRecAudRemark(String bailRecAudRemark) {
		this.bailRecAudRemark = bailRecAudRemark;
	}
	
}