package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 服务商结算费率变更记录控制表 TBL_CORE_CHNL_RATE_REC : TBL_CORE_CHNL_RATE_REC
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CoreChnlRateRecVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** recNo : 修改记录编号. REC_NO: NUMBER(10) */
	private Long recNo ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(20) */
	private String channelCode ;
	
	/** remark : 备注. REMARK: VARCHAR2(600) */
	private String remark ;
	
	/** status : 状态. STATUS: VARCHAR2(2) */
	private String status ;
	
	/** oprTime : 创建时间. OPR_TIME: VARCHAR2(14) */
	private String oprTime ;
	
	/** oprAcct : 创建人. OPR_ACCT: VARCHAR2(30) */
	private String oprAcct ;
	
	/** audTime : 审核时间. AUD_TIME: VARCHAR2(14) */
	private String audTime ;
	
	/** audAcct : 审核人. AUD_ACCT: VARCHAR2(30) */
	private String audAcct ;
	
	/** audRemark : 审核意见. AUD_REMARK: VARCHAR2(600) */
	private String audRemark ;
	
	/** lastUpdAcct : 最后更新用户. LAST_UPD_ACCT: VARCHAR2(30) */
	private String lastUpdAcct ;
	
	/** lastUpdTime : 最后更新时间. LAST_UPD_TIME: VARCHAR2(14) */
	private String lastUpdTime ;
	
	// -- Extended --
	/** channelName : 服务商名称 */
	private String channelName ; 
	/** statusDesc : 状态  */
	private String statusDesc ;
	
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CoreChnlRateRecVo() {
		// Default Construtor
	}
	
	public CoreChnlRateRecVo(Long recNo) {
		this.recNo = recNo;
	}
		
	// -- Setter And Getter
	/**
	 * Set recNo : 修改记录编号. REC_NO: NUMBER(10) 
	 */
	public void setRecNo(Long recNo){
		this.recNo = recNo;	
	}
	
	/**
	 * Get recNo : 修改记录编号. REC_NO: NUMBER(10) 
	 */
	public Long getRecNo(){
		return this.recNo;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(20) 
	 */
	public void setChannelCode(String channelCode){
		this.channelCode = channelCode;	
	}
	
	/**
	 * Get channelCode : 服务商编号. CHANNEL_CODE: VARCHAR2(20) 
	 */
	public String getChannelCode(){
		return this.channelCode;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR2(600) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR2(600) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set status : 状态. STATUS: VARCHAR2(2) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: VARCHAR2(2) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set oprTime : 创建时间. OPR_TIME: VARCHAR2(14) 
	 */
	public void setOprTime(String oprTime){
		this.oprTime = oprTime;	
	}
	
	/**
	 * Get oprTime : 创建时间. OPR_TIME: VARCHAR2(14) 
	 */
	public String getOprTime(){
		return this.oprTime;	
	}
	
	/**
	 * Set oprAcct : 创建人. OPR_ACCT: VARCHAR2(30) 
	 */
	public void setOprAcct(String oprAcct){
		this.oprAcct = oprAcct;	
	}
	
	/**
	 * Get oprAcct : 创建人. OPR_ACCT: VARCHAR2(30) 
	 */
	public String getOprAcct(){
		return this.oprAcct;	
	}
	
	/**
	 * Set audTime : 审核时间. AUD_TIME: VARCHAR2(14) 
	 */
	public void setAudTime(String audTime){
		this.audTime = audTime;	
	}
	
	/**
	 * Get audTime : 审核时间. AUD_TIME: VARCHAR2(14) 
	 */
	public String getAudTime(){
		return this.audTime;	
	}
	
	/**
	 * Set audAcct : 审核人. AUD_ACCT: VARCHAR2(30) 
	 */
	public void setAudAcct(String audAcct){
		this.audAcct = audAcct;	
	}
	
	/**
	 * Get audAcct : 审核人. AUD_ACCT: VARCHAR2(30) 
	 */
	public String getAudAcct(){
		return this.audAcct;	
	}
	
	/**
	 * Set audRemark : 审核意见. AUD_REMARK: VARCHAR2(600) 
	 */
	public void setAudRemark(String audRemark){
		this.audRemark = audRemark;	
	}
	
	/**
	 * Get audRemark : 审核意见. AUD_REMARK: VARCHAR2(600) 
	 */
	public String getAudRemark(){
		return this.audRemark;	
	}
	
	/**
	 * Set lastUpdAcct : 最后更新用户. LAST_UPD_ACCT: VARCHAR2(30) 
	 */
	public void setLastUpdAcct(String lastUpdAcct){
		this.lastUpdAcct = lastUpdAcct;	
	}
	
	/**
	 * Get lastUpdAcct : 最后更新用户. LAST_UPD_ACCT: VARCHAR2(30) 
	 */
	public String getLastUpdAcct(){
		return this.lastUpdAcct;	
	}
	
	/**
	 * Set lastUpdTime : 最后更新时间. LAST_UPD_TIME: VARCHAR2(14) 
	 */
	public void setLastUpdTime(String lastUpdTime){
		this.lastUpdTime = lastUpdTime;	
	}
	
	/**
	 * Get lastUpdTime : 最后更新时间. LAST_UPD_TIME: VARCHAR2(14) 
	 */
	public String getLastUpdTime(){
		return this.lastUpdTime;	
	}

	/**
	 * @return the channelName
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * @param channelName the channelName to set
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	/**
	 * @return the statusDesc
	 */
	public String getStatusDesc() {
		return statusDesc;
	}

	/**
	 * @param statusDesc the statusDesc to set
	 */
	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}
	
}