package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 费改_MCC分组扣率关系表 TBL_CORE_MCCGRP_RATE : TBL_CORE_MCCGRP_RATE
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CoreMccgrpRateVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mccGrp : MCC组类别. MCC_GRP: VARCHAR2(4) */
	private String mccGrp ;
	
	/** mccDesc : 描述. MCC_DESC: VARCHAR2(100) */
	private String mccDesc ;
	
	/** feeStlmType : 手续费收取方式. FEE_STLM_TYPE: VARCHAR2(2) */
	private String feeStlmType ;
	
	/** debitTtlRate : 借记卡总扣率. DEBIT_TTL_RATE: NUMBER(12) */
	private Long debitTtlRate ;
	
	/** creditTtlRate : 贷记卡总扣率. CREDIT_TTL_RATE: NUMBER(12) */
	private Long creditTtlRate ;
	
	/** unRate : 银联网络服务费_费率. UN_RATE: NUMBER(12) */
	private Long unRate ;
	
	/** unMaxFee : 银联网络服务费_单笔封顶. UN_MAX_FEE: NUMBER(12) */
	private Long unMaxFee ;
	
	/** bdRate : 发卡行服务费_借记费率. BD_RATE: NUMBER(12) */
	private Long bdRate ;
	
	/** bdMaxFee : 发卡行服务费_借记单笔封顶. BD_MAX_FEE: NUMBER(12) */
	private Long bdMaxFee ;
	
	/** bcRate : 发卡行服务费_贷记费率. BC_RATE: NUMBER(12) */
	private Long bcRate ;
	
	/** bcMaxFee : 发卡行服务费_贷记单笔封顶. BC_MAX_FEE: NUMBER(12) */
	private Long bcMaxFee ;
	
	/** feeVal : 固定手续费. FEE_VAL: NUMBER(12) */
	private Long feeVal ;
	
	/** feeUnVal : 银联固定手续费. FEE_UN_VAL: NUMBER(12) */
	private Long feeUnVal ;
	
	/** feeCardVal : 发卡行固定手续费. FEE_CARD_VAL: NUMBER(12) */
	private Long feeCardVal ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CoreMccgrpRateVo() {
		// Default Construtor
	}
	
	public CoreMccgrpRateVo(String mccGrp) {
		this.mccGrp = mccGrp;
	}
		
	// -- Setter And Getter
	/**
	 * Set mccGrp : MCC组类别. MCC_GRP: VARCHAR2(4) 
	 */
	public void setMccGrp(String mccGrp){
		this.mccGrp = mccGrp;	
	}
	
	/**
	 * Get mccGrp : MCC组类别. MCC_GRP: VARCHAR2(4) 
	 */
	public String getMccGrp(){
		return this.mccGrp;	
	}
	
	/**
	 * Set mccDesc : 描述. MCC_DESC: VARCHAR2(100) 
	 */
	public void setMccDesc(String mccDesc){
		this.mccDesc = mccDesc;	
	}
	
	/**
	 * Get mccDesc : 描述. MCC_DESC: VARCHAR2(100) 
	 */
	public String getMccDesc(){
		return this.mccDesc;	
	}
	
	/**
	 * Set feeStlmType : 手续费收取方式. FEE_STLM_TYPE: VARCHAR2(2) 
	 */
	public void setFeeStlmType(String feeStlmType){
		this.feeStlmType = feeStlmType;	
	}
	
	/**
	 * Get feeStlmType : 手续费收取方式. FEE_STLM_TYPE: VARCHAR2(2) 
	 */
	public String getFeeStlmType(){
		return this.feeStlmType;	
	}
	
	/**
	 * Set debitTtlRate : 借记卡总扣率. DEBIT_TTL_RATE: NUMBER(12) 
	 */
	public void setDebitTtlRate(Long debitTtlRate){
		this.debitTtlRate = debitTtlRate;	
	}
	
	/**
	 * Get debitTtlRate : 借记卡总扣率. DEBIT_TTL_RATE: NUMBER(12) 
	 */
	public Long getDebitTtlRate(){
		return this.debitTtlRate;	
	}
	
	/**
	 * Set creditTtlRate : 贷记卡总扣率. CREDIT_TTL_RATE: NUMBER(12) 
	 */
	public void setCreditTtlRate(Long creditTtlRate){
		this.creditTtlRate = creditTtlRate;	
	}
	
	/**
	 * Get creditTtlRate : 贷记卡总扣率. CREDIT_TTL_RATE: NUMBER(12) 
	 */
	public Long getCreditTtlRate(){
		return this.creditTtlRate;	
	}
	
	/**
	 * Set unRate : 银联网络服务费_费率. UN_RATE: NUMBER(12) 
	 */
	public void setUnRate(Long unRate){
		this.unRate = unRate;	
	}
	
	/**
	 * Get unRate : 银联网络服务费_费率. UN_RATE: NUMBER(12) 
	 */
	public Long getUnRate(){
		return this.unRate;	
	}
	
	/**
	 * Set unMaxFee : 银联网络服务费_单笔封顶. UN_MAX_FEE: NUMBER(12) 
	 */
	public void setUnMaxFee(Long unMaxFee){
		this.unMaxFee = unMaxFee;	
	}
	
	/**
	 * Get unMaxFee : 银联网络服务费_单笔封顶. UN_MAX_FEE: NUMBER(12) 
	 */
	public Long getUnMaxFee(){
		return this.unMaxFee;	
	}
	
	/**
	 * Set bdRate : 发卡行服务费_借记费率. BD_RATE: NUMBER(12) 
	 */
	public void setBdRate(Long bdRate){
		this.bdRate = bdRate;	
	}
	
	/**
	 * Get bdRate : 发卡行服务费_借记费率. BD_RATE: NUMBER(12) 
	 */
	public Long getBdRate(){
		return this.bdRate;	
	}
	
	/**
	 * Set bdMaxFee : 发卡行服务费_借记单笔封顶. BD_MAX_FEE: NUMBER(12) 
	 */
	public void setBdMaxFee(Long bdMaxFee){
		this.bdMaxFee = bdMaxFee;	
	}
	
	/**
	 * Get bdMaxFee : 发卡行服务费_借记单笔封顶. BD_MAX_FEE: NUMBER(12) 
	 */
	public Long getBdMaxFee(){
		return this.bdMaxFee;	
	}
	
	/**
	 * Set bcRate : 发卡行服务费_贷记费率. BC_RATE: NUMBER(12) 
	 */
	public void setBcRate(Long bcRate){
		this.bcRate = bcRate;	
	}
	
	/**
	 * Get bcRate : 发卡行服务费_贷记费率. BC_RATE: NUMBER(12) 
	 */
	public Long getBcRate(){
		return this.bcRate;	
	}
	
	/**
	 * Set bcMaxFee : 发卡行服务费_贷记单笔封顶. BC_MAX_FEE: NUMBER(12) 
	 */
	public void setBcMaxFee(Long bcMaxFee){
		this.bcMaxFee = bcMaxFee;	
	}
	
	/**
	 * Get bcMaxFee : 发卡行服务费_贷记单笔封顶. BC_MAX_FEE: NUMBER(12) 
	 */
	public Long getBcMaxFee(){
		return this.bcMaxFee;	
	}
	
	/**
	 * Set feeVal : 固定手续费. FEE_VAL: NUMBER(12) 
	 */
	public void setFeeVal(Long feeVal){
		this.feeVal = feeVal;	
	}
	
	/**
	 * Get feeVal : 固定手续费. FEE_VAL: NUMBER(12) 
	 */
	public Long getFeeVal(){
		return this.feeVal;	
	}
	
	/**
	 * Set feeUnVal : 银联固定手续费. FEE_UN_VAL: NUMBER(12) 
	 */
	public void setFeeUnVal(Long feeUnVal){
		this.feeUnVal = feeUnVal;	
	}
	
	/**
	 * Get feeUnVal : 银联固定手续费. FEE_UN_VAL: NUMBER(12) 
	 */
	public Long getFeeUnVal(){
		return this.feeUnVal;	
	}
	
	/**
	 * Set feeCardVal : 发卡行固定手续费. FEE_CARD_VAL: NUMBER(12) 
	 */
	public void setFeeCardVal(Long feeCardVal){
		this.feeCardVal = feeCardVal;	
	}
	
	/**
	 * Get feeCardVal : 发卡行固定手续费. FEE_CARD_VAL: NUMBER(12) 
	 */
	public Long getFeeCardVal(){
		return this.feeCardVal;	
	}
	
}