package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 代理商结算费率历史表 TBL_CORE_CHANNEL_RATE_HIS : TBL_CORE_CHANNEL_RATE_HIS
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CoreChannelRateHisVo extends CoreChannelRateVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** seqNo : 流水号. SEQ_NO: NUMBER(10) */
	private Long seqNo ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CoreChannelRateHisVo() {
		// Default Construtor
	}
	
	public CoreChannelRateHisVo(Long seqNo, String channelCode, String mccType, String mcc) {
		super(channelCode,mccType,mcc);
		this.seqNo = seqNo;
	}
	
	public CoreChannelRateHisVo(Long seqNo, CoreChannelRateVo rateVo) {
		this.seqNo = seqNo;
		if ( rateVo != null ) {
			this.setChannelCode(rateVo.getChannelCode());
			this.setMccGrp(rateVo.getMccGrp());
			this.setMcc(rateVo.getMcc());
			this.setVersion(rateVo.getVersion());
			this.setRemark(rateVo.getRemark());
			this.setRate(rateVo.getRate());
			this.setMaxFee(rateVo.getMaxFee());
			this.setChnlRatio(rateVo.getChnlRatio());
			this.setLastUpdAcct(rateVo.getLastUpdAcct());
			this.setLastUpdTime(rateVo.getLastUpdTime());
		}
	}
		
	// -- Setter And Getter
	/**
	 * Set seqNo : 流水号. SEQ_NO: NUMBER(10) 
	 */
	public void setSeqNo(Long seqNo){
		this.seqNo = seqNo;	
	}
	
	/**
	 * Get seqNo : 流水号. SEQ_NO: NUMBER(10) 
	 */
	public Long getSeqNo(){
		return this.seqNo;	
	}
	
}