package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: MCC扣率关系表 TBL_CORE_MCC_RATE : TBL_CORE_MCC_RATE
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CoreMccRateVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mcc : MCC码. MCC: CHAR(4) */
	private String mcc ;
	
	/** mccDesc : 描述. MCC_DESC: VARCHAR2(100) */
	private String mccDesc ;
	
	/** feeStlmType : 手续费收取方式. FEE_STLM_TYPE: VARCHAR2(2) */
	private String feeStlmType ;
	
	/** rate : 总扣率. RATE: NUMBER(5) */
	private Long rate ;
	
	/** unRate : 银联扣率. UN_RATE: NUMBER(5) */
	private Long unRate ;
	
	/** cardRate : 发卡行扣率. CARD_RATE: NUMBER(5) */
	private Long cardRate ;
	
	/** maxFee : 总封顶值. MAX_FEE: NUMBER(12) */
	private Long maxFee ;
	
	/** maxUnFee : 银联封顶值. MAX_UN_FEE: NUMBER(12) */
	private Long maxUnFee ;
	
	/** maxCardFee : 发卡行封顶值. MAX_CARD_FEE: NUMBER(12) */
	private Long maxCardFee ;
	
	/** feeVal : 固定手续费. FEE_VAL: NUMBER(12) */
	private Long feeVal ;
	
	/** feeUnVal : 银联固定手续费. FEE_UN_VAL: NUMBER(12) */
	private Long feeUnVal ;
	
	/** feeCardVal : 发卡行固定手续费. FEE_CARD_VAL: NUMBER(12) */
	private Long feeCardVal ;
	
	/** maxBrandFee : 品牌封顶值. MAX_BRAND_FEE: NUMBER(12) */
	private Long maxBrandFee ;
	
	/** mccType : MCC分类. MCC_TYPE: VARCHAR2(4) */
	private String mccType ;
	
	/** mccGrp : MCC大类. MCC_GRP: VARCHAR2(4) */
	private String mccGrp;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CoreMccRateVo() {
		// Default Construtor
	}
	
	public CoreMccRateVo(String mcc) {
		this.mcc = mcc;
	}
		
	// -- Setter And Getter
	/**
	 * Set mcc : MCC码. MCC: CHAR(4) 
	 */
	public void setMcc(String mcc){
		this.mcc = mcc;	
	}
	
	/**
	 * Get mcc : MCC码. MCC: CHAR(4) 
	 */
	public String getMcc(){
		return this.mcc;	
	}
	
	/**
	 * Set mccDesc : 描述. MCC_DESC: VARCHAR2(100) 
	 */
	public void setMccDesc(String mccDesc){
		this.mccDesc = mccDesc;	
	}
	
	/**
	 * Get mccDesc : 描述. MCC_DESC: VARCHAR2(100) 
	 */
	public String getMccDesc(){
		return this.mccDesc;	
	}
	
	/**
	 * Set feeStlmType : 手续费收取方式. FEE_STLM_TYPE: VARCHAR2(2) 
	 */
	public void setFeeStlmType(String feeStlmType){
		this.feeStlmType = feeStlmType;	
	}
	
	/**
	 * Get feeStlmType : 手续费收取方式. FEE_STLM_TYPE: VARCHAR2(2) 
	 */
	public String getFeeStlmType(){
		return this.feeStlmType;	
	}
	
	/**
	 * Set rate : 总扣率. RATE: NUMBER(5) 
	 */
	public void setRate(Long rate){
		this.rate = rate;	
	}
	
	/**
	 * Get rate : 总扣率. RATE: NUMBER(5) 
	 */
	public Long getRate(){
		return this.rate;	
	}
	
	/**
	 * Set unRate : 银联扣率. UN_RATE: NUMBER(5) 
	 */
	public void setUnRate(Long unRate){
		this.unRate = unRate;	
	}
	
	/**
	 * Get unRate : 银联扣率. UN_RATE: NUMBER(5) 
	 */
	public Long getUnRate(){
		return this.unRate;	
	}
	
	/**
	 * Set cardRate : 发卡行扣率. CARD_RATE: NUMBER(5) 
	 */
	public void setCardRate(Long cardRate){
		this.cardRate = cardRate;	
	}
	
	/**
	 * Get cardRate : 发卡行扣率. CARD_RATE: NUMBER(5) 
	 */
	public Long getCardRate(){
		return this.cardRate;	
	}
	
	/**
	 * Set maxFee : 总封顶值. MAX_FEE: NUMBER(12) 
	 */
	public void setMaxFee(Long maxFee){
		this.maxFee = maxFee;	
	}
	
	/**
	 * Get maxFee : 总封顶值. MAX_FEE: NUMBER(12) 
	 */
	public Long getMaxFee(){
		return this.maxFee;	
	}
	
	/**
	 * Set maxUnFee : 银联封顶值. MAX_UN_FEE: NUMBER(12) 
	 */
	public void setMaxUnFee(Long maxUnFee){
		this.maxUnFee = maxUnFee;	
	}
	
	/**
	 * Get maxUnFee : 银联封顶值. MAX_UN_FEE: NUMBER(12) 
	 */
	public Long getMaxUnFee(){
		return this.maxUnFee;	
	}
	
	/**
	 * Set maxCardFee : 发卡行封顶值. MAX_CARD_FEE: NUMBER(12) 
	 */
	public void setMaxCardFee(Long maxCardFee){
		this.maxCardFee = maxCardFee;	
	}
	
	/**
	 * Get maxCardFee : 发卡行封顶值. MAX_CARD_FEE: NUMBER(12) 
	 */
	public Long getMaxCardFee(){
		return this.maxCardFee;	
	}
	
	/**
	 * Set feeVal : 固定手续费. FEE_VAL: NUMBER(12) 
	 */
	public void setFeeVal(Long feeVal){
		this.feeVal = feeVal;	
	}
	
	/**
	 * Get feeVal : 固定手续费. FEE_VAL: NUMBER(12) 
	 */
	public Long getFeeVal(){
		return this.feeVal;	
	}
	
	/**
	 * Set feeUnVal : 银联固定手续费. FEE_UN_VAL: NUMBER(12) 
	 */
	public void setFeeUnVal(Long feeUnVal){
		this.feeUnVal = feeUnVal;	
	}
	
	/**
	 * Get feeUnVal : 银联固定手续费. FEE_UN_VAL: NUMBER(12) 
	 */
	public Long getFeeUnVal(){
		return this.feeUnVal;	
	}
	
	/**
	 * Set feeCardVal : 发卡行固定手续费. FEE_CARD_VAL: NUMBER(12) 
	 */
	public void setFeeCardVal(Long feeCardVal){
		this.feeCardVal = feeCardVal;	
	}
	
	/**
	 * Get feeCardVal : 发卡行固定手续费. FEE_CARD_VAL: NUMBER(12) 
	 */
	public Long getFeeCardVal(){
		return this.feeCardVal;	
	}
	
	/**
	 * Set maxBrandFee : 品牌封顶值. MAX_BRAND_FEE: NUMBER(12) 
	 */
	public void setMaxBrandFee(Long maxBrandFee){
		this.maxBrandFee = maxBrandFee;	
	}
	
	/**
	 * Get maxBrandFee : 品牌封顶值. MAX_BRAND_FEE: NUMBER(12) 
	 */
	public Long getMaxBrandFee(){
		return this.maxBrandFee;	
	}
	
	/**
	 * Set mccType : MCC分类. MCC_TYPE: VARCHAR2(4) 
	 */
	public void setMccType(String mccType){
		this.mccType = mccType;	
	}
	
	/**
	 * Get mccType : MCC分类. MCC_TYPE: VARCHAR2(4) 
	 */
	public String getMccType(){
		return this.mccType;	
	}

	/**
	 * @return the mccGrp
	 */
	public String getMccGrp() {
		return mccGrp;
	}

	/**
	 * @param mccGrp the mccGrp to set
	 */
	public void setMccGrp(String mccGrp) {
		this.mccGrp = mccGrp;
	}
	
}