package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 交易商户银行转换表 : TBL_CORE_MER_ORG
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MerOrgInfoVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** bankCode : 银行. BANK_CODE: VARCHAR2(10) */
	private String bankCode ;
	
	
	/** merOutCode : 外部银行商户号(42). MER_OUT_CODE: VARCHAR2(15) */
	private String merOutCode ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** merOutAcquireInstitCode : 外部标识码(32). MER_OUT_ACQUIRE_INSTIT_CODE: VARCHAR2(11) */
	private String merOutAcquireInstitCode ;
	
	/** mccCups : 对银联的商户类别码（MCC）. MCC_CUPS: VARCHAR2(10) */
	private String mccCups ;
	
	/** cardAcceptName : 受卡方名称(43). CARD_ACCEPT_NAME: VARCHAR2(40) */
	private String cardAcceptName ;
	
	/** sepcialchargeType : 特殊计费类型(银60.3.1）. SEPCIALCHARGE_TYPE: VARCHAR2(2) */
	private String sepcialchargeType ;
	
	/** sepcialchargeLevel : 特殊计费级别(银60.3.2）. SEPCIALCHARGE_LEVEL: VARCHAR2(1) */
	private String sepcialchargeLevel ;
	
	/** busiDeductionRate : 位商户扣率，值为扣率*10000(122.1). BUSI_DEDUCTION_RATE: VARCHAR2(6) */
	private String busiDeductionRate ;
	
	
	/** rsv1 : RSV1. RSV1: VARCHAR2(100) */
	private String rsv1 ;
	
	/** rsv2 : RSV2. RSV2: VARCHAR2(100) */
	private String rsv2 ;
	
	/** lastUptTime : 最后更新时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后更新账户. LAST_UPT_ACC: VARCHAR2(16) */
	private String lastUptAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) */
	private String lastUptOrg ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MerOrgInfoVo() {
		// Default Construtor
	}
	
		
	// -- Setter And Getter
	/**
	 * Set bankCode : 银行. BANK_CODE: VARCHAR2(10) 
	 */
	public void setBankCode(String bankCode){
		this.bankCode = bankCode;	
	}
	
	/**
	 * Get bankCode : 银行. BANK_CODE: VARCHAR2(10) 
	 */
	public String getBankCode(){
		return this.bankCode;	
	}
	
	
	/**
	 * Set merOutCode : 外部银行商户号(42). MER_OUT_CODE: VARCHAR2(15) 
	 */
	public void setMerOutCode(String merOutCode){
		this.merOutCode = merOutCode;	
	}
	
	/**
	 * Get merOutCode : 外部银行商户号(42). MER_OUT_CODE: VARCHAR2(15) 
	 */
	public String getMerOutCode(){
		return this.merOutCode;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set merOutAcquireInstitCode : 外部标识码(32). MER_OUT_ACQUIRE_INSTIT_CODE: VARCHAR2(11) 
	 */
	public void setMerOutAcquireInstitCode(String merOutAcquireInstitCode){
		this.merOutAcquireInstitCode = merOutAcquireInstitCode;	
	}
	
	/**
	 * Get merOutAcquireInstitCode : 外部标识码(32). MER_OUT_ACQUIRE_INSTIT_CODE: VARCHAR2(11) 
	 */
	public String getMerOutAcquireInstitCode(){
		return this.merOutAcquireInstitCode;	
	}
	
	/**
	 * Set mccCups : 对银联的商户类别码（MCC）. MCC_CUPS: VARCHAR2(10) 
	 */
	public void setMccCups(String mccCups){
		this.mccCups = mccCups;	
	}
	
	/**
	 * Get mccCups : 对银联的商户类别码（MCC）. MCC_CUPS: VARCHAR2(10) 
	 */
	public String getMccCups(){
		return this.mccCups;	
	}
	
	/**
	 * Set cardAcceptName : 受卡方名称(43). CARD_ACCEPT_NAME: VARCHAR2(40) 
	 */
	public void setCardAcceptName(String cardAcceptName){
		this.cardAcceptName = cardAcceptName;	
	}
	
	/**
	 * Get cardAcceptName : 受卡方名称(43). CARD_ACCEPT_NAME: VARCHAR2(40) 
	 */
	public String getCardAcceptName(){
		return this.cardAcceptName;	
	}
	
	/**
	 * Set sepcialchargeType : 特殊计费类型(银60.3.1）. SEPCIALCHARGE_TYPE: VARCHAR2(2) 
	 */
	public void setSepcialchargeType(String sepcialchargeType){
		this.sepcialchargeType = sepcialchargeType;	
	}
	
	/**
	 * Get sepcialchargeType : 特殊计费类型(银60.3.1）. SEPCIALCHARGE_TYPE: VARCHAR2(2) 
	 */
	public String getSepcialchargeType(){
		return this.sepcialchargeType;	
	}
	
	/**
	 * Set sepcialchargeLevel : 特殊计费级别(银60.3.2）. SEPCIALCHARGE_LEVEL: VARCHAR2(1) 
	 */
	public void setSepcialchargeLevel(String sepcialchargeLevel){
		this.sepcialchargeLevel = sepcialchargeLevel;	
	}
	
	/**
	 * Get sepcialchargeLevel : 特殊计费级别(银60.3.2）. SEPCIALCHARGE_LEVEL: VARCHAR2(1) 
	 */
	public String getSepcialchargeLevel(){
		return this.sepcialchargeLevel;	
	}
	
	/**
	 * Set busiDeductionRate : 位商户扣率，值为扣率*10000(122.1). BUSI_DEDUCTION_RATE: VARCHAR2(6) 
	 */
	public void setBusiDeductionRate(String busiDeductionRate){
		this.busiDeductionRate = busiDeductionRate;	
	}
	
	/**
	 * Get busiDeductionRate : 位商户扣率，值为扣率*10000(122.1). BUSI_DEDUCTION_RATE: VARCHAR2(6) 
	 */
	public String getBusiDeductionRate(){
		return this.busiDeductionRate;	
	}
	
	/**
	 * Set rsv1 : RSV1. RSV1: VARCHAR2(100) 
	 */
	public void setRsv1(String rsv1){
		this.rsv1 = rsv1;	
	}
	
	/**
	 * Get rsv1 : RSV1. RSV1: VARCHAR2(100) 
	 */
	public String getRsv1(){
		return this.rsv1;	
	}
	
	/**
	 * Set rsv2 : RSV2. RSV2: VARCHAR2(100) 
	 */
	public void setRsv2(String rsv2){
		this.rsv2 = rsv2;	
	}
	
	/**
	 * Get rsv2 : RSV2. RSV2: VARCHAR2(100) 
	 */
	public String getRsv2(){
		return this.rsv2;	
	}
	
	/**
	 * Set lastUptTime : 最后更新时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后更新时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后更新账户. LAST_UPT_ACC: VARCHAR2(16) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后更新账户. LAST_UPT_ACC: VARCHAR2(16) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}

	
}