package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户平台用户表 TBL_SYS_MER_USER : TBL_SYS_MER_USER
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysMerUserVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** userid : 用户ID. USERID: VARCHAR2(20) */
	private String userid ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** loginid : 登陆ID. LOGINID: VARCHAR2(20) */
	private String loginid ;
	
	/** loginpasswd : 登陆密码. LOGINPASSWD: VARCHAR2(64) */
	private String loginpasswd ;
	
	/** username : 密码.. USERNAME: VARCHAR2(50) */
	private String username ;
	
	/** phone : 电话. PHONE: VARCHAR2(20) */
	private String phone ;
	
	/** email : EMAIL. EMAIL: VARCHAR2(50) */
	private String email ;
	
	/** addr : 地址. ADDR: VARCHAR2(200) */
	private String addr ;
	
	/** status : 状态. STATUS: CHAR(1) */
	private String status ;
	
	/** loginFailTimes : 密码错误次数. LOGIN_FAIL_TIMES: VARCHAR2(2) */
	private String loginFailTimes ;
	
	/** type : 等级分类. TYPE: VARCHAR2(2) */
	private String type ;
	
	/** channel : 用户所属服务商. CHANNEL: CHAR(30) */
	private String channel ;
	
	/** luTime : 修改时间. LU_TIME: VARCHAR2(14) */
	private String luTime ;
	
	/** demo : 描述. DEMO: VARCHAR2(100) */
	private String demo ;
	
	/** cardNo : 证件号码. CARD_NO: VARCHAR2(30) */
	private String cardNo ;
	
	/** cardType : 证件类型. CARD_TYPE: CHAR(2) */
	private String cardType ;
	
	/** luUserid : 最后修改人. LU_USERID: VARCHAR2(20) */
	private String luUserid ;
	
	/** opUserid : 创建人USERID. OP_USERID: VARCHAR2(20) */
	private String opUserid ;
	
	/** opTime : 账号建立时间. OP_TIME: VARCHAR2(20) */
	private String opTime ;
	
	/** reserved2 : 保留域2. RESERVED2: VARCHAR2(200) */
	private String reserved2 ;
	
	/** reserved1 : 保留域1. RESERVED1: VARCHAR2(200) */
	private String reserved1 ;
	
	/** mid : 商户号. MID: VARCHAR2(20) */
	private String mid ;
	
	/** islocked : 上锁标识. ISLOCKED: VARCHAR2(2) */
	private String islocked ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysMerUserVo() {
		// Default Construtor
	}
	
	public SysMerUserVo(String userid) {
		this.userid = userid;
	}
		
	// -- Setter And Getter
	/**
	 * Set userid : 用户ID. USERID: VARCHAR2(20) 
	 */
	public void setUserid(String userid){
		this.userid = userid;	
	}
	
	/**
	 * Get userid : 用户ID. USERID: VARCHAR2(20) 
	 */
	public String getUserid(){
		return this.userid;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set loginid : 登陆ID. LOGINID: VARCHAR2(20) 
	 */
	public void setLoginid(String loginid){
		this.loginid = loginid;	
	}
	
	/**
	 * Get loginid : 登陆ID. LOGINID: VARCHAR2(20) 
	 */
	public String getLoginid(){
		return this.loginid;	
	}
	
	/**
	 * Set loginpasswd : 登陆密码. LOGINPASSWD: VARCHAR2(64) 
	 */
	public void setLoginpasswd(String loginpasswd){
		this.loginpasswd = loginpasswd;	
	}
	
	/**
	 * Get loginpasswd : 登陆密码. LOGINPASSWD: VARCHAR2(64) 
	 */
	public String getLoginpasswd(){
		return this.loginpasswd;	
	}
	
	/**
	 * Set username : 密码.. USERNAME: VARCHAR2(50) 
	 */
	public void setUsername(String username){
		this.username = username;	
	}
	
	/**
	 * Get username : 密码.. USERNAME: VARCHAR2(50) 
	 */
	public String getUsername(){
		return this.username;	
	}
	
	/**
	 * Set phone : 电话. PHONE: VARCHAR2(20) 
	 */
	public void setPhone(String phone){
		this.phone = phone;	
	}
	
	/**
	 * Get phone : 电话. PHONE: VARCHAR2(20) 
	 */
	public String getPhone(){
		return this.phone;	
	}
	
	/**
	 * Set email : EMAIL. EMAIL: VARCHAR2(50) 
	 */
	public void setEmail(String email){
		this.email = email;	
	}
	
	/**
	 * Get email : EMAIL. EMAIL: VARCHAR2(50) 
	 */
	public String getEmail(){
		return this.email;	
	}
	
	/**
	 * Set addr : 地址. ADDR: VARCHAR2(200) 
	 */
	public void setAddr(String addr){
		this.addr = addr;	
	}
	
	/**
	 * Get addr : 地址. ADDR: VARCHAR2(200) 
	 */
	public String getAddr(){
		return this.addr;	
	}
	
	/**
	 * Set status : 状态. STATUS: CHAR(1) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: CHAR(1) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set loginFailTimes : 密码错误次数. LOGIN_FAIL_TIMES: VARCHAR2(2) 
	 */
	public void setLoginFailTimes(String loginFailTimes){
		this.loginFailTimes = loginFailTimes;	
	}
	
	/**
	 * Get loginFailTimes : 密码错误次数. LOGIN_FAIL_TIMES: VARCHAR2(2) 
	 */
	public String getLoginFailTimes(){
		return this.loginFailTimes;	
	}
	
	/**
	 * Set type : 等级分类. TYPE: VARCHAR2(2) 
	 */
	public void setType(String type){
		this.type = type;	
	}
	
	/**
	 * Get type : 等级分类. TYPE: VARCHAR2(2) 
	 */
	public String getType(){
		return this.type;	
	}
	
	/**
	 * Set channel : 用户所属服务商. CHANNEL: CHAR(30) 
	 */
	public void setChannel(String channel){
		this.channel = channel;	
	}
	
	/**
	 * Get channel : 用户所属服务商. CHANNEL: CHAR(30) 
	 */
	public String getChannel(){
		return this.channel;	
	}
	
	/**
	 * Set luTime : 修改时间. LU_TIME: VARCHAR2(14) 
	 */
	public void setLuTime(String luTime){
		this.luTime = luTime;	
	}
	
	/**
	 * Get luTime : 修改时间. LU_TIME: VARCHAR2(14) 
	 */
	public String getLuTime(){
		return this.luTime;	
	}
	
	/**
	 * Set demo : 描述. DEMO: VARCHAR2(100) 
	 */
	public void setDemo(String demo){
		this.demo = demo;	
	}
	
	/**
	 * Get demo : 描述. DEMO: VARCHAR2(100) 
	 */
	public String getDemo(){
		return this.demo;	
	}
	
	/**
	 * Set cardNo : 证件号码. CARD_NO: VARCHAR2(30) 
	 */
	public void setCardNo(String cardNo){
		this.cardNo = cardNo;	
	}
	
	/**
	 * Get cardNo : 证件号码. CARD_NO: VARCHAR2(30) 
	 */
	public String getCardNo(){
		return this.cardNo;	
	}
	
	/**
	 * Set cardType : 证件类型. CARD_TYPE: CHAR(2) 
	 */
	public void setCardType(String cardType){
		this.cardType = cardType;	
	}
	
	/**
	 * Get cardType : 证件类型. CARD_TYPE: CHAR(2) 
	 */
	public String getCardType(){
		return this.cardType;	
	}
	
	/**
	 * Set luUserid : 最后修改人. LU_USERID: VARCHAR2(20) 
	 */
	public void setLuUserid(String luUserid){
		this.luUserid = luUserid;	
	}
	
	/**
	 * Get luUserid : 最后修改人. LU_USERID: VARCHAR2(20) 
	 */
	public String getLuUserid(){
		return this.luUserid;	
	}
	
	/**
	 * Set opUserid : 创建人USERID. OP_USERID: VARCHAR2(20) 
	 */
	public void setOpUserid(String opUserid){
		this.opUserid = opUserid;	
	}
	
	/**
	 * Get opUserid : 创建人USERID. OP_USERID: VARCHAR2(20) 
	 */
	public String getOpUserid(){
		return this.opUserid;	
	}
	
	/**
	 * Set opTime : 账号建立时间. OP_TIME: VARCHAR2(20) 
	 */
	public void setOpTime(String opTime){
		this.opTime = opTime;	
	}
	
	/**
	 * Get opTime : 账号建立时间. OP_TIME: VARCHAR2(20) 
	 */
	public String getOpTime(){
		return this.opTime;	
	}
	
	/**
	 * Set reserved2 : 保留域2. RESERVED2: VARCHAR2(200) 
	 */
	public void setReserved2(String reserved2){
		this.reserved2 = reserved2;	
	}
	
	/**
	 * Get reserved2 : 保留域2. RESERVED2: VARCHAR2(200) 
	 */
	public String getReserved2(){
		return this.reserved2;	
	}
	
	/**
	 * Set reserved1 : 保留域1. RESERVED1: VARCHAR2(200) 
	 */
	public void setReserved1(String reserved1){
		this.reserved1 = reserved1;	
	}
	
	/**
	 * Get reserved1 : 保留域1. RESERVED1: VARCHAR2(200) 
	 */
	public String getReserved1(){
		return this.reserved1;	
	}
	
	/**
	 * Set mid : 商户号. MID: VARCHAR2(20) 
	 */
	public void setMid(String mid){
		this.mid = mid;	
	}
	
	/**
	 * Get mid : 商户号. MID: VARCHAR2(20) 
	 */
	public String getMid(){
		return this.mid;	
	}
	
	/**
	 * Set islocked : 上锁标识. ISLOCKED: VARCHAR2(2) 
	 */
	public void setIslocked(String islocked){
		this.islocked = islocked;	
	}
	
	/**
	 * Get islocked : 上锁标识. ISLOCKED: VARCHAR2(2) 
	 */
	public String getIslocked(){
		return this.islocked;	
	}
	
}