package com.jiuyv.yl.console.orgmngr.entity ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户服务商变更记录表 TBL_SYS_ORG_CHNL_HIS : TBL_SYS_ORG_CHNL_HIS
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysOrgChnlHisVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** seqNo : 记录序号. SEQ_NO: NUMBER(10) */
	private Long seqNo ;
	
	/** orgCode : 机构代码. ORG_CODE: VARCHAR2(30) */
	private String orgCode ;
	
	/** fatherOrgCode : 上级机构代码. FATHER_ORG_CODE: VARCHAR2(30) */
	private String fatherOrgCode ;
	
	/** sday : 清算日期. SDAY: CHAR(8) */
	private String sday ;
	
	/** lastUpdTm : 最后修改时间. LAST_UPD_TM: CHAR(14) */
	private String lastUpdTm ;
	
	/** lastUpdOpid : 最后修改操作员号. LAST_UPD_OPID: VARCHAR2(15) */
	private String lastUpdOpid ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysOrgChnlHisVo() {
		// Default Construtor
	}
	
	public SysOrgChnlHisVo(Long seqNo) {
		this.seqNo = seqNo;
	}
		
	public SysOrgChnlHisVo(String orgCode, String fatherOrgCode,
			String lastUpdOpid) {
		super();
		this.orgCode = orgCode;
		this.fatherOrgCode = fatherOrgCode;
		this.lastUpdOpid = lastUpdOpid;
	}

	// -- Setter And Getter
	/**
	 * Set seqNo : 记录序号. SEQ_NO: NUMBER(10) 
	 */
	public void setSeqNo(Long seqNo){
		this.seqNo = seqNo;	
	}
	
	/**
	 * Get seqNo : 记录序号. SEQ_NO: NUMBER(10) 
	 */
	public Long getSeqNo(){
		return this.seqNo;	
	}
	
	/**
	 * Set orgCode : 机构代码. ORG_CODE: VARCHAR2(30) 
	 */
	public void setOrgCode(String orgCode){
		this.orgCode = orgCode;	
	}
	
	/**
	 * Get orgCode : 机构代码. ORG_CODE: VARCHAR2(30) 
	 */
	public String getOrgCode(){
		return this.orgCode;	
	}
	
	/**
	 * Set fatherOrgCode : 上级机构代码. FATHER_ORG_CODE: VARCHAR2(30) 
	 */
	public void setFatherOrgCode(String fatherOrgCode){
		this.fatherOrgCode = fatherOrgCode;	
	}
	
	/**
	 * Get fatherOrgCode : 上级机构代码. FATHER_ORG_CODE: VARCHAR2(30) 
	 */
	public String getFatherOrgCode(){
		return this.fatherOrgCode;	
	}
	
	/**
	 * Set sday : 清算日期. SDAY: CHAR(8) 
	 */
	public void setSday(String sday){
		this.sday = sday;	
	}
	
	/**
	 * Get sday : 清算日期. SDAY: CHAR(8) 
	 */
	public String getSday(){
		return this.sday;	
	}
	
	/**
	 * Set lastUpdTm : 最后修改时间. LAST_UPD_TM: CHAR(14) 
	 */
	public void setLastUpdTm(String lastUpdTm){
		this.lastUpdTm = lastUpdTm;	
	}
	
	/**
	 * Get lastUpdTm : 最后修改时间. LAST_UPD_TM: CHAR(14) 
	 */
	public String getLastUpdTm(){
		return this.lastUpdTm;	
	}
	
	/**
	 * Set lastUpdOpid : 最后修改操作员号. LAST_UPD_OPID: VARCHAR2(15) 
	 */
	public void setLastUpdOpid(String lastUpdOpid){
		this.lastUpdOpid = lastUpdOpid;	
	}
	
	/**
	 * Get lastUpdOpid : 最后修改操作员号. LAST_UPD_OPID: VARCHAR2(15) 
	 */
	public String getLastUpdOpid(){
		return this.lastUpdOpid;	
	}
	
}