package com.jiuyv.yl.console.outmer.dao.impl ;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.jiuyv.yl.console.common.dao.impl.BaseDaoImpl;
import com.jiuyv.yl.console.outmer.dao.inter.IMhtAttachInfoHisDao;
import com.jiuyv.yl.console.outmer.entity.MhtAttachInfoHisVo;

// Generated by AutoCode4J
/**
 * Database Access Object: 商户附件信息历史表 TBL_MHT_ATTACH_INFO_HIS : TBL_MHT_ATTACH_INFO_HIS
 * This is a DAO. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtAttachInfoHisDaoImpl extends BaseDaoImpl<MhtAttachInfoHisVo> implements IMhtAttachInfoHisDao {

	private final static String SELECT_PK_SNM = ".__selectByPk";
	/**
	 * sqlmap namespace
	 */
	protected String ns() {
		return "TBL_MHT_ATTACH_INFO_HIS";	
	}
	
	/**
	 * provide sequence name
	 */
	protected String seq() {
		// TODO 
		return null;
	}

	/**
	 * Find MhtAttachInfoHisVo by Primary Key
	 * 
	 * @param athNo : 附件编号
	 * @param oprNo : 日志流水号	 
	 * @return MhtAttachInfoHisVo : 商户附件信息历史表 TBL_MHT_ATTACH_INFO_HIS
	 */
	public MhtAttachInfoHisVo findByPK(Long athNo , Long oprNo ) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("athNo", athNo);
		param.put("oprNo", oprNo);
		List<MhtAttachInfoHisVo> lst = getExtendSqlMapClientTemplate().queryForList(ns() + SELECT_PK_SNM, param);
		if ( lst!= null && lst.size() == 1 ) {
			return lst.get(0);
		}
		return null;
	}

}