package com.jiuyv.yl.console.outmer.dao.impl ;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.jiuyv.yl.console.common.dao.impl.BaseDaoImpl;
import com.jiuyv.yl.console.outmer.dao.inter.IMhtAttachInfoDao;
import com.jiuyv.yl.console.outmer.entity.MhtAttachInfoVo;

// Generated by AutoCode4J
/**
 * Database Access Object: 商户附件信息表 TBL_MHT_ATTACH_INFO : TBL_MHT_ATTACH_INFO
 * This is a DAO. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtAttachInfoDaoImpl extends BaseDaoImpl<MhtAttachInfoVo> implements IMhtAttachInfoDao {

	private final static String SELECT_PK_SNM = ".__selectByPk";
	/**
	 * sqlmap namespace
	 */
	protected String ns() {
		return "TBL_MHT_ATTACH_INFO";	
	}
	
	/**
	 * provide sequence name
	 */
	protected String seq() {
		// TODO 
		return null;
	}

	/**
	 * Find MhtAttachInfoVo by Primary Key
	 * 
	 * @param athNo : 附件编号	 
	 * @return MhtAttachInfoVo : 商户附件信息表 TBL_MHT_ATTACH_INFO
	 */
	public MhtAttachInfoVo findByPK(Long athNo ) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("athNo", athNo);
		List<MhtAttachInfoVo> lst = getExtendSqlMapClientTemplate().queryForList(ns() + SELECT_PK_SNM, param);
		if ( lst!= null && lst.size() == 1 ) {
			return lst.get(0);
		}
		return null;
	}
	
	/**
	 * 根据mid查询商户附件Map，
	 * key为athType
	 * @param mid
	 * @return
	 */
	public Map<String, MhtAttachInfoVo> findAthTypeMapByMid(String mid) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("mid", mid);
		return getExtendSqlMapClientTemplate().queryForMap(ns() + ".findAthTypeMapByMid", param, "athType");
	}

	/**
	 * 生成athNo编号
	 * @param athInfoVo
	 */
	public MhtAttachInfoVo insertWithKey(MhtAttachInfoVo athInfoVo) {
		getExtendSqlMapClientTemplate().insert(ns() + ".insertWithKey", athInfoVo);
		return findByPK(athInfoVo.getAthNo());
	}

}