package com.jiuyv.yl.console.outmer.dao.impl ;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.jiuyv.yl.console.common.dao.impl.BaseDaoImpl;
import com.jiuyv.yl.console.outmer.dao.inter.IMhtAttachInfoAddDao;
import com.jiuyv.yl.console.outmer.entity.MhtAttachInfoAddVo;

// Generated by AutoCode4J
/**
 * Database Access Object: 商户进件附件信息表 TBL_MHT_ATTACH_INFO_ADD : TBL_MHT_ATTACH_INFO_ADD
 * This is a DAO. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtAttachInfoAddDaoImpl extends BaseDaoImpl<MhtAttachInfoAddVo> implements IMhtAttachInfoAddDao {

	private final static String SELECT_PK_SNM = ".__selectByPk";
	/**
	 * sqlmap namespace
	 */
	protected String ns() {
		return "TBL_MHT_ATTACH_INFO_ADD";	
	}
	
	/**
	 * provide sequence name
	 */
	protected String seq() {
		// TODO 
		return null;
	}

	/**
	 * Find MhtAttachInfoAddVo by Primary Key
	 * 
	 * @param athNo : 附件编号	 
	 * @return MhtAttachInfoAddVo : 商户进件附件信息表 TBL_MHT_ATTACH_INFO_ADD
	 */
	public MhtAttachInfoAddVo findByPK(Long athNo ) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("athNo", athNo);
		List<MhtAttachInfoAddVo> lst = getExtendSqlMapClientTemplate().queryForList(ns() + SELECT_PK_SNM, param);
		if ( lst!= null && lst.size() == 1 ) {
			return lst.get(0);
		}
		return null;
	}
	
	/**
	 * 根据orgCode查询进件附件Map
	 * @param orgCode
	 * @return
	 */
	public Map<String, MhtAttachInfoAddVo> findAthTypeMapByOrgCode(String orgCode) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("orgCode", orgCode);
		return getExtendSqlMapClientTemplate().queryForMap(ns() + ".findAthTypeMapByOrgCode", param, "athType");
	}

}