package com.jiuyv.yl.console.lottery.entity;

public class TblLotteryMerchant {

	private String nickName;
	private long addAmt;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_lottery_merchant.MERID
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	private String merid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_lottery_merchant.MERNAME
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	private String mername;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_lottery_merchant.TELPHONE
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	private String telphone;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_lottery_merchant.STATUS
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_lottery_merchant.CREATE_DATE
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	private String createDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_lottery_merchant.CREATE_CHL
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	private String createChl;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_lottery_merchant.AMT
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	private Long amt;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_lottery_merchant.MERID
	 * @return  the value of tbl_lottery_merchant.MERID
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public String getMerid() {
		return merid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_lottery_merchant.MERID
	 * @param merid  the value for tbl_lottery_merchant.MERID
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public void setMerid(String merid) {
		this.merid = merid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_lottery_merchant.MERNAME
	 * @return  the value of tbl_lottery_merchant.MERNAME
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public String getMername() {
		return mername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_lottery_merchant.MERNAME
	 * @param mername  the value for tbl_lottery_merchant.MERNAME
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public void setMername(String mername) {
		this.mername = mername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_lottery_merchant.TELPHONE
	 * @return  the value of tbl_lottery_merchant.TELPHONE
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_lottery_merchant.TELPHONE
	 * @param telphone  the value for tbl_lottery_merchant.TELPHONE
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_lottery_merchant.STATUS
	 * @return  the value of tbl_lottery_merchant.STATUS
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_lottery_merchant.STATUS
	 * @param status  the value for tbl_lottery_merchant.STATUS
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_lottery_merchant.CREATE_DATE
	 * @return  the value of tbl_lottery_merchant.CREATE_DATE
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_lottery_merchant.CREATE_DATE
	 * @param createDate  the value for tbl_lottery_merchant.CREATE_DATE
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_lottery_merchant.CREATE_CHL
	 * @return  the value of tbl_lottery_merchant.CREATE_CHL
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public String getCreateChl() {
		return createChl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_lottery_merchant.CREATE_CHL
	 * @param createChl  the value for tbl_lottery_merchant.CREATE_CHL
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public void setCreateChl(String createChl) {
		this.createChl = createChl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_lottery_merchant.AMT
	 * @return  the value of tbl_lottery_merchant.AMT
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public Long getAmt() {
		return amt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_lottery_merchant.AMT
	 * @param amt  the value for tbl_lottery_merchant.AMT
	 * @ibatorgenerated  Sun Oct 22 22:51:41 CST 2017
	 */
	public void setAmt(Long amt) {
		this.amt = amt;
	}
	

	public long getAddAmt() {
		return addAmt;
	}

	public void setAddAmt(long addAmt) {
		this.addAmt = addAmt;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
}