package com.jiuyv.yl.console.lottery.entity;

public class TblLotteryOrder {
	
	private String msgId;
	private String lotteryResult;
	private Long transAmtSum;
	private int count;
	
	private Long transAmt;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.ID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.LOTTERY_ID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String lotteryId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.LOTTERY_TYPE
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String lotteryType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.MERID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String merid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.STATUS
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.SYSTEM_TIME
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String systemTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.total_single_double
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String totalSingleDouble;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.total_big_small
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String totalBigSmall;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.total_tail_big_small
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String totalTailBigSmall;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.dragon_tigger
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String dragonTigger;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.leopard
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String leopard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.field1
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String field1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.field2
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String field2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.field3
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String field3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.field4
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String field4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_order.field5
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    private String field5;

    private Long winAmt;
    
    private String nickname;
    
	//查询用
	private String lotteryCode;
	private String statusDesc;
	
    public String getMsgId() {
		return msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	public String getLotteryCode() {
		return lotteryCode;
	}

	public void setLotteryCode(String lotteryCode) {
		this.lotteryCode = lotteryCode;
	}

	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Long getWinAmt() {
		return winAmt;
	}

	public void setWinAmt(Long winAmt) {
		this.winAmt = winAmt;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.ID
     *
     * @return the value of tbl_lottery_order.ID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.ID
     *
     * @param id the value for tbl_lottery_order.ID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.LOTTERY_ID
     *
     * @return the value of tbl_lottery_order.LOTTERY_ID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getLotteryId() {
        return lotteryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.LOTTERY_ID
     *
     * @param lotteryId the value for tbl_lottery_order.LOTTERY_ID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setLotteryId(String lotteryId) {
        this.lotteryId = lotteryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.LOTTERY_TYPE
     *
     * @return the value of tbl_lottery_order.LOTTERY_TYPE
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getLotteryType() {
        return lotteryType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.LOTTERY_TYPE
     *
     * @param lotteryType the value for tbl_lottery_order.LOTTERY_TYPE
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setLotteryType(String lotteryType) {
        this.lotteryType = lotteryType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.MERID
     *
     * @return the value of tbl_lottery_order.MERID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getMerid() {
        return merid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.MERID
     *
     * @param merid the value for tbl_lottery_order.MERID
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setMerid(String merid) {
        this.merid = merid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.STATUS
     *
     * @return the value of tbl_lottery_order.STATUS
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.STATUS
     *
     * @param status the value for tbl_lottery_order.STATUS
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.SYSTEM_TIME
     *
     * @return the value of tbl_lottery_order.SYSTEM_TIME
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getSystemTime() {
        return systemTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.SYSTEM_TIME
     *
     * @param systemTime the value for tbl_lottery_order.SYSTEM_TIME
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setSystemTime(String systemTime) {
        this.systemTime = systemTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.total_single_double
     *
     * @return the value of tbl_lottery_order.total_single_double
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getTotalSingleDouble() {
        return totalSingleDouble;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.total_single_double
     *
     * @param totalSingleDouble the value for tbl_lottery_order.total_single_double
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setTotalSingleDouble(String totalSingleDouble) {
        this.totalSingleDouble = totalSingleDouble;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.total_big_small
     *
     * @return the value of tbl_lottery_order.total_big_small
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getTotalBigSmall() {
        return totalBigSmall;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.total_big_small
     *
     * @param totalBigSmall the value for tbl_lottery_order.total_big_small
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setTotalBigSmall(String totalBigSmall) {
        this.totalBigSmall = totalBigSmall;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.total_tail_big_small
     *
     * @return the value of tbl_lottery_order.total_tail_big_small
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getTotalTailBigSmall() {
        return totalTailBigSmall;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.total_tail_big_small
     *
     * @param totalTailBigSmall the value for tbl_lottery_order.total_tail_big_small
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setTotalTailBigSmall(String totalTailBigSmall) {
        this.totalTailBigSmall = totalTailBigSmall;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.dragon_tigger
     *
     * @return the value of tbl_lottery_order.dragon_tigger
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getDragonTigger() {
        return dragonTigger;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.dragon_tigger
     *
     * @param dragonTigger the value for tbl_lottery_order.dragon_tigger
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setDragonTigger(String dragonTigger) {
        this.dragonTigger = dragonTigger;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.leopard
     *
     * @return the value of tbl_lottery_order.leopard
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getLeopard() {
        return leopard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.leopard
     *
     * @param leopard the value for tbl_lottery_order.leopard
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setLeopard(String leopard) {
        this.leopard = leopard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.field1
     *
     * @return the value of tbl_lottery_order.field1
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.field1
     *
     * @param field1 the value for tbl_lottery_order.field1
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setField1(String field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.field2
     *
     * @return the value of tbl_lottery_order.field2
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.field2
     *
     * @param field2 the value for tbl_lottery_order.field2
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setField2(String field2) {
        this.field2 = field2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.field3
     *
     * @return the value of tbl_lottery_order.field3
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.field3
     *
     * @param field3 the value for tbl_lottery_order.field3
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setField3(String field3) {
        this.field3 = field3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.field4
     *
     * @return the value of tbl_lottery_order.field4
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.field4
     *
     * @param field4 the value for tbl_lottery_order.field4
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setField4(String field4) {
        this.field4 = field4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_order.field5
     *
     * @return the value of tbl_lottery_order.field5
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_order.field5
     *
     * @param field5 the value for tbl_lottery_order.field5
     *
     * @ibatorgenerated Sat Oct 21 21:51:34 CST 2017
     */
    public void setField5(String field5) {
        this.field5 = field5;
    }

	public Long getTransAmt() {
		return transAmt;
	}

	public void setTransAmt(Long transAmt) {
		this.transAmt = transAmt;
	}

	public Long getTransAmtSum() {
		return transAmtSum;
	}

	public void setTransAmtSum(Long transAmtSum) {
		this.transAmtSum = transAmtSum;
	}

	public String getLotteryResult() {
		return lotteryResult;
	}

	public void setLotteryResult(String lotteryResult) {
		this.lotteryResult = lotteryResult;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}
}