package com.jiuyv.yl.console.lottery.entity;

public class TblLotteryWelfare {
	
	private Long transAmtSum;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_welfare.ID
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_welfare.MERID
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    private String merid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_welfare.SYSTEM_TIME
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    private String systemTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_lottery_welfare.amt
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    private Long amt;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_welfare.ID
     *
     * @return the value of tbl_lottery_welfare.ID
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_welfare.ID
     *
     * @param id the value for tbl_lottery_welfare.ID
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_welfare.MERID
     *
     * @return the value of tbl_lottery_welfare.MERID
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public String getMerid() {
        return merid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_welfare.MERID
     *
     * @param merid the value for tbl_lottery_welfare.MERID
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public void setMerid(String merid) {
        this.merid = merid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_welfare.SYSTEM_TIME
     *
     * @return the value of tbl_lottery_welfare.SYSTEM_TIME
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public String getSystemTime() {
        return systemTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_welfare.SYSTEM_TIME
     *
     * @param systemTime the value for tbl_lottery_welfare.SYSTEM_TIME
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public void setSystemTime(String systemTime) {
        this.systemTime = systemTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_lottery_welfare.amt
     *
     * @return the value of tbl_lottery_welfare.amt
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public Long getAmt() {
        return amt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_lottery_welfare.amt
     *
     * @param amt the value for tbl_lottery_welfare.amt
     *
     * @ibatorgenerated Wed Dec 20 23:49:51 CST 2017
     */
    public void setAmt(Long amt) {
        this.amt = amt;
    }

	public Long getTransAmtSum() {
		return transAmtSum;
	}

	public void setTransAmtSum(Long transAmtSum) {
		this.transAmtSum = transAmtSum;
	}
}