package com.jiuyv.yl.console.lottery.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TblWebchantMerchantExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public TblWebchantMerchantExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    protected TblWebchantMerchantExample(TblWebchantMerchantExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_webchant_merchant
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andMeridIsNull() {
            addCriterion("MERID is null");
            return this;
        }

        public Criteria andMeridIsNotNull() {
            addCriterion("MERID is not null");
            return this;
        }

        public Criteria andMeridEqualTo(String value) {
            addCriterion("MERID =", value, "merid");
            return this;
        }

        public Criteria andMeridNotEqualTo(String value) {
            addCriterion("MERID <>", value, "merid");
            return this;
        }

        public Criteria andMeridGreaterThan(String value) {
            addCriterion("MERID >", value, "merid");
            return this;
        }

        public Criteria andMeridGreaterThanOrEqualTo(String value) {
            addCriterion("MERID >=", value, "merid");
            return this;
        }

        public Criteria andMeridLessThan(String value) {
            addCriterion("MERID <", value, "merid");
            return this;
        }

        public Criteria andMeridLessThanOrEqualTo(String value) {
            addCriterion("MERID <=", value, "merid");
            return this;
        }

        public Criteria andMeridLike(String value) {
            addCriterion("MERID like", value, "merid");
            return this;
        }

        public Criteria andMeridNotLike(String value) {
            addCriterion("MERID not like", value, "merid");
            return this;
        }

        public Criteria andMeridIn(List values) {
            addCriterion("MERID in", values, "merid");
            return this;
        }

        public Criteria andMeridNotIn(List values) {
            addCriterion("MERID not in", values, "merid");
            return this;
        }

        public Criteria andMeridBetween(String value1, String value2) {
            addCriterion("MERID between", value1, value2, "merid");
            return this;
        }

        public Criteria andMeridNotBetween(String value1, String value2) {
            addCriterion("MERID not between", value1, value2, "merid");
            return this;
        }

        public Criteria andUinIsNull() {
            addCriterion("UIN is null");
            return this;
        }

        public Criteria andUinIsNotNull() {
            addCriterion("UIN is not null");
            return this;
        }

        public Criteria andUinEqualTo(String value) {
            addCriterion("UIN =", value, "uin");
            return this;
        }

        public Criteria andUinNotEqualTo(String value) {
            addCriterion("UIN <>", value, "uin");
            return this;
        }

        public Criteria andUinGreaterThan(String value) {
            addCriterion("UIN >", value, "uin");
            return this;
        }

        public Criteria andUinGreaterThanOrEqualTo(String value) {
            addCriterion("UIN >=", value, "uin");
            return this;
        }

        public Criteria andUinLessThan(String value) {
            addCriterion("UIN <", value, "uin");
            return this;
        }

        public Criteria andUinLessThanOrEqualTo(String value) {
            addCriterion("UIN <=", value, "uin");
            return this;
        }

        public Criteria andUinLike(String value) {
            addCriterion("UIN like", value, "uin");
            return this;
        }

        public Criteria andUinNotLike(String value) {
            addCriterion("UIN not like", value, "uin");
            return this;
        }

        public Criteria andUinIn(List values) {
            addCriterion("UIN in", values, "uin");
            return this;
        }

        public Criteria andUinNotIn(List values) {
            addCriterion("UIN not in", values, "uin");
            return this;
        }

        public Criteria andUinBetween(String value1, String value2) {
            addCriterion("UIN between", value1, value2, "uin");
            return this;
        }

        public Criteria andUinNotBetween(String value1, String value2) {
            addCriterion("UIN not between", value1, value2, "uin");
            return this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return this;
        }

        public Criteria andUsernameIn(List values) {
            addCriterion("USERNAME in", values, "username");
            return this;
        }

        public Criteria andUsernameNotIn(List values) {
            addCriterion("USERNAME not in", values, "username");
            return this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("NICKNAME is null");
            return this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("NICKNAME is not null");
            return this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("NICKNAME =", value, "nickname");
            return this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("NICKNAME <>", value, "nickname");
            return this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("NICKNAME >", value, "nickname");
            return this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("NICKNAME >=", value, "nickname");
            return this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("NICKNAME <", value, "nickname");
            return this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("NICKNAME <=", value, "nickname");
            return this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("NICKNAME like", value, "nickname");
            return this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("NICKNAME not like", value, "nickname");
            return this;
        }

        public Criteria andNicknameIn(List values) {
            addCriterion("NICKNAME in", values, "nickname");
            return this;
        }

        public Criteria andNicknameNotIn(List values) {
            addCriterion("NICKNAME not in", values, "nickname");
            return this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("NICKNAME between", value1, value2, "nickname");
            return this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("NICKNAME not between", value1, value2, "nickname");
            return this;
        }

        public Criteria andHeadimgurlIsNull() {
            addCriterion("HEADIMGURL is null");
            return this;
        }

        public Criteria andHeadimgurlIsNotNull() {
            addCriterion("HEADIMGURL is not null");
            return this;
        }

        public Criteria andHeadimgurlEqualTo(String value) {
            addCriterion("HEADIMGURL =", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlNotEqualTo(String value) {
            addCriterion("HEADIMGURL <>", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlGreaterThan(String value) {
            addCriterion("HEADIMGURL >", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlGreaterThanOrEqualTo(String value) {
            addCriterion("HEADIMGURL >=", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlLessThan(String value) {
            addCriterion("HEADIMGURL <", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlLessThanOrEqualTo(String value) {
            addCriterion("HEADIMGURL <=", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlLike(String value) {
            addCriterion("HEADIMGURL like", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlNotLike(String value) {
            addCriterion("HEADIMGURL not like", value, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlIn(List values) {
            addCriterion("HEADIMGURL in", values, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlNotIn(List values) {
            addCriterion("HEADIMGURL not in", values, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlBetween(String value1, String value2) {
            addCriterion("HEADIMGURL between", value1, value2, "headimgurl");
            return this;
        }

        public Criteria andHeadimgurlNotBetween(String value1, String value2) {
            addCriterion("HEADIMGURL not between", value1, value2, "headimgurl");
            return this;
        }

        public Criteria andContactflagIsNull() {
            addCriterion("CONTACTFLAG is null");
            return this;
        }

        public Criteria andContactflagIsNotNull() {
            addCriterion("CONTACTFLAG is not null");
            return this;
        }

        public Criteria andContactflagEqualTo(String value) {
            addCriterion("CONTACTFLAG =", value, "contactflag");
            return this;
        }

        public Criteria andContactflagNotEqualTo(String value) {
            addCriterion("CONTACTFLAG <>", value, "contactflag");
            return this;
        }

        public Criteria andContactflagGreaterThan(String value) {
            addCriterion("CONTACTFLAG >", value, "contactflag");
            return this;
        }

        public Criteria andContactflagGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACTFLAG >=", value, "contactflag");
            return this;
        }

        public Criteria andContactflagLessThan(String value) {
            addCriterion("CONTACTFLAG <", value, "contactflag");
            return this;
        }

        public Criteria andContactflagLessThanOrEqualTo(String value) {
            addCriterion("CONTACTFLAG <=", value, "contactflag");
            return this;
        }

        public Criteria andContactflagLike(String value) {
            addCriterion("CONTACTFLAG like", value, "contactflag");
            return this;
        }

        public Criteria andContactflagNotLike(String value) {
            addCriterion("CONTACTFLAG not like", value, "contactflag");
            return this;
        }

        public Criteria andContactflagIn(List values) {
            addCriterion("CONTACTFLAG in", values, "contactflag");
            return this;
        }

        public Criteria andContactflagNotIn(List values) {
            addCriterion("CONTACTFLAG not in", values, "contactflag");
            return this;
        }

        public Criteria andContactflagBetween(String value1, String value2) {
            addCriterion("CONTACTFLAG between", value1, value2, "contactflag");
            return this;
        }

        public Criteria andContactflagNotBetween(String value1, String value2) {
            addCriterion("CONTACTFLAG not between", value1, value2, "contactflag");
            return this;
        }

        public Criteria andRemarknameIsNull() {
            addCriterion("REMARKNAME is null");
            return this;
        }

        public Criteria andRemarknameIsNotNull() {
            addCriterion("REMARKNAME is not null");
            return this;
        }

        public Criteria andRemarknameEqualTo(String value) {
            addCriterion("REMARKNAME =", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameNotEqualTo(String value) {
            addCriterion("REMARKNAME <>", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameGreaterThan(String value) {
            addCriterion("REMARKNAME >", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKNAME >=", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameLessThan(String value) {
            addCriterion("REMARKNAME <", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameLessThanOrEqualTo(String value) {
            addCriterion("REMARKNAME <=", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameLike(String value) {
            addCriterion("REMARKNAME like", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameNotLike(String value) {
            addCriterion("REMARKNAME not like", value, "remarkname");
            return this;
        }

        public Criteria andRemarknameIn(List values) {
            addCriterion("REMARKNAME in", values, "remarkname");
            return this;
        }

        public Criteria andRemarknameNotIn(List values) {
            addCriterion("REMARKNAME not in", values, "remarkname");
            return this;
        }

        public Criteria andRemarknameBetween(String value1, String value2) {
            addCriterion("REMARKNAME between", value1, value2, "remarkname");
            return this;
        }

        public Criteria andRemarknameNotBetween(String value1, String value2) {
            addCriterion("REMARKNAME not between", value1, value2, "remarkname");
            return this;
        }

        public Criteria andHideinputbarflagIsNull() {
            addCriterion("HIDEINPUTBARFLAG is null");
            return this;
        }

        public Criteria andHideinputbarflagIsNotNull() {
            addCriterion("HIDEINPUTBARFLAG is not null");
            return this;
        }

        public Criteria andHideinputbarflagEqualTo(String value) {
            addCriterion("HIDEINPUTBARFLAG =", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagNotEqualTo(String value) {
            addCriterion("HIDEINPUTBARFLAG <>", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagGreaterThan(String value) {
            addCriterion("HIDEINPUTBARFLAG >", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagGreaterThanOrEqualTo(String value) {
            addCriterion("HIDEINPUTBARFLAG >=", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagLessThan(String value) {
            addCriterion("HIDEINPUTBARFLAG <", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagLessThanOrEqualTo(String value) {
            addCriterion("HIDEINPUTBARFLAG <=", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagLike(String value) {
            addCriterion("HIDEINPUTBARFLAG like", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagNotLike(String value) {
            addCriterion("HIDEINPUTBARFLAG not like", value, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagIn(List values) {
            addCriterion("HIDEINPUTBARFLAG in", values, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagNotIn(List values) {
            addCriterion("HIDEINPUTBARFLAG not in", values, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagBetween(String value1, String value2) {
            addCriterion("HIDEINPUTBARFLAG between", value1, value2, "hideinputbarflag");
            return this;
        }

        public Criteria andHideinputbarflagNotBetween(String value1, String value2) {
            addCriterion("HIDEINPUTBARFLAG not between", value1, value2, "hideinputbarflag");
            return this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return this;
        }

        public Criteria andSexIn(List values) {
            addCriterion("SEX in", values, "sex");
            return this;
        }

        public Criteria andSexNotIn(List values) {
            addCriterion("SEX not in", values, "sex");
            return this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("SIGNATURE is null");
            return this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("SIGNATURE is not null");
            return this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("SIGNATURE =", value, "signature");
            return this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("SIGNATURE <>", value, "signature");
            return this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("SIGNATURE >", value, "signature");
            return this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("SIGNATURE >=", value, "signature");
            return this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("SIGNATURE <", value, "signature");
            return this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("SIGNATURE <=", value, "signature");
            return this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("SIGNATURE like", value, "signature");
            return this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("SIGNATURE not like", value, "signature");
            return this;
        }

        public Criteria andSignatureIn(List values) {
            addCriterion("SIGNATURE in", values, "signature");
            return this;
        }

        public Criteria andSignatureNotIn(List values) {
            addCriterion("SIGNATURE not in", values, "signature");
            return this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("SIGNATURE between", value1, value2, "signature");
            return this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("SIGNATURE not between", value1, value2, "signature");
            return this;
        }

        public Criteria andVerifyflagIsNull() {
            addCriterion("VERIFYFLAG is null");
            return this;
        }

        public Criteria andVerifyflagIsNotNull() {
            addCriterion("VERIFYFLAG is not null");
            return this;
        }

        public Criteria andVerifyflagEqualTo(String value) {
            addCriterion("VERIFYFLAG =", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagNotEqualTo(String value) {
            addCriterion("VERIFYFLAG <>", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagGreaterThan(String value) {
            addCriterion("VERIFYFLAG >", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFYFLAG >=", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagLessThan(String value) {
            addCriterion("VERIFYFLAG <", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagLessThanOrEqualTo(String value) {
            addCriterion("VERIFYFLAG <=", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagLike(String value) {
            addCriterion("VERIFYFLAG like", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagNotLike(String value) {
            addCriterion("VERIFYFLAG not like", value, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagIn(List values) {
            addCriterion("VERIFYFLAG in", values, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagNotIn(List values) {
            addCriterion("VERIFYFLAG not in", values, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagBetween(String value1, String value2) {
            addCriterion("VERIFYFLAG between", value1, value2, "verifyflag");
            return this;
        }

        public Criteria andVerifyflagNotBetween(String value1, String value2) {
            addCriterion("VERIFYFLAG not between", value1, value2, "verifyflag");
            return this;
        }

        public Criteria andOwneruinIsNull() {
            addCriterion("OWNERUIN is null");
            return this;
        }

        public Criteria andOwneruinIsNotNull() {
            addCriterion("OWNERUIN is not null");
            return this;
        }

        public Criteria andOwneruinEqualTo(String value) {
            addCriterion("OWNERUIN =", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinNotEqualTo(String value) {
            addCriterion("OWNERUIN <>", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinGreaterThan(String value) {
            addCriterion("OWNERUIN >", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinGreaterThanOrEqualTo(String value) {
            addCriterion("OWNERUIN >=", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinLessThan(String value) {
            addCriterion("OWNERUIN <", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinLessThanOrEqualTo(String value) {
            addCriterion("OWNERUIN <=", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinLike(String value) {
            addCriterion("OWNERUIN like", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinNotLike(String value) {
            addCriterion("OWNERUIN not like", value, "owneruin");
            return this;
        }

        public Criteria andOwneruinIn(List values) {
            addCriterion("OWNERUIN in", values, "owneruin");
            return this;
        }

        public Criteria andOwneruinNotIn(List values) {
            addCriterion("OWNERUIN not in", values, "owneruin");
            return this;
        }

        public Criteria andOwneruinBetween(String value1, String value2) {
            addCriterion("OWNERUIN between", value1, value2, "owneruin");
            return this;
        }

        public Criteria andOwneruinNotBetween(String value1, String value2) {
            addCriterion("OWNERUIN not between", value1, value2, "owneruin");
            return this;
        }

        public Criteria andPyinitialIsNull() {
            addCriterion("PYINITIAL is null");
            return this;
        }

        public Criteria andPyinitialIsNotNull() {
            addCriterion("PYINITIAL is not null");
            return this;
        }

        public Criteria andPyinitialEqualTo(String value) {
            addCriterion("PYINITIAL =", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialNotEqualTo(String value) {
            addCriterion("PYINITIAL <>", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialGreaterThan(String value) {
            addCriterion("PYINITIAL >", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialGreaterThanOrEqualTo(String value) {
            addCriterion("PYINITIAL >=", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialLessThan(String value) {
            addCriterion("PYINITIAL <", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialLessThanOrEqualTo(String value) {
            addCriterion("PYINITIAL <=", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialLike(String value) {
            addCriterion("PYINITIAL like", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialNotLike(String value) {
            addCriterion("PYINITIAL not like", value, "pyinitial");
            return this;
        }

        public Criteria andPyinitialIn(List values) {
            addCriterion("PYINITIAL in", values, "pyinitial");
            return this;
        }

        public Criteria andPyinitialNotIn(List values) {
            addCriterion("PYINITIAL not in", values, "pyinitial");
            return this;
        }

        public Criteria andPyinitialBetween(String value1, String value2) {
            addCriterion("PYINITIAL between", value1, value2, "pyinitial");
            return this;
        }

        public Criteria andPyinitialNotBetween(String value1, String value2) {
            addCriterion("PYINITIAL not between", value1, value2, "pyinitial");
            return this;
        }

        public Criteria andPyquanpinIsNull() {
            addCriterion("PYQUANPIN is null");
            return this;
        }

        public Criteria andPyquanpinIsNotNull() {
            addCriterion("PYQUANPIN is not null");
            return this;
        }

        public Criteria andPyquanpinEqualTo(String value) {
            addCriterion("PYQUANPIN =", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinNotEqualTo(String value) {
            addCriterion("PYQUANPIN <>", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinGreaterThan(String value) {
            addCriterion("PYQUANPIN >", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinGreaterThanOrEqualTo(String value) {
            addCriterion("PYQUANPIN >=", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinLessThan(String value) {
            addCriterion("PYQUANPIN <", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinLessThanOrEqualTo(String value) {
            addCriterion("PYQUANPIN <=", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinLike(String value) {
            addCriterion("PYQUANPIN like", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinNotLike(String value) {
            addCriterion("PYQUANPIN not like", value, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinIn(List values) {
            addCriterion("PYQUANPIN in", values, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinNotIn(List values) {
            addCriterion("PYQUANPIN not in", values, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinBetween(String value1, String value2) {
            addCriterion("PYQUANPIN between", value1, value2, "pyquanpin");
            return this;
        }

        public Criteria andPyquanpinNotBetween(String value1, String value2) {
            addCriterion("PYQUANPIN not between", value1, value2, "pyquanpin");
            return this;
        }

        public Criteria andRemarkpyinitialIsNull() {
            addCriterion("REMARKPYINITIAL is null");
            return this;
        }

        public Criteria andRemarkpyinitialIsNotNull() {
            addCriterion("REMARKPYINITIAL is not null");
            return this;
        }

        public Criteria andRemarkpyinitialEqualTo(String value) {
            addCriterion("REMARKPYINITIAL =", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialNotEqualTo(String value) {
            addCriterion("REMARKPYINITIAL <>", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialGreaterThan(String value) {
            addCriterion("REMARKPYINITIAL >", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKPYINITIAL >=", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialLessThan(String value) {
            addCriterion("REMARKPYINITIAL <", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialLessThanOrEqualTo(String value) {
            addCriterion("REMARKPYINITIAL <=", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialLike(String value) {
            addCriterion("REMARKPYINITIAL like", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialNotLike(String value) {
            addCriterion("REMARKPYINITIAL not like", value, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialIn(List values) {
            addCriterion("REMARKPYINITIAL in", values, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialNotIn(List values) {
            addCriterion("REMARKPYINITIAL not in", values, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialBetween(String value1, String value2) {
            addCriterion("REMARKPYINITIAL between", value1, value2, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyinitialNotBetween(String value1, String value2) {
            addCriterion("REMARKPYINITIAL not between", value1, value2, "remarkpyinitial");
            return this;
        }

        public Criteria andRemarkpyquanpinIsNull() {
            addCriterion("REMARKPYQUANPIN is null");
            return this;
        }

        public Criteria andRemarkpyquanpinIsNotNull() {
            addCriterion("REMARKPYQUANPIN is not null");
            return this;
        }

        public Criteria andRemarkpyquanpinEqualTo(String value) {
            addCriterion("REMARKPYQUANPIN =", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinNotEqualTo(String value) {
            addCriterion("REMARKPYQUANPIN <>", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinGreaterThan(String value) {
            addCriterion("REMARKPYQUANPIN >", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKPYQUANPIN >=", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinLessThan(String value) {
            addCriterion("REMARKPYQUANPIN <", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinLessThanOrEqualTo(String value) {
            addCriterion("REMARKPYQUANPIN <=", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinLike(String value) {
            addCriterion("REMARKPYQUANPIN like", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinNotLike(String value) {
            addCriterion("REMARKPYQUANPIN not like", value, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinIn(List values) {
            addCriterion("REMARKPYQUANPIN in", values, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinNotIn(List values) {
            addCriterion("REMARKPYQUANPIN not in", values, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinBetween(String value1, String value2) {
            addCriterion("REMARKPYQUANPIN between", value1, value2, "remarkpyquanpin");
            return this;
        }

        public Criteria andRemarkpyquanpinNotBetween(String value1, String value2) {
            addCriterion("REMARKPYQUANPIN not between", value1, value2, "remarkpyquanpin");
            return this;
        }

        public Criteria andStarfriendIsNull() {
            addCriterion("STARFRIEND is null");
            return this;
        }

        public Criteria andStarfriendIsNotNull() {
            addCriterion("STARFRIEND is not null");
            return this;
        }

        public Criteria andStarfriendEqualTo(String value) {
            addCriterion("STARFRIEND =", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendNotEqualTo(String value) {
            addCriterion("STARFRIEND <>", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendGreaterThan(String value) {
            addCriterion("STARFRIEND >", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendGreaterThanOrEqualTo(String value) {
            addCriterion("STARFRIEND >=", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendLessThan(String value) {
            addCriterion("STARFRIEND <", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendLessThanOrEqualTo(String value) {
            addCriterion("STARFRIEND <=", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendLike(String value) {
            addCriterion("STARFRIEND like", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendNotLike(String value) {
            addCriterion("STARFRIEND not like", value, "starfriend");
            return this;
        }

        public Criteria andStarfriendIn(List values) {
            addCriterion("STARFRIEND in", values, "starfriend");
            return this;
        }

        public Criteria andStarfriendNotIn(List values) {
            addCriterion("STARFRIEND not in", values, "starfriend");
            return this;
        }

        public Criteria andStarfriendBetween(String value1, String value2) {
            addCriterion("STARFRIEND between", value1, value2, "starfriend");
            return this;
        }

        public Criteria andStarfriendNotBetween(String value1, String value2) {
            addCriterion("STARFRIEND not between", value1, value2, "starfriend");
            return this;
        }

        public Criteria andAppaccountflagIsNull() {
            addCriterion("APPACCOUNTFLAG is null");
            return this;
        }

        public Criteria andAppaccountflagIsNotNull() {
            addCriterion("APPACCOUNTFLAG is not null");
            return this;
        }

        public Criteria andAppaccountflagEqualTo(String value) {
            addCriterion("APPACCOUNTFLAG =", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagNotEqualTo(String value) {
            addCriterion("APPACCOUNTFLAG <>", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagGreaterThan(String value) {
            addCriterion("APPACCOUNTFLAG >", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagGreaterThanOrEqualTo(String value) {
            addCriterion("APPACCOUNTFLAG >=", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagLessThan(String value) {
            addCriterion("APPACCOUNTFLAG <", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagLessThanOrEqualTo(String value) {
            addCriterion("APPACCOUNTFLAG <=", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagLike(String value) {
            addCriterion("APPACCOUNTFLAG like", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagNotLike(String value) {
            addCriterion("APPACCOUNTFLAG not like", value, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagIn(List values) {
            addCriterion("APPACCOUNTFLAG in", values, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagNotIn(List values) {
            addCriterion("APPACCOUNTFLAG not in", values, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagBetween(String value1, String value2) {
            addCriterion("APPACCOUNTFLAG between", value1, value2, "appaccountflag");
            return this;
        }

        public Criteria andAppaccountflagNotBetween(String value1, String value2) {
            addCriterion("APPACCOUNTFLAG not between", value1, value2, "appaccountflag");
            return this;
        }

        public Criteria andStatuesIsNull() {
            addCriterion("STATUES is null");
            return this;
        }

        public Criteria andStatuesIsNotNull() {
            addCriterion("STATUES is not null");
            return this;
        }

        public Criteria andStatuesEqualTo(String value) {
            addCriterion("STATUES =", value, "statues");
            return this;
        }

        public Criteria andStatuesNotEqualTo(String value) {
            addCriterion("STATUES <>", value, "statues");
            return this;
        }

        public Criteria andStatuesGreaterThan(String value) {
            addCriterion("STATUES >", value, "statues");
            return this;
        }

        public Criteria andStatuesGreaterThanOrEqualTo(String value) {
            addCriterion("STATUES >=", value, "statues");
            return this;
        }

        public Criteria andStatuesLessThan(String value) {
            addCriterion("STATUES <", value, "statues");
            return this;
        }

        public Criteria andStatuesLessThanOrEqualTo(String value) {
            addCriterion("STATUES <=", value, "statues");
            return this;
        }

        public Criteria andStatuesLike(String value) {
            addCriterion("STATUES like", value, "statues");
            return this;
        }

        public Criteria andStatuesNotLike(String value) {
            addCriterion("STATUES not like", value, "statues");
            return this;
        }

        public Criteria andStatuesIn(List values) {
            addCriterion("STATUES in", values, "statues");
            return this;
        }

        public Criteria andStatuesNotIn(List values) {
            addCriterion("STATUES not in", values, "statues");
            return this;
        }

        public Criteria andStatuesBetween(String value1, String value2) {
            addCriterion("STATUES between", value1, value2, "statues");
            return this;
        }

        public Criteria andStatuesNotBetween(String value1, String value2) {
            addCriterion("STATUES not between", value1, value2, "statues");
            return this;
        }

        public Criteria andAttrstatusIsNull() {
            addCriterion("ATTRSTATUS is null");
            return this;
        }

        public Criteria andAttrstatusIsNotNull() {
            addCriterion("ATTRSTATUS is not null");
            return this;
        }

        public Criteria andAttrstatusEqualTo(String value) {
            addCriterion("ATTRSTATUS =", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusNotEqualTo(String value) {
            addCriterion("ATTRSTATUS <>", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusGreaterThan(String value) {
            addCriterion("ATTRSTATUS >", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusGreaterThanOrEqualTo(String value) {
            addCriterion("ATTRSTATUS >=", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusLessThan(String value) {
            addCriterion("ATTRSTATUS <", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusLessThanOrEqualTo(String value) {
            addCriterion("ATTRSTATUS <=", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusLike(String value) {
            addCriterion("ATTRSTATUS like", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusNotLike(String value) {
            addCriterion("ATTRSTATUS not like", value, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusIn(List values) {
            addCriterion("ATTRSTATUS in", values, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusNotIn(List values) {
            addCriterion("ATTRSTATUS not in", values, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusBetween(String value1, String value2) {
            addCriterion("ATTRSTATUS between", value1, value2, "attrstatus");
            return this;
        }

        public Criteria andAttrstatusNotBetween(String value1, String value2) {
            addCriterion("ATTRSTATUS not between", value1, value2, "attrstatus");
            return this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return this;
        }

        public Criteria andProvinceIn(List values) {
            addCriterion("PROVINCE in", values, "province");
            return this;
        }

        public Criteria andProvinceNotIn(List values) {
            addCriterion("PROVINCE not in", values, "province");
            return this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return this;
        }

        public Criteria andCityIn(List values) {
            addCriterion("CITY in", values, "city");
            return this;
        }

        public Criteria andCityNotIn(List values) {
            addCriterion("CITY not in", values, "city");
            return this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("ALIAS is null");
            return this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("ALIAS is not null");
            return this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("ALIAS =", value, "alias");
            return this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("ALIAS <>", value, "alias");
            return this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("ALIAS >", value, "alias");
            return this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("ALIAS >=", value, "alias");
            return this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("ALIAS <", value, "alias");
            return this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("ALIAS <=", value, "alias");
            return this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("ALIAS like", value, "alias");
            return this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("ALIAS not like", value, "alias");
            return this;
        }

        public Criteria andAliasIn(List values) {
            addCriterion("ALIAS in", values, "alias");
            return this;
        }

        public Criteria andAliasNotIn(List values) {
            addCriterion("ALIAS not in", values, "alias");
            return this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("ALIAS between", value1, value2, "alias");
            return this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("ALIAS not between", value1, value2, "alias");
            return this;
        }

        public Criteria andSnsflagIsNull() {
            addCriterion("SNSFLAG is null");
            return this;
        }

        public Criteria andSnsflagIsNotNull() {
            addCriterion("SNSFLAG is not null");
            return this;
        }

        public Criteria andSnsflagEqualTo(String value) {
            addCriterion("SNSFLAG =", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagNotEqualTo(String value) {
            addCriterion("SNSFLAG <>", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagGreaterThan(String value) {
            addCriterion("SNSFLAG >", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagGreaterThanOrEqualTo(String value) {
            addCriterion("SNSFLAG >=", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagLessThan(String value) {
            addCriterion("SNSFLAG <", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagLessThanOrEqualTo(String value) {
            addCriterion("SNSFLAG <=", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagLike(String value) {
            addCriterion("SNSFLAG like", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagNotLike(String value) {
            addCriterion("SNSFLAG not like", value, "snsflag");
            return this;
        }

        public Criteria andSnsflagIn(List values) {
            addCriterion("SNSFLAG in", values, "snsflag");
            return this;
        }

        public Criteria andSnsflagNotIn(List values) {
            addCriterion("SNSFLAG not in", values, "snsflag");
            return this;
        }

        public Criteria andSnsflagBetween(String value1, String value2) {
            addCriterion("SNSFLAG between", value1, value2, "snsflag");
            return this;
        }

        public Criteria andSnsflagNotBetween(String value1, String value2) {
            addCriterion("SNSFLAG not between", value1, value2, "snsflag");
            return this;
        }

        public Criteria andUnifriendIsNull() {
            addCriterion("UNIFRIEND is null");
            return this;
        }

        public Criteria andUnifriendIsNotNull() {
            addCriterion("UNIFRIEND is not null");
            return this;
        }

        public Criteria andUnifriendEqualTo(String value) {
            addCriterion("UNIFRIEND =", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendNotEqualTo(String value) {
            addCriterion("UNIFRIEND <>", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendGreaterThan(String value) {
            addCriterion("UNIFRIEND >", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendGreaterThanOrEqualTo(String value) {
            addCriterion("UNIFRIEND >=", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendLessThan(String value) {
            addCriterion("UNIFRIEND <", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendLessThanOrEqualTo(String value) {
            addCriterion("UNIFRIEND <=", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendLike(String value) {
            addCriterion("UNIFRIEND like", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendNotLike(String value) {
            addCriterion("UNIFRIEND not like", value, "unifriend");
            return this;
        }

        public Criteria andUnifriendIn(List values) {
            addCriterion("UNIFRIEND in", values, "unifriend");
            return this;
        }

        public Criteria andUnifriendNotIn(List values) {
            addCriterion("UNIFRIEND not in", values, "unifriend");
            return this;
        }

        public Criteria andUnifriendBetween(String value1, String value2) {
            addCriterion("UNIFRIEND between", value1, value2, "unifriend");
            return this;
        }

        public Criteria andUnifriendNotBetween(String value1, String value2) {
            addCriterion("UNIFRIEND not between", value1, value2, "unifriend");
            return this;
        }

        public Criteria andDisplaynameIsNull() {
            addCriterion("DISPLAYNAME is null");
            return this;
        }

        public Criteria andDisplaynameIsNotNull() {
            addCriterion("DISPLAYNAME is not null");
            return this;
        }

        public Criteria andDisplaynameEqualTo(String value) {
            addCriterion("DISPLAYNAME =", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotEqualTo(String value) {
            addCriterion("DISPLAYNAME <>", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameGreaterThan(String value) {
            addCriterion("DISPLAYNAME >", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAYNAME >=", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameLessThan(String value) {
            addCriterion("DISPLAYNAME <", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameLessThanOrEqualTo(String value) {
            addCriterion("DISPLAYNAME <=", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameLike(String value) {
            addCriterion("DISPLAYNAME like", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotLike(String value) {
            addCriterion("DISPLAYNAME not like", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameIn(List values) {
            addCriterion("DISPLAYNAME in", values, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotIn(List values) {
            addCriterion("DISPLAYNAME not in", values, "displayname");
            return this;
        }

        public Criteria andDisplaynameBetween(String value1, String value2) {
            addCriterion("DISPLAYNAME between", value1, value2, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotBetween(String value1, String value2) {
            addCriterion("DISPLAYNAME not between", value1, value2, "displayname");
            return this;
        }

        public Criteria andChatroomidIsNull() {
            addCriterion("CHATROOMID is null");
            return this;
        }

        public Criteria andChatroomidIsNotNull() {
            addCriterion("CHATROOMID is not null");
            return this;
        }

        public Criteria andChatroomidEqualTo(String value) {
            addCriterion("CHATROOMID =", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidNotEqualTo(String value) {
            addCriterion("CHATROOMID <>", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidGreaterThan(String value) {
            addCriterion("CHATROOMID >", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidGreaterThanOrEqualTo(String value) {
            addCriterion("CHATROOMID >=", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidLessThan(String value) {
            addCriterion("CHATROOMID <", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidLessThanOrEqualTo(String value) {
            addCriterion("CHATROOMID <=", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidLike(String value) {
            addCriterion("CHATROOMID like", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidNotLike(String value) {
            addCriterion("CHATROOMID not like", value, "chatroomid");
            return this;
        }

        public Criteria andChatroomidIn(List values) {
            addCriterion("CHATROOMID in", values, "chatroomid");
            return this;
        }

        public Criteria andChatroomidNotIn(List values) {
            addCriterion("CHATROOMID not in", values, "chatroomid");
            return this;
        }

        public Criteria andChatroomidBetween(String value1, String value2) {
            addCriterion("CHATROOMID between", value1, value2, "chatroomid");
            return this;
        }

        public Criteria andChatroomidNotBetween(String value1, String value2) {
            addCriterion("CHATROOMID not between", value1, value2, "chatroomid");
            return this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("KEYWORD is null");
            return this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("KEYWORD is not null");
            return this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("KEYWORD =", value, "keyword");
            return this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("KEYWORD <>", value, "keyword");
            return this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("KEYWORD >", value, "keyword");
            return this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("KEYWORD >=", value, "keyword");
            return this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("KEYWORD <", value, "keyword");
            return this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("KEYWORD <=", value, "keyword");
            return this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("KEYWORD like", value, "keyword");
            return this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("KEYWORD not like", value, "keyword");
            return this;
        }

        public Criteria andKeywordIn(List values) {
            addCriterion("KEYWORD in", values, "keyword");
            return this;
        }

        public Criteria andKeywordNotIn(List values) {
            addCriterion("KEYWORD not in", values, "keyword");
            return this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("KEYWORD between", value1, value2, "keyword");
            return this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("KEYWORD not between", value1, value2, "keyword");
            return this;
        }

        public Criteria andEncrychatroomidIsNull() {
            addCriterion("ENCRYCHATROOMID is null");
            return this;
        }

        public Criteria andEncrychatroomidIsNotNull() {
            addCriterion("ENCRYCHATROOMID is not null");
            return this;
        }

        public Criteria andEncrychatroomidEqualTo(String value) {
            addCriterion("ENCRYCHATROOMID =", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidNotEqualTo(String value) {
            addCriterion("ENCRYCHATROOMID <>", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidGreaterThan(String value) {
            addCriterion("ENCRYCHATROOMID >", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidGreaterThanOrEqualTo(String value) {
            addCriterion("ENCRYCHATROOMID >=", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidLessThan(String value) {
            addCriterion("ENCRYCHATROOMID <", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidLessThanOrEqualTo(String value) {
            addCriterion("ENCRYCHATROOMID <=", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidLike(String value) {
            addCriterion("ENCRYCHATROOMID like", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidNotLike(String value) {
            addCriterion("ENCRYCHATROOMID not like", value, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidIn(List values) {
            addCriterion("ENCRYCHATROOMID in", values, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidNotIn(List values) {
            addCriterion("ENCRYCHATROOMID not in", values, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidBetween(String value1, String value2) {
            addCriterion("ENCRYCHATROOMID between", value1, value2, "encrychatroomid");
            return this;
        }

        public Criteria andEncrychatroomidNotBetween(String value1, String value2) {
            addCriterion("ENCRYCHATROOMID not between", value1, value2, "encrychatroomid");
            return this;
        }

        public Criteria andIsownerIsNull() {
            addCriterion("ISOWNER is null");
            return this;
        }

        public Criteria andIsownerIsNotNull() {
            addCriterion("ISOWNER is not null");
            return this;
        }

        public Criteria andIsownerEqualTo(String value) {
            addCriterion("ISOWNER =", value, "isowner");
            return this;
        }

        public Criteria andIsownerNotEqualTo(String value) {
            addCriterion("ISOWNER <>", value, "isowner");
            return this;
        }

        public Criteria andIsownerGreaterThan(String value) {
            addCriterion("ISOWNER >", value, "isowner");
            return this;
        }

        public Criteria andIsownerGreaterThanOrEqualTo(String value) {
            addCriterion("ISOWNER >=", value, "isowner");
            return this;
        }

        public Criteria andIsownerLessThan(String value) {
            addCriterion("ISOWNER <", value, "isowner");
            return this;
        }

        public Criteria andIsownerLessThanOrEqualTo(String value) {
            addCriterion("ISOWNER <=", value, "isowner");
            return this;
        }

        public Criteria andIsownerLike(String value) {
            addCriterion("ISOWNER like", value, "isowner");
            return this;
        }

        public Criteria andIsownerNotLike(String value) {
            addCriterion("ISOWNER not like", value, "isowner");
            return this;
        }

        public Criteria andIsownerIn(List values) {
            addCriterion("ISOWNER in", values, "isowner");
            return this;
        }

        public Criteria andIsownerNotIn(List values) {
            addCriterion("ISOWNER not in", values, "isowner");
            return this;
        }

        public Criteria andIsownerBetween(String value1, String value2) {
            addCriterion("ISOWNER between", value1, value2, "isowner");
            return this;
        }

        public Criteria andIsownerNotBetween(String value1, String value2) {
            addCriterion("ISOWNER not between", value1, value2, "isowner");
            return this;
        }
    }
}