package com.jiuyv.yl.console.lottery.entity;

public class TblWebchantMerchant {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.MERID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String merid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.UIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String uin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.USERNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.NICKNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.HEADIMGURL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String headimgurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.CONTACTFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String contactflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.REMARKNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String remarkname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.HIDEINPUTBARFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String hideinputbarflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.SEX
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.SIGNATURE
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String signature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.VERIFYFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String verifyflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.OWNERUIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String owneruin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.PYINITIAL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String pyinitial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.PYQUANPIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String pyquanpin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.REMARKPYINITIAL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String remarkpyinitial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.REMARKPYQUANPIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String remarkpyquanpin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.STARFRIEND
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String starfriend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.APPACCOUNTFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String appaccountflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.STATUES
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String statues;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.ATTRSTATUS
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String attrstatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.PROVINCE
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.CITY
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.ALIAS
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String alias;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.SNSFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String snsflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.UNIFRIEND
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String unifriend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.DISPLAYNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String displayname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.CHATROOMID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String chatroomid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.KEYWORD
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.ENCRYCHATROOMID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String encrychatroomid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_webchant_merchant.ISOWNER
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    private String isowner;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.MERID
     *
     * @return the value of tbl_webchant_merchant.MERID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getMerid() {
        return merid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.MERID
     *
     * @param merid the value for tbl_webchant_merchant.MERID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setMerid(String merid) {
        this.merid = merid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.UIN
     *
     * @return the value of tbl_webchant_merchant.UIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getUin() {
        return uin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.UIN
     *
     * @param uin the value for tbl_webchant_merchant.UIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setUin(String uin) {
        this.uin = uin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.USERNAME
     *
     * @return the value of tbl_webchant_merchant.USERNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.USERNAME
     *
     * @param username the value for tbl_webchant_merchant.USERNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.NICKNAME
     *
     * @return the value of tbl_webchant_merchant.NICKNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.NICKNAME
     *
     * @param nickname the value for tbl_webchant_merchant.NICKNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.HEADIMGURL
     *
     * @return the value of tbl_webchant_merchant.HEADIMGURL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.HEADIMGURL
     *
     * @param headimgurl the value for tbl_webchant_merchant.HEADIMGURL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.CONTACTFLAG
     *
     * @return the value of tbl_webchant_merchant.CONTACTFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getContactflag() {
        return contactflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.CONTACTFLAG
     *
     * @param contactflag the value for tbl_webchant_merchant.CONTACTFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setContactflag(String contactflag) {
        this.contactflag = contactflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.REMARKNAME
     *
     * @return the value of tbl_webchant_merchant.REMARKNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getRemarkname() {
        return remarkname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.REMARKNAME
     *
     * @param remarkname the value for tbl_webchant_merchant.REMARKNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setRemarkname(String remarkname) {
        this.remarkname = remarkname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.HIDEINPUTBARFLAG
     *
     * @return the value of tbl_webchant_merchant.HIDEINPUTBARFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getHideinputbarflag() {
        return hideinputbarflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.HIDEINPUTBARFLAG
     *
     * @param hideinputbarflag the value for tbl_webchant_merchant.HIDEINPUTBARFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setHideinputbarflag(String hideinputbarflag) {
        this.hideinputbarflag = hideinputbarflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.SEX
     *
     * @return the value of tbl_webchant_merchant.SEX
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.SEX
     *
     * @param sex the value for tbl_webchant_merchant.SEX
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.SIGNATURE
     *
     * @return the value of tbl_webchant_merchant.SIGNATURE
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.SIGNATURE
     *
     * @param signature the value for tbl_webchant_merchant.SIGNATURE
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.VERIFYFLAG
     *
     * @return the value of tbl_webchant_merchant.VERIFYFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getVerifyflag() {
        return verifyflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.VERIFYFLAG
     *
     * @param verifyflag the value for tbl_webchant_merchant.VERIFYFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setVerifyflag(String verifyflag) {
        this.verifyflag = verifyflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.OWNERUIN
     *
     * @return the value of tbl_webchant_merchant.OWNERUIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getOwneruin() {
        return owneruin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.OWNERUIN
     *
     * @param owneruin the value for tbl_webchant_merchant.OWNERUIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setOwneruin(String owneruin) {
        this.owneruin = owneruin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.PYINITIAL
     *
     * @return the value of tbl_webchant_merchant.PYINITIAL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getPyinitial() {
        return pyinitial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.PYINITIAL
     *
     * @param pyinitial the value for tbl_webchant_merchant.PYINITIAL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setPyinitial(String pyinitial) {
        this.pyinitial = pyinitial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.PYQUANPIN
     *
     * @return the value of tbl_webchant_merchant.PYQUANPIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getPyquanpin() {
        return pyquanpin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.PYQUANPIN
     *
     * @param pyquanpin the value for tbl_webchant_merchant.PYQUANPIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setPyquanpin(String pyquanpin) {
        this.pyquanpin = pyquanpin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.REMARKPYINITIAL
     *
     * @return the value of tbl_webchant_merchant.REMARKPYINITIAL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getRemarkpyinitial() {
        return remarkpyinitial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.REMARKPYINITIAL
     *
     * @param remarkpyinitial the value for tbl_webchant_merchant.REMARKPYINITIAL
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setRemarkpyinitial(String remarkpyinitial) {
        this.remarkpyinitial = remarkpyinitial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.REMARKPYQUANPIN
     *
     * @return the value of tbl_webchant_merchant.REMARKPYQUANPIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getRemarkpyquanpin() {
        return remarkpyquanpin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.REMARKPYQUANPIN
     *
     * @param remarkpyquanpin the value for tbl_webchant_merchant.REMARKPYQUANPIN
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setRemarkpyquanpin(String remarkpyquanpin) {
        this.remarkpyquanpin = remarkpyquanpin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.STARFRIEND
     *
     * @return the value of tbl_webchant_merchant.STARFRIEND
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getStarfriend() {
        return starfriend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.STARFRIEND
     *
     * @param starfriend the value for tbl_webchant_merchant.STARFRIEND
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setStarfriend(String starfriend) {
        this.starfriend = starfriend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.APPACCOUNTFLAG
     *
     * @return the value of tbl_webchant_merchant.APPACCOUNTFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getAppaccountflag() {
        return appaccountflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.APPACCOUNTFLAG
     *
     * @param appaccountflag the value for tbl_webchant_merchant.APPACCOUNTFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setAppaccountflag(String appaccountflag) {
        this.appaccountflag = appaccountflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.STATUES
     *
     * @return the value of tbl_webchant_merchant.STATUES
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getStatues() {
        return statues;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.STATUES
     *
     * @param statues the value for tbl_webchant_merchant.STATUES
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setStatues(String statues) {
        this.statues = statues;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.ATTRSTATUS
     *
     * @return the value of tbl_webchant_merchant.ATTRSTATUS
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getAttrstatus() {
        return attrstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.ATTRSTATUS
     *
     * @param attrstatus the value for tbl_webchant_merchant.ATTRSTATUS
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setAttrstatus(String attrstatus) {
        this.attrstatus = attrstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.PROVINCE
     *
     * @return the value of tbl_webchant_merchant.PROVINCE
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.PROVINCE
     *
     * @param province the value for tbl_webchant_merchant.PROVINCE
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.CITY
     *
     * @return the value of tbl_webchant_merchant.CITY
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.CITY
     *
     * @param city the value for tbl_webchant_merchant.CITY
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.ALIAS
     *
     * @return the value of tbl_webchant_merchant.ALIAS
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.ALIAS
     *
     * @param alias the value for tbl_webchant_merchant.ALIAS
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.SNSFLAG
     *
     * @return the value of tbl_webchant_merchant.SNSFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getSnsflag() {
        return snsflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.SNSFLAG
     *
     * @param snsflag the value for tbl_webchant_merchant.SNSFLAG
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setSnsflag(String snsflag) {
        this.snsflag = snsflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.UNIFRIEND
     *
     * @return the value of tbl_webchant_merchant.UNIFRIEND
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getUnifriend() {
        return unifriend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.UNIFRIEND
     *
     * @param unifriend the value for tbl_webchant_merchant.UNIFRIEND
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setUnifriend(String unifriend) {
        this.unifriend = unifriend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.DISPLAYNAME
     *
     * @return the value of tbl_webchant_merchant.DISPLAYNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.DISPLAYNAME
     *
     * @param displayname the value for tbl_webchant_merchant.DISPLAYNAME
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.CHATROOMID
     *
     * @return the value of tbl_webchant_merchant.CHATROOMID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getChatroomid() {
        return chatroomid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.CHATROOMID
     *
     * @param chatroomid the value for tbl_webchant_merchant.CHATROOMID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setChatroomid(String chatroomid) {
        this.chatroomid = chatroomid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.KEYWORD
     *
     * @return the value of tbl_webchant_merchant.KEYWORD
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.KEYWORD
     *
     * @param keyword the value for tbl_webchant_merchant.KEYWORD
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.ENCRYCHATROOMID
     *
     * @return the value of tbl_webchant_merchant.ENCRYCHATROOMID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getEncrychatroomid() {
        return encrychatroomid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.ENCRYCHATROOMID
     *
     * @param encrychatroomid the value for tbl_webchant_merchant.ENCRYCHATROOMID
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setEncrychatroomid(String encrychatroomid) {
        this.encrychatroomid = encrychatroomid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_webchant_merchant.ISOWNER
     *
     * @return the value of tbl_webchant_merchant.ISOWNER
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public String getIsowner() {
        return isowner;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_webchant_merchant.ISOWNER
     *
     * @param isowner the value for tbl_webchant_merchant.ISOWNER
     *
     * @ibatorgenerated Sat Oct 28 23:54:59 CST 2017
     */
    public void setIsowner(String isowner) {
        this.isowner = isowner;
    }
}