package com.jiuyv.yl.console.common.dao.inter ;

import com.jiuyv.yl.console.common.entity.CmMediaResVo;

// Generated by AutoCode4J
/**
 * Interface: 媒体资源 : TBL_CM_MEDIA_RES
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface ICmMediaResDao extends IBaseDao<CmMediaResVo>{
	
	/** mapped key is : com.jiuyv.yl.model.common.dao.CmMediaResDao.filterQuery */
//	String MAPPED_FIND = "com.jiuyv.yl.model.common.dao.CmMediaResDao.filterQuery";

	/**
	 * Find CmMediaResVo by Primary Key. 
	 * 
	 * @param medSeq : 内部序号	 
	 * @return CmMediaResVo : 媒体资源
	 */
	CmMediaResVo findByKey(Long medSeq ) ;
	
	/**
	 * Find thumb by path.
	 * 获取缩略图
	 * 
	 * @param medPath the med path
	 * @return the res media vo
	 */
	CmMediaResVo findThumbByPath(String medPath);

	/**
	 * Find content by path.
	 * 获取完整图片
	 * 
	 * @param medPath the med path
	 * @return the res media vo
	 */
	CmMediaResVo findContentByPath(String medPath);
	
	/**
	 * Find thumb by path.
	 * 获取缩略图
	 *
	 * @param medSeq the med seq
	 * @param refNo the ref no
	 * @return the res media vo
	 */
	CmMediaResVo findThumbByMedSeqRefNo(String medSeq, String refNo);

	/**
	 * Find content by path.
	 * 获取完整图片
	 *
	 * @param medSeq the med seq
	 * @param refNo the ref no
	 * @return the res media vo
	 */
	CmMediaResVo findContentByMedSeqRefNo(String medSeq, String refNo);
	
	/**
	 * Update CmMediaResVo by Primary Key.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateByKey(CmMediaResVo vo);


}